/* ***********************************
 * 	@Copyright : NURITelecom
 * 	@ProjectName : aimir-mdms-iesco
 * 	@FileName : CREATE_MDM_TABLES.sql
 * 	@Author : kyunghee.yoon
 * 	@Date : 2019.05.09
 *************************************/  

/* ===================================
 * 	@tablespace : MDM_DATA_TS
 * =================================== */
CREATE TABLESPACE MDM_DATA_TS DATAFILE
    '/oracle/oradata/aimirdat/MDM_DATA_TS.dbf' SIZE 10M;
ALTER DATABASE DATAFILE '/oracle/oradata/aimirdat/MDM_DATA_TS.dbf' AUTOEXTEND ON;

/* ===================================
 * 	@tablespace : MDM_IDX_TS
 * =================================== */
CREATE TABLESPACE MDM_IDX_TS DATAFILE
    '/oracle/oradata/aimirdat/MDM_IDX_TS.dbf' SIZE 10M;
ALTER DATABASE DATAFILE '/oracle/oradata/aimirdat/MDM_IDX_TS.dbf' AUTOEXTEND ON;


/* ===================================
 * 	@tablespace : AIMIR 계정 권한부여
 * =================================== */
grant unlimited tablespace to AIMIR ;

/* ===================================
 * 	@sequence : SEQ_MDM_BATCH
 * =================================== */
CREATE SEQUENCE "SEQ_MDM_BATCH"  MINVALUE 1 MAXVALUE 99999999999999999999 INCREMENT BY 1 START WITH 1 CYCLE;

/* ===================================
 * 	@tablespace : MDM_BATCH_LOG
 * =================================== */  
CREATE TABLE "MDM_BATCH_LOG" 
(	
	"BATCH_ID" NUMBER(20,0) NOT NULL, 
	"BATCH_TYPE" VARCHAR2(20 BYTE) NOT NULL, 
	"BATCH_STATUS" CHAR(1 BYTE) DEFAULT '1' NOT NULL, 
	"BATCH_CNT" NUMBER(10,0) NOT NULL, 
	"BATCH_DATETIME" VARCHAR2(14 BYTE) DEFAULT TO_CHAR(SYSDATE,'yyyymmddhh24miss') NOT NULL, 
	 CONSTRAINT "PK_MDM_BATCH_LOG" PRIMARY KEY ("BATCH_ID")	
)
TABLESPACE "MDM_DATA_TS" ;

CREATE INDEX "IDX_MDM_BATCH_LOG_01" ON "MDM_BATCH_LOG" ("BATCH_TYPE", "BATCH_STATUS", "BATCH_DATETIME")   
TABLESPACE "MDM_IDX_TS" LOCAL;

/* ===================================
 * 	@tablespace : MDM_LP_EM
 * =================================== */  
DROP TABLE "MDM_LP_EM" CASCADE CONSTRAINTS;
CREATE TABLE "MDM_LP_EM" 
(	
	"MDEV_ID" 			VARCHAR2(20) NOT NULL, 
	"YYYYMMDDHHMMSS" 	VARCHAR2(14) NOT NULL, 
	"MDEV_TYPE" 		VARCHAR2(20) NOT NULL, 	
	"DST"		 		NUMBER(38,0) NOT NULL, 	
	"METER_ID"			NUMBER(10,0) NOT NULL, 	
	"INSTALL_PROPERTY"  VARCHAR2(10),		
	"CH1" 				FLOAT(126),
	"CH2" 				FLOAT(126),
	"CH3" 				FLOAT(126),
	"CH4" 				FLOAT(126),
	"CH5" 				FLOAT(126),
	"CH6" 				FLOAT(126),
	"CH7" 				FLOAT(126),
	"CH8" 				FLOAT(126),
	"CH9" 				FLOAT(126),
	"CH10" 				FLOAT(126),
	"CH11" 				FLOAT(126),
	"CH12" 				FLOAT(126),	
	"CH13" 				FLOAT(126),	
	"CH14" 				FLOAT(126),	
	"CH15" 				FLOAT(126),		
	"WRITEDATE" 		VARCHAR2(14) NOT NULL, 
	"BATCH_ID" 			NUMBER(20,0), 
	"TRANSFER_DATETIME" VARCHAR2(14), 	
	"INSERT_DATETIME" 	VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'yyyymmddhh24miss') NOT NULL, 
	CONSTRAINT "PK_MDM_LP_EM" PRIMARY KEY ("MDEV_ID", "YYYYMMDDHHMMSS", "MDEV_TYPE", "DST")	
) TABLESPACE "MDM_DATA_TS"
partition by range (YYYYMMDDHHMMSS)
(
   partition MDM_LP_EM_LOG_201909 values less than ('20191001000000') TABLESPACE "MDM_DATA_TS"
);


--인덱스 생성
CREATE INDEX "IDX_MDM_LP_EM_01" ON "MDM_LP_EM" ("BATCH_ID", "INSERT_DATETIME")   
TABLESPACE "MDM_IDX_TS" LOCAL;

CREATE INDEX "IDX_MDM_LP_EM_02" ON "MDM_LP_EM" ("YYYYMMDDHHMMSS")   
TABLESPACE "MDM_IDX_TS" LOCAL;

CREATE INDEX "IDX_MDM_LP_EM_03" ON "MDM_LP_EM" ("MDEV_ID")   
TABLESPACE "MDM_IDX_TS" LOCAL;


/* ===================================
 * 	@tablespace : MDM_BILLING_DAY_EM
 * =================================== */  
DROP TABLE "MDM_BILLING_DAY_EM" CASCADE CONSTRAINTS;
CREATE TABLE "MDM_BILLING_DAY_EM" 
(	
	"MDEV_ID" 			VARCHAR2(20) NOT NULL,
	"MDEV_TYPE"			NUMBER(10,0) NOT NULL,	
	"YYYYMMDD" 			VARCHAR2(8) NOT NULL, 	
	"HHMMSS" 			VARCHAR2(6) NOT NULL,	
	"CUMULACTIVEENGYIMPORT"				FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE1"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE2"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE3"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE4"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE5"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE6"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE7"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE8"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORT"			FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE1"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE2"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE3"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE4"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE5"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE6"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE7"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE8"		FLOAT(126),	
	"WRITEDATE" 		VARCHAR2(14) NOT NULL, 
	"BATCH_ID" 			NUMBER(20,0), 
	"TRANSFER_DATETIME" VARCHAR2(14), 	
	"INSERT_DATETIME" 	VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'yyyymmddhh24miss') NOT NULL, 
	CONSTRAINT "PK_MDM_BILLING_DAY_EM" PRIMARY KEY ("MDEV_ID", "MDEV_TYPE", "YYYYMMDD", "HHMMSS")	
) TABLESPACE "MDM_DATA_TS" 
partition by range (YYYYMMDD)
(
   partition MDM_BILLING_DAY_EM_201909 values less than ('20191001') TABLESPACE "MDM_DATA_TS"
);

--인덱스 생성
CREATE INDEX "IDX_MDM_BILLING_DAY_EM_01" ON "MDM_BILLING_DAY_EM" ("BATCH_ID", "INSERT_DATETIME")   
TABLESPACE "MDM_IDX_TS" LOCAL;

CREATE INDEX "IDX_MDM_BILLING_DAY_EM_02" ON "MDM_BILLING_DAY_EM" ("MDEV_ID")  
TABLESPACE "MDM_IDX_TS" LOCAL; 

CREATE INDEX "IDX_MDM_BILLING_DAY_EM_03" ON "MDM_BILLING_DAY_EM" ("YYYYMMDD")    
TABLESPACE "MDM_IDX_TS" LOCAL; 

/* ===================================
 * 	@tablespace : MDM_BILLING_MONTH_EM
 * =================================== */  
DROP TABLE "MDM_BILLING_MONTH_EM" CASCADE CONSTRAINTS;
CREATE TABLE "MDM_BILLING_MONTH_EM" 
(	
	"MDEV_ID" 			VARCHAR2(20) NOT NULL, 
	"MDEV_TYPE"			NUMBER(10,0) NOT NULL,
	"YYYYMMDD" 			VARCHAR2(8) NOT NULL, 
	"HHMMSS" 			VARCHAR2(6) NOT NULL,	
	"CUMULACTIVEENGYIMPORT"				FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE1"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE2"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE3"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE4"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE5"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE6"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE7"		FLOAT(126),
	"CUMULACTIVEENGYIMPORTRATE8"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORT"			FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE1"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE2"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE3"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE4"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE5"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE6"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE7"		FLOAT(126),
	"CUMULREACTIVEENGYIMPORTRATE8"		FLOAT(126),	
	"ACTIVEPWRDMDMAXTIMERATETOT"		VARCHAR2(14),	
	"ACTIVEPWRMAXDMDRATETOT"			FLOAT(126),	
	"WRITEDATE" 		VARCHAR2(14) NOT NULL, 
	"BATCH_ID" 			NUMBER(20,0), 
	"TRANSFER_DATETIME" VARCHAR2(14), 	
	"INSERT_DATETIME" 	VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'yyyymmddhh24miss') NOT NULL, 
	CONSTRAINT "PK_MDM_BILLING_MONTH_EM" PRIMARY KEY ("MDEV_ID", "MDEV_TYPE", "YYYYMMDD", "HHMMSS")	
)  TABLESPACE "MDM_DATA_TS" 
partition by range (YYYYMMDD)
(
   partition MDM_BILLING_MONTH_EM_201909 values less than ('20191001') TABLESPACE "MDM_DATA_TS"
);

--인덱스 생성
CREATE INDEX "IDX_MDM_BILLING_MONTH_EM_01" ON "MDM_BILLING_MONTH_EM" ("BATCH_ID", "INSERT_DATETIME")   
TABLESPACE "MDM_IDX_TS" LOCAL;

CREATE INDEX "IDX_MDM_BILLING_MONTH_EM_02" ON "MDM_BILLING_MONTH_EM" ("MDEV_ID")   
TABLESPACE "MDM_IDX_TS" LOCAL; 

CREATE INDEX "IDX_MDM_BILLING_MONTH_EM_03" ON "MDM_BILLING_MONTH_EM" ("YYYYMMDD")   
TABLESPACE "MDM_IDX_TS" LOCAL; 


/* ===================================
 * 	@tablespace : MDM_METEREVENT_LOG
 * =================================== */  
DROP TABLE "MDM_METEREVENT_LOG" CASCADE CONSTRAINTS;
CREATE TABLE "MDM_METEREVENT_LOG" 
(
	"ACTIVATOR_ID" 		VARCHAR2(100) NOT NULL, 
	"METEREVENT_ID" 	VARCHAR2(100) NOT NULL, 
	"OPEN_TIME" 		VARCHAR2(14) NOT NULL,
	"ACTIVATOR_TYPE" 	VARCHAR2(255) NOT NULL,
	"MESSAGE"           VARCHAR2(255),
	"WRITETIME" 		VARCHAR2(14) NOT NULL, 
	"BATCH_ID" 			NUMBER(20,0), 
	"TRANSFER_DATETIME" VARCHAR2(14), 	
	"INSERT_DATETIME" 	VARCHAR2(14) DEFAULT TO_CHAR(SYSDATE,'yyyymmddhh24miss') NOT NULL, 
	CONSTRAINT "PK_MDM_METEREVENT_LOG" PRIMARY KEY ("ACTIVATOR_ID", "METEREVENT_ID", "OPEN_TIME", "ACTIVATOR_TYPE")	
)  TABLESPACE "MDM_DATA_TS" 
partition by range (OPEN_TIME)
(
   partition MDM_METEREVENT_LOG_201909 values less than ('20191001000000') TABLESPACE "MDM_DATA_TS"
);

--인덱스 생성
CREATE INDEX "IDX_MDM_METEREVENT_LOG_01" ON "MDM_METEREVENT_LOG" ("BATCH_ID", "INSERT_DATETIME")   
TABLESPACE "MDM_IDX_TS" LOCAL;

CREATE INDEX "IDX_MDM_METEREVENT_LOG_02" ON "MDM_METEREVENT_LOG" ("ACTIVATOR_ID")   
TABLESPACE "MDM_IDX_TS" LOCAL; 

CREATE INDEX "IDX_MDM_METEREVENT_LOG_03" ON "MDM_METEREVENT_LOG" ("OPEN_TIME")   
TABLESPACE "MDM_IDX_TS" LOCAL; 

/* ===================================
 * 	@tablespace : MDM_BATCH_LOG
 * =================================== */ 
DROP TABLE "MDM_BATCH_LOG" CASCADE CONSTRAINTS;
CREATE TABLE "MDM_BATCH_LOG" (	
	"BATCH_ID" NUMBER(20,0) NOT NULL ENABLE, 
	"BATCH_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BATCH_STATUS" CHAR(1 BYTE) DEFAULT '1' NOT NULL ENABLE, 
	"BATCH_CNT" NUMBER(10,0) NOT NULL ENABLE, 
	"BATCH_DATETIME" VARCHAR2(14 BYTE) DEFAULT TO_CHAR(SYSDATE,'yyyymmddhh24miss') NOT NULL ENABLE, 
	CONSTRAINT "PK_MDM_BATCH_LOG" PRIMARY KEY ("BATCH_ID")	
)
TABLESPACE "MDM_DATA_TS";

CREATE INDEX "IDX_MDM_BATCH_LOG_01" ON "MDM_BATCH_LOG" ("BATCH_TYPE", "BATCH_STATUS", "BATCH_DATETIME")   
TABLESPACE "MDM_IDX_TS";
