/* ***********************************
 * 	@Copyright : NURITelecom
 * 	@ProjectName : aimir_mdms_moe
 * 	@FileName : PKG_MDM_DEL_DATA.sql
 * 	@Author : kyunghee.yoon
 * 	@Date : 2018.09.20
 *************************************/ 
 
create or replace PACKAGE PKG_MDM_DEL_DATA AS 
	
	PROCEDURE DELETE_MDM_DATA;

END PKG_MDM_DEL_DATA;
 
create or replace PACKAGE BODY PKG_MDM_DEL_DATA AS  

	PROCEDURE DELETE_MDM_DATA  
	AS 		
		V_LIMIT NUMBER :=2000; 
		V_START_DATE VARCHAR(8) :=NULL; 
		V_END_DATE VARCHAR(8) :=NULL; 
		V_START_DATE1 VARCHAR(8) :=NULL; 
		V_END_DATE1 VARCHAR(8) :=NULL; 
	BEGIN 

		SELECT TO_CHAR(SYSDATE-30,'YYYYMMDD') INTO V_START_DATE FROM DUAL;
		SELECT TO_CHAR(SYSDATE-30,'YYYYMMDD') INTO V_END_DATE FROM DUAL; 

		-- DELETE MDM_LP_EM_
		DELETE FROM MDM_LP_EM
		WHERE INSERT_DATETIME BETWEEN V_START_DATE || '000000' AND V_END_DATE || '235959' AND ROWNUM <= V_LIMIT;
		
		-- MDM_BILLING_DAY_EM
		DELETE FROM MDM_BILLING_DAY_EM WHERE INSERT_DATETIME BETWEEN V_START_DATE || '000000' AND V_END_DATE || '235959' AND ROWNUM <= V_LIMIT;

		-- MDM_BILLING_MONTH_EM
		DELETE FROM MDM_BILLING_MONTH_EM WHERE INSERT_DATETIME BETWEEN V_START_DATE || '000000' AND V_END_DATE || '235959' AND ROWNUM <= V_LIMIT;

		-- MDM_METEREVENT_LOG
		DELETE FROM MDM_METEREVENT_LOG WHERE INSERT_DATETIME BETWEEN V_START_DATE || '000000' AND V_END_DATE || '235959' AND ROWNUM <= V_LIMIT;

		-- MDM_BATCH_LOG
		DELETE FROM MDM_BATCH_LOG WHERE BATCH_DATETIME BETWEEN V_START_DATE || '000000' AND V_END_DATE || '235959' AND ROWNUM <= V_LIMIT;

	END; 

END PKG_MDM_DEL_DATA;