/* ***********************************
 * 	@Copyright : NURITelecom
 * 	@ProjectName : aimir_mdms_evn
 * 	@FileName : TRG_LP_EM.sql
 * 	@Author : kyunghee.yoon
 * 	@Date : 2018.06.11
 *************************************/

create or replace TRIGGER TRG_LP_EM
AFTER INSERT OR UPDATE ON LP_EM 
FOR EACH ROW 
DECLARE 
BEGIN 

	IF (:OLD.VALUE_00 IS NULL AND :NEW.VALUE_00 IS NOT NULL) OR :OLD.VALUE_00 != :NEW.VALUE_00 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0000', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_00, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_01 IS NULL AND :NEW.VALUE_01 IS NOT NULL) OR :OLD.VALUE_01 != :NEW.VALUE_01 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0100', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_01, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_02 IS NULL AND :NEW.VALUE_02 IS NOT NULL) OR :OLD.VALUE_02 != :NEW.VALUE_02 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0200', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_02, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_03 IS NULL AND :NEW.VALUE_03 IS NOT NULL) OR :OLD.VALUE_03 != :NEW.VALUE_03 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0300', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_03, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_04 IS NULL AND :NEW.VALUE_04 IS NOT NULL) OR :OLD.VALUE_04 != :NEW.VALUE_04 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0400', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_04, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_05 IS NULL AND :NEW.VALUE_05 IS NOT NULL) OR :OLD.VALUE_05 != :NEW.VALUE_05 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0500', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_05, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_06 IS NULL AND :NEW.VALUE_06 IS NOT NULL) OR :OLD.VALUE_06 != :NEW.VALUE_06 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0600', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_06, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_07 IS NULL AND :NEW.VALUE_07 IS NOT NULL) OR :OLD.VALUE_07 != :NEW.VALUE_07 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0700', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_07, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_08 IS NULL AND :NEW.VALUE_08 IS NOT NULL) OR :OLD.VALUE_08 != :NEW.VALUE_08 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0800', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_08, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_09 IS NULL AND :NEW.VALUE_09 IS NOT NULL) OR :OLD.VALUE_09 != :NEW.VALUE_09 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'0900', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_09, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_10 IS NULL AND :NEW.VALUE_10 IS NOT NULL) OR :OLD.VALUE_10 != :NEW.VALUE_10 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1000', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_10, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_11 IS NULL AND :NEW.VALUE_11 IS NOT NULL) OR :OLD.VALUE_11 != :NEW.VALUE_11 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1100', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_11, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_12 IS NULL AND :NEW.VALUE_12 IS NOT NULL) OR :OLD.VALUE_12 != :NEW.VALUE_12 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1200', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_12, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_13 IS NULL AND :NEW.VALUE_13 IS NOT NULL) OR :OLD.VALUE_13 != :NEW.VALUE_13 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1300', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_13, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_14 IS NULL AND :NEW.VALUE_14 IS NOT NULL) OR :OLD.VALUE_14 != :NEW.VALUE_14 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1400', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_14, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_15 IS NULL AND :NEW.VALUE_15 IS NOT NULL) OR :OLD.VALUE_15 != :NEW.VALUE_15 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1500', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_15, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_16 IS NULL AND :NEW.VALUE_16 IS NOT NULL) OR :OLD.VALUE_16 != :NEW.VALUE_16 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1600', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_16, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_17 IS NULL AND :NEW.VALUE_17 IS NOT NULL) OR :OLD.VALUE_17 != :NEW.VALUE_17 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1700', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_17, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_18 IS NULL AND :NEW.VALUE_18 IS NOT NULL) OR :OLD.VALUE_18 != :NEW.VALUE_18 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1800', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_18, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_19 IS NULL AND :NEW.VALUE_19 IS NOT NULL) OR :OLD.VALUE_19 != :NEW.VALUE_19 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'1900', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_19, :NEW.WRITEDATE);
	END IF; 

	IF (:OLD.VALUE_20 IS NULL AND :NEW.VALUE_20 IS NOT NULL) OR :OLD.VALUE_20 != :NEW.VALUE_20 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2000', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_20, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_21 IS NULL AND :NEW.VALUE_21 IS NOT NULL) OR :OLD.VALUE_21 != :NEW.VALUE_21 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2100', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_21, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_22 IS NULL AND :NEW.VALUE_22 IS NOT NULL) OR :OLD.VALUE_22 != :NEW.VALUE_22 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2200', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_22, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_23 IS NULL AND :NEW.VALUE_23 IS NOT NULL) OR :OLD.VALUE_23 != :NEW.VALUE_23 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2300', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_23, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_24 IS NULL AND :NEW.VALUE_24 IS NOT NULL) OR :OLD.VALUE_24 != :NEW.VALUE_24 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2400', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_24, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_25 IS NULL AND :NEW.VALUE_25 IS NOT NULL) OR :OLD.VALUE_25 != :NEW.VALUE_25 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2500', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_25, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_26 IS NULL AND :NEW.VALUE_26 IS NOT NULL) OR :OLD.VALUE_26 != :NEW.VALUE_26 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2600', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_26, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_27 IS NULL AND :NEW.VALUE_27 IS NOT NULL) OR :OLD.VALUE_27 != :NEW.VALUE_27 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2700', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_27, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_28 IS NULL AND :NEW.VALUE_28 IS NOT NULL) OR :OLD.VALUE_28 != :NEW.VALUE_28 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2800', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_28, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_29 IS NULL AND :NEW.VALUE_29 IS NOT NULL) OR :OLD.VALUE_29 != :NEW.VALUE_29 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'2900', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_29, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_30 IS NULL AND :NEW.VALUE_30 IS NOT NULL) OR :OLD.VALUE_30 != :NEW.VALUE_30 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3000', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_30, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_31 IS NULL AND :NEW.VALUE_31 IS NOT NULL) OR :OLD.VALUE_31 != :NEW.VALUE_31 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3100', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_31, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_32 IS NULL AND :NEW.VALUE_32 IS NOT NULL) OR :OLD.VALUE_32 != :NEW.VALUE_32 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3200', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_32, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_33 IS NULL AND :NEW.VALUE_33 IS NOT NULL) OR :OLD.VALUE_33 != :NEW.VALUE_33 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3300', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_33, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_34 IS NULL AND :NEW.VALUE_34 IS NOT NULL) OR :OLD.VALUE_34 != :NEW.VALUE_34 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3400', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_34, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_35 IS NULL AND :NEW.VALUE_35 IS NOT NULL) OR :OLD.VALUE_35 != :NEW.VALUE_35 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3500', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_35, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_36 IS NULL AND :NEW.VALUE_36 IS NOT NULL) OR :OLD.VALUE_36 != :NEW.VALUE_36 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3600', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_36, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_37 IS NULL AND :NEW.VALUE_37 IS NOT NULL) OR :OLD.VALUE_37 != :NEW.VALUE_37 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3700', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_37, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_38 IS NULL AND :NEW.VALUE_38 IS NOT NULL) OR :OLD.VALUE_38 != :NEW.VALUE_38 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3800', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_38, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_39 IS NULL AND :NEW.VALUE_39 IS NOT NULL) OR :OLD.VALUE_39 != :NEW.VALUE_39 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'3900', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_39, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_40 IS NULL AND :NEW.VALUE_40 IS NOT NULL) OR :OLD.VALUE_40 != :NEW.VALUE_40 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4000', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_40, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_41 IS NULL AND :NEW.VALUE_41 IS NOT NULL) OR :OLD.VALUE_41 != :NEW.VALUE_41 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4100', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_41, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_42 IS NULL AND :NEW.VALUE_42 IS NOT NULL) OR :OLD.VALUE_42 != :NEW.VALUE_42 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4200', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_42, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_43 IS NULL AND :NEW.VALUE_43 IS NOT NULL) OR :OLD.VALUE_43 != :NEW.VALUE_43 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4300', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_43, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_44 IS NULL AND :NEW.VALUE_44 IS NOT NULL) OR :OLD.VALUE_44 != :NEW.VALUE_44 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4400', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_44, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_45 IS NULL AND :NEW.VALUE_45 IS NOT NULL) OR :OLD.VALUE_45 != :NEW.VALUE_45 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4500', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_45, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_46 IS NULL AND :NEW.VALUE_46 IS NOT NULL) OR :OLD.VALUE_46 != :NEW.VALUE_46 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4600', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_46, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_47 IS NULL AND :NEW.VALUE_47 IS NOT NULL) OR :OLD.VALUE_47 != :NEW.VALUE_47 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4700', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_47, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_48 IS NULL AND :NEW.VALUE_48 IS NOT NULL) OR :OLD.VALUE_48 != :NEW.VALUE_48 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4800', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_48, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_49 IS NULL AND :NEW.VALUE_49 IS NOT NULL) OR :OLD.VALUE_49 != :NEW.VALUE_49 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'4900', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_49, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_50 IS NULL AND :NEW.VALUE_50 IS NOT NULL) OR :OLD.VALUE_50 != :NEW.VALUE_50 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5000', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_50, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_51 IS NULL AND :NEW.VALUE_51 IS NOT NULL) OR :OLD.VALUE_51 != :NEW.VALUE_51 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5100', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_51, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_52 IS NULL AND :NEW.VALUE_52 IS NOT NULL) OR :OLD.VALUE_52 != :NEW.VALUE_52 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5200', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_52, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_53 IS NULL AND :NEW.VALUE_53 IS NOT NULL) OR :OLD.VALUE_53 != :NEW.VALUE_53 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5300', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_53, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_54 IS NULL AND :NEW.VALUE_54 IS NOT NULL) OR :OLD.VALUE_54 != :NEW.VALUE_54 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5400', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_54, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_55 IS NULL AND :NEW.VALUE_55 IS NOT NULL) OR :OLD.VALUE_55 != :NEW.VALUE_55 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5500', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_55, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_56 IS NULL AND :NEW.VALUE_56 IS NOT NULL) OR :OLD.VALUE_56 != :NEW.VALUE_56 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5600', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_56, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_57 IS NULL AND :NEW.VALUE_57 IS NOT NULL) OR :OLD.VALUE_57 != :NEW.VALUE_57 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5700', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_57, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_58 IS NULL AND :NEW.VALUE_58 IS NOT NULL) OR :OLD.VALUE_58 != :NEW.VALUE_58 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5800', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_58, :NEW.WRITEDATE);
	END IF;	 

	IF (:OLD.VALUE_59 IS NULL AND :NEW.VALUE_59 IS NOT NULL) OR :OLD.VALUE_59 != :NEW.VALUE_59 THEN 
		PKG_MDM_DATA.INSERT_MDM_LP_EM(:NEW.MDEV_ID, :NEW.YYYYMMDDHH||'5900', :NEW.MDEV_TYPE, :NEW.DST, :NEW.METER_ID, :NEW.CHANNEL, :NEW.VALUE_59, :NEW.WRITEDATE);
	END IF;	 

END;