<%@ page language="java" contentType="text/javascript; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="/taglibs.jsp"%>
var GLOBAL_CONTEXT = {
	CONTEXT: "${ctx}",
	GADGET: "FacilityMgmt",
	SIZE: "MAX",
	I18N: {
		'aimir.save2': '<fmt:message key="aimir.save2"/>',
		'aimir.cancel': '<fmt:message key="aimir.cancel"/>',
		'aimir.vendor': '<fmt:message key="aimir.vendor"/>',
		'aimir.msg.updateconfirm': '<fmt:message key="aimir.msg.updateconfirm"/>',
		'aimir.msg.deleteconfirm': '<fmt:message key="aimir.msg.deleteconfirm"/>',
		'aimir.msg.deletesuccess': '<fmt:message key="aimir.msg.deletesuccess"/>',
		'aimir.bems.facilityMgmt.add': '<fmt:message key="aimir.bems.facilityMgmt.add"/>',
		'aimir.bems.facilityMgmt.update': '<fmt:message key="aimir.bems.facilityMgmt.update"/>',
		'aimir.bemsfacilityMgmt.delete': '<fmt:message key="aimir.bemsfacilityMgmt.delete"/>',
		'aimir.facility.number': '<fmt:message key="aimir.facility.number"/>',
		'aimir.bems.facilityMgmt.count': '<fmt:message key="aimir.bems.facilityMgmt.count"/>',
		'aimir.bems.facilityMgmt.operation': '<fmt:message key="aimir.bems.facilityMgmt.operation"/>',
		'aimir.stop': '<fmt:message key="aimir.stop"/>',
		'aimir.unknown': '<fmt:message key="aimir.unknown"/>',
		'aimir.bems.facilityMgmt.location': '<fmt:message key="aimir.bems.facilityMgmt.location"/>',
		'aimir.bems.facilityMgmt.kind': '<fmt:message key="aimir.bems.facilityMgmt.kind"/>',
		'aimir.bems.facilityMgmt.name': '<fmt:message key="aimir.bems.facilityMgmt.name"/>',
		'aimir.afterChange': '<fmt:message key="aimir.afterChange"/>',
		'aimir.facilityMgmt.energy': '<fmt:message key="aimir.facilityMgmt.energy"/>',
		'aimir.facilityMgmt.water': '<fmt:message key="aimir.facilityMgmt.water"/>',
		'aimir.facilityMgmt.gas': '<fmt:message key="aimir.facilityMgmt.gas"/>',
		'aimir.facilityMgmt.heat': '<fmt:message key="aimir.facilityMgmt.heat"/>',
		'aimir.bems.facilityMgmt.changeDate': '<fmt:message key="aimir.bems.facilityMgmt.changeDate"/>',
		'aimir.facilityMgmt.operating.status': '<fmt:message key="aimir.facilityMgmt.operating.status"/>',
		'aimir.facilityMgmt.operating.status.history': '<fmt:message key="aimir.facilityMgmt.operating.status.history"/>',
		'aimir.facilityMgmt.operating.status.chart': '<fmt:message key="aimir.facilityMgmt.operating.status.chart"/>',
		'aimir.facilityMgmt.situation': '<fmt:message key="aimir.facilityMgmt.situation"/>',
		'aimir.bems.facilityMgmt.kind': '<fmt:message key="aimir.bems.facilityMgmt.kind"/>',
		'aimir.equipvendor': '<fmt:message key="aimir.equipvendor"/>',
		'aimir.model': '<fmt:message key="aimir.model"/>',
		'aimir.name': '<fmt:message key="aimir.name"/>',
		'aimir.installdate': '<fmt:message key="aimir.installdate"/>',
		'aimir.facilityMgmt.manufactureDate': '<fmt:message key="aimir.facilityMgmt.manufactureDate"/>',
		'aimir.facilityMgmt.powerConsumption': '<fmt:message key="aimir.facilityMgmt.powerConsumption"/>',
		'aimir.facilityMgmt.control': '<fmt:message key="aimir.facilityMgmt.control"/>',
		'aimir.facilityMgmt.controller': '<fmt:message key="aimir.facilityMgmt.controller"/>',
		'aimir.changehistory': '<fmt:message key="aimir.changehistory"/>',
		'aimir.beforeChange': '<fmt:message key="aimir.beforeChange"/>',
		'aimir.state': '<fmt:message key="aimir.state"/>',
		'aimir.facilityMgmt.usagechart': '<fmt:message key="aimir.facilityMgmt.usagechart"/>',
		'aimir.date.yesterday': '<fmt:message key="aimir.date.yesterday"/>',
		'aimir.usage': '<fmt:message key="aimir.usage"/>',
		'aimir.today': '<fmt:message key="aimir.today"/>',
		'aimir.date.lastweek': '<fmt:message key="aimir.date.lastweek"/>',
		'aimir.date.thisweek': '<fmt:message key="aimir.date.thisweek"/>',
		'aimir.facilityMgmt.beforeMonth': '<fmt:message key="aimir.facilityMgmt.beforeMonth"/>',
		'aimir.thismonth': '<fmt:message key="aimir.thismonth"/>',
		'aimir.lastyear': '<fmt:message key="aimir.lastyear"/>',
		'aimir.year1': '<fmt:message key="aimir.year1"/>',
		'aimir.facilityMgmt.dailyUsage': '<fmt:message key="aimir.facilityMgmt.dailyUsage"/>',
		'aimir.facilityMgmt.weeklyUsage': '<fmt:message key="aimir.facilityMgmt.weeklyUsage"/>',		
		'aimir.facilityMgmt.monthlyUsage': '<fmt:message key="aimir.facilityMgmt.monthlyUsage"/>',
		'aimir.facilityMgmt.yearlyUsage': '<fmt:message key="aimir.facilityMgmt.yearlyUsage"/>',
		'aimir.energymeter':  '<fmt:message key="aimir.energymeter"/>',
		'aimir.gas': '<fmt:message key="aimir.gas"/>',
		'aimir.water': '<fmt:message key="aimir.water"/>',
		'aimir.heatmeter': '<fmt:message key="aimir.heatmeter"/>',
		'aimir.locationUsage.lastTerm': '<fmt:message key="aimir.locationUsage.lastTerm"/>',
		'aimir.locationUsage.now': '<fmt:message key="aimir.locationUsage.now"/>'
	}
};