package com.oracle.xmlns.ssys.nurieventsproxy.nurieventsproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-07-21T00:00:12.853+09:00
 * Generated source version: 3.1.5
 *
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/SSYS/NuriEventsProxy/NuriEventsProxy", name = "execute_ptt")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ExecutePtt {

    @WebMethod(action = "execute")
    @WebResult(name = "dateTime", targetNamespace = "http://xmlns.oracle.com/SSYS/NuriEventsProxy/NuriEventsProxy", partName = "response")
    public javax.xml.datatype.XMLGregorianCalendar execute(
        @WebParam(partName = "request", name = "request", targetNamespace = "http://iec.ch/TC57/2011/EndDeviceEventsMessage")
        ch.iec.tc57._2011.enddeviceeventsmessage.EndDeviceEventsEventMessageType request
    );
}