package com.oracle.xmlns.ssys.nurieventsproxy.nurieventsproxy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.1.5
 * 2016-07-21T00:00:12.896+09:00
 * Generated source version: 3.1.5
 *
 */
@WebServiceClient(name = "execute_bindQSService",
                  wsdlLocation = "file:NuriEventsProxy.wsdl",
                  targetNamespace = "http://xmlns.oracle.com/SSYS/NuriEventsProxy/NuriEventsProxy")
public class ExecuteBindQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/SSYS/NuriEventsProxy/NuriEventsProxy", "execute_bindQSService");
    public final static QName ExecuteBindQSPort = new QName("http://xmlns.oracle.com/SSYS/NuriEventsProxy/NuriEventsProxy", "execute_bindQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:NuriEventsProxy.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ExecuteBindQSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:NuriEventsProxy.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ExecuteBindQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ExecuteBindQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExecuteBindQSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ExecuteBindQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ExecuteBindQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ExecuteBindQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_bindQSPort")
    public ExecutePtt getExecuteBindQSPort() {
        return super.getPort(ExecuteBindQSPort, ExecutePtt.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExecutePtt
     */
    @WebEndpoint(name = "execute_bindQSPort")
    public ExecutePtt getExecuteBindQSPort(WebServiceFeature... features) {
        return super.getPort(ExecuteBindQSPort, ExecutePtt.class, features);
    }

}