package com.oracle.xmlns.ssys.nurieventsproxy.nurieventsproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-08-31T16:21:32.733+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/SSYS/NuriEventsProxy/NuriEventsProxy", name = "NuriEvents")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NuriEvents {

    @WebMethod(operationName = "NuriEvents_bulk", action = "execute")
    @WebResult(name = "dateTime", targetNamespace = "http://xmlns.oracle.com/SSYS/NuriEventsProxy/NuriEventsProxy", partName = "part1")
    public javax.xml.datatype.XMLGregorianCalendar nuriEventsBulk(
        @WebParam(partName = "part1", name = "Events", targetNamespace = "http://iec.ch/TC57/2011/EndDeviceEventsMessage")
        ch.iec.tc57._2011.enddeviceeventsmessage.EndDeviceEventsEventMessageType request
    );
}
