var firmWareAddInnerHTML = "";
    firmWareAddInnerHTML += ""
    +"<form id=\"form_input\" name=\"form_input\" method=\"post\" enctype=\"multipart/form-data\">  "
    +"  <input type=\"hidden\" name=\"binaryFileName\" id=\"binaryFileName\" value=\"\">               "
    +"  <input type=\"hidden\" name=\"hwVersion\" id=\"hwVersion\" value=\"\">               "
    +"  <input type=\"hidden\" name=\"fwVersion\" id=\"fwVersion\" value=\"\">               "
    +"  <input type=\"hidden\" name=\"arm\" id=\"arm\" value=\"0\">         "
    +"  <input type=\"hidden\" name=\"equipKind\" id=\"equipKind\" >  "
    +"  <input type=\"hidden\" name=\"equipModel\" id=\"equipModel\" >             "
    +"  <input type=\"hidden\" id=\"equipVendor\" >     		"
    +"  <input type=\"hidden\" id=\"supplier\" >     			"    
    +" <div class=\"mcudiv\">                                                                                                                          "
    +" 	<p class=\"title\">◈ Add E/W</p>                                                                                                               "
    +"     <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" class=\"mcu\">                                                                    "
    +"         <colgroup>                                                                                                                              "
    +"         <col width=\"140\"/>                                                                                                                    "
    +"         <col width=\"\"/>                                                                                                                       "
    +"         <col width=\"140\"/>                                                                                                                    "
    +"         <col>                                                                                                                                   "
    +"         </colgroup>                                                                                                                             "
    +"         <tr>                                                                                                                                    "
    +"             <th colspan=\"4\">Add F/W</th>                                                                                                      "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th>MCU Type</th>                                                                                                                   "
    +"             <td><span><input type=text name=\"equipType\" id=\"equipType\" align=\"absmiddle\" /></td>                                                                                                                  "
    +"             <th>&nbsp;</th>                                                                                                                     "
    +"             <td>&nbsp;</td>                                                                                                                     "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th>H/W Version</th>                                                                                                                "
    +"             <td>                                                                                                                                "
    +"                 <div id=\"hwVselectDIV\"><span><select name=\"select\" id=\"hwVselect\" onchange=\"javascript:setVersion();\" >                                                                                "
    +"                        <option>Etc</option>                                                                                                     "
    +"                        </select>                                                                                                                "
    +"                 </span></div><span><input type=\"text\" name=\"textfield2\" id=\"hwVersionETC\" align=\"absmiddle\" /></span>                        "
    +"             </td>                                                                                                                               "
    +"             <th>&nbsp;</th>                                                                                                                     "
    +"             <td></td>                                          																				   "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th>F/W Version</th>                                                                                                                "
    +"             <td class=\"space\">                                          "
    +"                <div id=\"fwVselectDIV\"><span><select name=\"select\" id=\"fwVselect\"  onchange=\"javascript:setVersion();\" >                                        "
    +"                      <option>Etc</option></select>                                      "
    +"                </span></div><span><input type=\"text\" name=\"textfield4\" id=\"fwVersionETC\" align=\"absmiddle\" /></span>                                       "
    +"             </td>                                     																						   "
    +"             <th>F/W Revision</th>                                                                                                                  "
    +"             <td class=\"space\"><input type=\"text\" name=\"build\" id=\"build\" align=\"absmiddle\" /></td>                                          "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th>Release Date</th>                                                                                                               "
    +"             <td class=\"space\">                                                                                                                                "
    +"                 <span><input name=\"textfield6\" type=\"text\" id=\"releasedDateYear\"  maxlength=\"4\" size=\"10\" align=\"absmiddle\" />년</span>                   "
    +"                 <span><input name=\"textfield7\" type=\"text\" id=\"releasedDateMonth\" maxlength=\"2\" size=\"10\" align=\"absmiddle\" />월</span>                                 "
    +"                 <span><input name=\"textfield8\" type=\"text\" id=\"releasedDateDay\"   maxlength=\"2\" size=\"10\" align=\"absmiddle\" />일</span>                                 "
    +"              </td>                                                                                                                              "
    +"             <th></th>                                                                                                                   "
    +"             <td></td>                                                                                                                "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th>Constraints<br />H/W(F/W Revision)</th>                                                                                            "
    +"             <td colspan=\"3\">                                                                                                                  "
    +"                 <input type=\"text\" name=\"textfield9\" id=\"constraintsHwFwVersion\" size=\"100\"/>                                                       "
    +"                 <a href=\"javascript:setConstraints();\"> <p class=\"title\">set<p> </a>														   "
    +"             </td>                                                                                                                               "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th> * Binary File</th>                                                                                                             "
    +"             <td colspan=\"3\"><input type=\"file\" id=\"newfile\" name=\"newfile\"  style=\"font-size: 9pt; display: block;\"/><em class=\"btn_grn_small\"><input type=\"submit\"  name=\"file_submit\" id=\"file_submit\" value=\"파일등록\" class=\"button\" /></em> </td>                                                                                                              "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th colspan=\"4\">Board</th>                                                                                                        "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th>Title</th>                                                                                                                      "
    +"             <td colspan=\"3\"><input type=\"text\" name=\"textfield9\" id=\"boardTitle\" align=\"absmiddle\"  style=\"width:90%\"/></td>        "
    +"         </tr>                                                                                                                                   "
    +"         <tr>                                                                                                                                    "
    +"             <th>Content</th>                                                                                                                    "
    +"             <td colspan=\"3\" class=\"space\"><textarea name=\"textarea\" id=\"boardContent\" rows=\"5\" style=\"width:95%\"></textarea></td>       "
    +"         </tr>                                                                                                                                   "
    +"     </table>                                                                                                                                    "
    +"     <table width=\"100%\" cellspacing=\"0\" cellpadding=\"0\" class=\"mcu\">                                                                    "
    +"     <colgroup>                                                                                                                                  "
    +"     <col width=\"10%\"/>                                                                                                                        "
    +"     <col width=\"%\"/>                                                                                                                          "
    +"     <col>                                                                                                                                       "
    +"     </colgroup>                                                                                                                                 "
    +"     <tr>                                                                                                                                        "
    +"         <td style=\"cursor: pointer\" onclick=\"javascript:addFWsubmit();\">&nbsp add</td>                                                                                                                      "
    +"         <td style=\"cursor: pointer\" >cancel</td>                                                                                                                         "
    +"     </tr>                                                                                                                                       "
    +"     </table>                                                                                                                                    "
    +" </div>                                                                                                                                          "
    +"                                   																									           " 
    +"<div id=\"tooltiplayer\" class=\"tooltiplayer\">																								   "
    +"<div class=\"tooltiptitle\">																								                       "
    +"    <span id=\"title\"> </span>																								                   "
    +"</div>																								                                           "
    +"<div class=\"tooltipcontent\">																								                   "
    +"    <span id=\"content\"></span>																								                   "
    +"</div>																								                                           "
    +"</div>    																								                                       "
   
    +"<script> $(document).ready(function(){                                              "
    +"  $(\"#form_input\").ajaxForm({                                                     "
    +"            success:function(responseText, statusText, xhr, $saveForm){                 "
    +"                       "
    +"                if($.trim(statusText) == \"success\"){                              "
    +"                    alert(\"파일을 성공적으로 등록하였습니다.\");    setbinfileName(responseText);            "
   // +"                    //$(\"#list1\").trigger(\"reloadGrid\");                          "
    +"                }else{                                                              "
    +"                    alert(\"FileUpload Error..\");                                  "
    +"                }                                                                   "
    +"            }                                                                       "
    +"        });                                                                         "
    +"        $(\"#form_input\").submit(function(){return false;});                       "
    +"	$(\"#file_submit\").click(function(){ 											  "
    +"	          setVersion();															  "
    +"		     if($('#build').val() == null || $('#build').val() == \"\"){ 				"
    +"	    	 	alert(\"build 값을 먼저 입력하세요\"); 										"
    +"	    	 	$('#build').focus(); 													"
    +"	    	 	return false; 															"
    +"	     	 } 																			"
    +"           var imgno = \"0\";                                                                                                   "
    +"           var nono = \"0\";                                                                                                    "
    +"           $('#newfile').each(function() {                                                                                      "
    +"            var imgval = $(this).val();                                                                                         "
    +"            imgno++;                                                                                                            "
    +"                                                                                                                                "
    +"              if (!imgval.toLowerCase().match(/.(tar.gz)$/i)) {                                                                 "
    +"             alert(\"tar.gz 파일이 아닙니다.\");                                                                                   "
    +"             nono = \"1\";                                                                                                      "
    +"             return false;                                                                                                      "
    +"            }                                                                                                                   "
    +"           });                                                                                                                  "
    +"           if (nono == 1) {                                                                                                     "
    +"            return false;                                                                                                       "
    +"           }                                                                                                                    "
    +"           if(confirm(\"파일전송 하시겠습니까?\")){                                                                                 "
    +"               $(\"#div_input\").ajaxError(function(evt,xhr,opt){                                                               "
    +"                   alert(\"오류가 발생하였습니다.\");                                                                               "
    +"                   $('#div_input').unblock();                                                                                   "
    +"               });                                                                                                              "
    +"               $(\"<input type='hidden' name='seprator' id='seprator' value='admin_upt'>\").appendTo(\"#form_input\");          "
    +"               $(\"#form_input\").attr(\"action\",\"file_upload.do\");    				                                        "
    +"               $(\"#form_input\").submit();                                                                                     "
    +"           }                                                                                                                    "
    +"});"
    +"}); </script> 																												" 
    +"<table>																														"
    +"<td class=\"txtRight\"></td>																									"
    +"  <td>																														"
    +"    <input type=\"hidden\" name=\"oldFile\" id=\"oldFile\" >																	"
    +"    <span id=\"file\" style=\"display: none\"><a href=\"#\" id=\"fname\"></a></span>											"
    +"    <div id=\"filearea\">																										"
    +"    </div>																													"
    +"         <input type=\"hidden\" id=\"filenamez\" name=\"filenamez\" />														"
    +"</table> </form>																											"
    ;
 
    var firmdetailInnerHTML = "";
    firmdetailInnerHTML += ""    
    +"   <div class=\"mcudiv\">                                                                                                                                                                                      "
    +"      <table  border=\"0\" cellpadding=\"0\" cellspacing=\"0\"  class=\"mcu\">                                                                                                                                 "
      +"     <colgroup>                                                                                                                                                                                                "
      +"     <col width=\"10%\" />                                                                                                                                                                                     "
      +"     <col width=\"\" />                                                                                                                                                                                        "
      +"     </colgroup>                                                                                                                                                                                               "
      +"     <tr>                                                                                                                                                                                                      "
      +"     <th>FW/HW</th>                                                                                                                                                                                            "
	  +"		 <th>1</th> " 																																												
      +"     <th>Unknown</th>                                                                                                                                                                                          "
      +"     </tr>                                                                                                                                                                                                     "
      +"     <tr>                                                                                                                                                                                                      "
      +"     <th>1</th>                                                                                                                                                                                    "
      +"     <td>                                                                                                                                                                                                      "
      +"     <div class=\"scroll\" \">                                                                                                                                                                                    "
      +"     </div>                                                                                                                                                                                                    "
      +"     </td>                                                                                                                                                                                                     "
      +"     <td>                                                                                                                                                                                                      "
      +"     <div class=\"scroll\" \">                                                                                                                                                                                    "
      +"     </div>                                                                                                                                                                                                    "
      +"     </td>                                                                                                                                                                                                     "
      +"     </tr>                                                                                                                                                                                                     "								       
	  +"     <tr>                                                                                                                                                                                                      "
	  +"     <th>unknown</th>                                                                                                                                                                                    "
	  +"     <td><div class=\"scroll\"></div></td> "		
	  +"     <td><div class=\"scroll\"></div></td> "
	  +"     </table>                                                                                                                                                                                                  "
      +" </div>";      
    
    var addDivInnerHTML = "";
    addDivInnerHTML += "" 
    	+" <em class=\"btn\"><a onclick=\"javascript:addFW('0');\" >Add F/W</a></em>"
    	+" <em class=\"btn\"><a onclick=\"javascript:distributeFW();\">Distributde</a></em>";
    
    var searchDivInnerHTML = "";
        searchDivInnerHTML += "" 
       
        	+"      <div class=\"search\">																																									                                           "
        	+"          <table width=\"100%\" border=\"0\" cellspacing=\"0\" class=\"basic\">                                                                          "
        	+"          <colgroup>                                                                                                                                     "
        	+"          <col width=\"90px\" />                                                                                                                         "
        	+"          <col width=\"120px\" />                                                                                                                        "
        	+"          <col width=\"90px\" />                                                                                                                         "
        	+"          <col width=\"120px\" />                                                                                                                        "
        	+"          <col width=\"120px\" />                                                                                                                        "
        	+"          <col width=\"\" />                                                                                                                             "
        	+"          </colgroup>                                                                                                                                    "
        	+"          <tr>                                                                                                                                           "
        	+"          <th width=\"10%\">Equip Kind:</th>                                                                                                             "
        	+"          <td width=\"20%\">                                                                                                                             "
        	+"              <select name=\"select\" id=\"select\" >                                                                                                    "
        	+"              <option selected=\"selected\">Etc</option>                                                                                                 "
        	+"              </select>                                                                                                                                  "
        	+"          </td>                                                                                                                                          "
        	+"          <th width=\"10%\">Equip Type:</th>                                                                                                             "
        	+"          <td width=\"20%\">                                                                                                                             "
        	+"              <select name=\"select3\" id=\"select3\" >                                                                                                  "
        	+"              <option selected=\"selected\">Etc</option>                                                                                                 "
        	+"              </select>                                                                                                                                  "
        	+"          </td>                                                                                                                                          "
        	+"          <th width=\"10%\">Location: </th>                                                                                                              "
        	+"          <td colspan=\"2\"><input type=\"text\" name=\"textfield3\" id=\"textfield3\"  align=\"absmiddle\"/></td>                                       "
        	+"          </tr>                                                                                                                                          "
        	+"          <tr>                                                                                                                                           "
        	+"          <th>Vendor</th>                                                                                                                                "
        	+"          <td>                                                                                                                                           "
        	+"              <select name=\"select2\" id=\"select2\" >                                                                                                  "
        	+"              <option selected=\"selected\">Etc</option>                                                                                                 "
        	+"              </select>                                                                                                                                  "
        	+"          </td>                                                                                                                                          "
        	+"          <th>Model:</th>                                                                                                                                "
        	+"          <td>                                                                                                                                           "
        	+"              <select name=\"select4\" id=\"select4\" >                                                                                                  "
        	+"              <option selected=\"selected\">Etc</option>                                                                                                 "
        	+"              </select>                                                                                                                                  "
        	+"          </td>                                                                                                                                          "
        	+"          <th>State: </th>                                                                                                                               "
        	+"          <td colspan=\"2\">                                                                                                                             "
        	+"              <select name=\"select5\" id=\"select5\" >                                                                                                  "
        	+"              <option selected=\"selected\">Etc</option>                                                                                                 "
        	+"              </select>                                                                                                                                  "
        	+"          </td>                                                                                                                                          "
        	+"          </tr>                                                                                                                                          "
        	+"          <tr>                                                                                                                                           "
        	+"          <th>Trigger ID:</th>                                                                                                                           "
        	+"          <td><input type=\"text\" name=\"textfield2\" id=\"textfield2\"  align=\"absmiddle\"/></td>                                                     "
        	+"          <th>Equip. ID:</th>                                                                                                                            "
        	+"          <td><input type=\"text\" name=\"textfield\" id=\"textfield\"  align=\"absmiddle\"/></td>                                                       "
        	+"          <th>Issue Date:</th>                                                                                                                           "
        	+"          <td>                                                                                                                                           "
        	+"          	<input name=\"textfield6\" type=\"text\" id=\"textfield6\" size=\"10\" align=\"absmiddle\" /><span class=\"ico_calendar\"></span> ~          "
        	+"          	<input name=\"textfield4\" type=\"text\" id=\"textfield4\" size=\"10\" align=\"absmiddle\" /><span class=\"ico_calendar\"></span>            "
        	+"          </td>                                                                                                                                          "
        	+"          <td><em class=\"btn_grn_small\"><input type=\"submit\" name=\"button\" id=\"button\" value=\"Search\" class=\"button\" /></em></td>            "
        	+"          </tr>                                                                                                                                          "
        	+"          </table>                                                                                                                                       "
        	+" 	</div>																																				"
        	+"        <div class=\"mgn_rbl20\">                                                                " 
        	+"            <div class=\"mcudiv\">                                                               "
        	+"                <table  border=\"0\" cellpadding=\"0\" cellspacing=\"0\"  class=\"mcu\">         "
        	+"                <colgroup>                                                                       "
        	+"                <col width=\"\" />                                                               "
        	+"                <col width=\"\" />                                                               "
        	+"                <col width=\"\" />                                                               "
        	+"                <col width=\"\" />                                                               "
        	+"                </colgroup>                                                                      "
        	+"                <tr>                                                                             "
        	+"                <th>No</th>                                                                      "
        	+"                <th>Trigger ID</th>                                                              "
        	+"                <th>Equip Kind</th>                                                              "
        	+"                <th>Equip Type</th>                                                              "
        	+"                <th colspan=\"3\">Source Version</th>                                            "
        	+"                <th colspan=\"3\">Target Version</th>                                            "
        	+"                <th  colspan=\"5\">State</th>                                                    "
        	+"               </tr>                                                                             "
        	+"                <tr>                                                                             "
        	+"                <th class=\"subtit\">3.1</th>                                                    "
        	+"                <th class=\"subtit\">111</th>                                                    "
        	+"                <th class=\"subtit\">2222</th>                                                   "
        	+"                <th class=\"subtit\">333</th>                                                    "
        	+"                <th class=\"subtit\">H/W Version</th>                                            "
        	+"                <th class=\"subtit\">F/W Version</th>                                            "
        	+"                <th class=\"subtit\">F/W Build</th>                                              "
        	+"                <th class=\"subtit\">H/W Version</th>                                            "
        	+"                <th class=\"subtit\">F/W Version</th>                                            "
        	+"                <th class=\"subtit\">F/W Revision</th>                                              "
        	+"                <th class=\"subtit\">Total</th>                                                  "
        	+"                <th class=\"subtit\">Success</th>                                                "
        	+"                <th class=\"subtit\">Executinig</th>                                             "
        	+"                <th class=\"subtit\">Cancel</th>                                                 "
        	+"                <th class=\"subtit\">Error</th>                                                  "
        	+"                </tr>                                                                            "
        	+"                <tr>                                                                             "
        	+"                <td>1111</td>                                                                    "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                <td></td>                                                                        "
        	+"                </tr>                                                                            "
        	+"                </table>                                                                         "
        	+"          </div>                                                                                 "
        	+"        </div>                                                                                   ";

        	
    
    
