USE [aimirdb]
GO
BEGIN TRANSACTION
CREATE PARTITION FUNCTION [day_em_part_func](varchar(8)) AS RANGE RIGHT FOR VALUES (N'20140101', N'20140401', N'20140701', N'20141001', N'20150101', N'20150401', N'20150701', N'20151001')


CREATE PARTITION SCHEME [day_em_part_scheme] AS PARTITION [day_em_part_func] TO ([PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY], [PRIMARY])


ALTER TABLE [dbo].[DAY_EM] DROP CONSTRAINT [PK__DAY_EM__862D7D6F3A4CA8FD]


ALTER TABLE [dbo].[DAY_EM] ADD PRIMARY KEY CLUSTERED 
(
	[channel] ASC,
	[yyyymmdd] ASC,
	[dst] ASC,
	[mdev_id] ASC,
	[mdev_type] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [day_em_part_scheme]([yyyymmdd])




COMMIT TRANSACTION


