pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["gadget_descr_hems_info006.htm","제품 관리","제품 관리 Top AIMIR v3.0 Manual Enter topic text here. ",""],
["gadget_hems_demandresponsemgmt.htm","수요반응 관리","수요반응 관리 Top Previous AIMIR v3.0 Manual Enter topic text here. ",""],
["gadget_hems_electconsumption.htm","電気使用量照会","電気使用量照会 Top Previous Next AIMIR v3.0 Manual 전기 사용량 조회는 각 가정의 전기 사용량을 기간별, 기기별로 조회할 수 있는 기능을 제공합니다. 미니가젯 미니 가젯은 [요약] , [기간별 조회] , [기기별 조회] 3개의 탭으로 ...",""],
["gadget_hems_electprepaymentcustomer.htm","電気前払い管理","電気前払い管理 Top Previous Next AIMIR v3.0 Manual 요금제도가 선불인 전기 고객에 대해서, 충전 이력 조회및 잔액 통보 설정 기능을 제공합니다. 미니가젯 미니 가젯은 [충전이력] , [설정], [요금단가] 3개의 탭으로 구성되어 있습니...",""],
["gadget_hems_electsavingsgoal.htm","電気エネルギー削減目標","電気エネルギー削減目標 Top Previous Next AIMIR v3.0 Manual 각 가정의 전기 에너지 절감 목표 설정및 실적 관리 기능을 제공합니다. 전기 에너지 절감 목표는 월단위로 설정가능하며, 절감 목표 실적은 통보기능을 통해서 고객이 설정한 주기로...",""],
["gadget_hems_gasconsumption.htm","ガス使用量照会","ガス使用量照会 Top Previous Next AIMIR v3.0 Manual 가스 사용량 조회는 각 가정의 가스 사용량을 기간별로 조회할 수 있는 기능을 제공합니다. 미니가젯 미니 가젯은 [요약] , [기간별 조회] 2개의 탭으로 구성되어있습니다. 요약 : 당...",""],
["gadget_hems_gasprepaymentcustomer.htm","ガス前払い管理","ガス前払い管理 Top Previous Next AIMIR v3.0 Manual 요금제도가 선불인 가스 고객에 대해서, 충전 이력 조회및 잔액 통보 설정 기능을 제공합니다. 미니가젯 미니 가젯은 [충전이력] , [설정], [요금단가] 3개의 탭으로 구성되어 있습니...",""],
["gadget_hems_gassavingsgoal.htm","ガスエネルギー削減目標","ガスエネルギー削減目標 Top Previous Next AIMIR v3.0 Manual 각 가정의 가스 에너지 절감 목표 설정및 실적 관리 기능을 제공합니다. 가스 에너지 절감 목표는 월단위로 설정가능하며, 절감 실적은 통보기능을 통해서 고객이 설정한 주기로 통보...",""],
["gadget_hems_homedevicemgmt.htm","機器管理","機器管理 Top Previous Next AIMIR v3.0 Manual 댁내에서 사용하는 가전정보를 관리하는 기능을 제공합니다. 가전의 직접 부하제어및 수요반응 참여를 위해서는 본 기능을 통해 먼저 가전의 정보를 등록해야합니다.(자세한 사항은 수용반응 관리 참...",""],
["gadget_hems_myreport.htm","My Report","My Report Top Previous Next AIMIR v3.0 Manual My Report는 고객의 전기,가스,수도등 모든 에너지원을 통합 관리하는 메인화면입니다. 일/월 단위 에너지 사용정보를 확인할 수 있습니다. 각 에너지 원 별 (전기, 가스,수도...",""],
["gadget_hems_waterconsumption.htm","水道使用量照会","水道使用量照会 Top Previous Next AIMIR v3.0 Manual 수도 사용량 조회는 각 가정의 수도 사용량을 기간별로 조회할 수 있는 기능을 제공한다. 미니가젯 미니 가젯은 [요약] , [기간별 조회] 2개의 탭으로 구성되 어있다. 요약 : 당일 ...",""],
["gadget_hems_waterprepaymentcustomer.htm","水道前払い管理","水道前払い管理 Top Previous Next AIMIR v3.0 Manual 요금제도가 선불인 수도 고객에 대해서, 충전 이력 조회및 잔액 통보 설정 기능을 제공합니다. 미니가젯 미니 가젯은 [충전이력] , [설정], [요금단가] 3개의 탭으로 구성되어 있습니...",""],
["gadget_hems_watersavingsgoal.htm","水道エネルギー削減目標","水道エネルギー削減目標 Top Previous Next AIMIR v3.0 Manual 각 가정의 가스 에너지 절감 목표 설정및 실적 관리 기능을 제공합니다. 가스 에너지 절감 목표는 월단위로 설정가능하며, 절감 실적은 통보기능을 통해서 고객이 설정한 주기로 통보...",""],
["hems_overview.htm","Overview","Overview Top AIMIR v3.0 Manual Home Energy Management System(이하, HEMS)는 가정의 에너지 절감을 실현하기 위한..... 화면 구성 HEMS는 크게 3개의 패널로 구성되어 있다. 패널 명 설명 Header Pa...",""],
["hems___.htm","HEMS 소개","HEMS 소개 Top Previous Next AIMIR v3.0 Manual Home Energy Management System(以下, HEMS)はヌリテレコム AiMiR AMI Systemの一つとして家庭エネルギ－削減を実現するための顧客ポ－タルサイトです。 画面構...",""],
["introduction.htm","소개","소개 Top AIMIR v3.0 Manual Enter topic text here. ",""],
["new_topic.htm","New topic","Welcome to HEMS Manual Top Next AIMIR v3.0 Manual AIMIR&#174;はヌリテレコムの登録商標です。 使用者公示 이 문서에 포함되어 있는 어떠한 정보도 기능 향상 등을 이유로 사전 통보 없이 변경 및 수정되어질 수 있으며, 누리텔레콤은...",""],
["new_topic2.htm","기능 설명","기능 설명 Top AIMIR v3.0 Manual Enter topic text here. ",""]];
