CREATE TABLE AIMIR.DUMMY_LPEM_TO_DAYEM
(
MDEV_ID VARCHAR2(20) NOT NULL,
YYYYMMDDHHMISS VARCHAR2(14) NOT NULL,
CHANNEL VARCHAR2(3) NOT NULL,
MDEV_TYPE VARCHAR2(20) NOT NULL,
DST NUMBER(38) NOT NULL,
WRITEDATE VARCHAR2(14)
);
CREATE INDEX AIMIR.IDX_DUMMY_LPEM_TO_DAYEM ON AIMIR.DUMMY_LPEM_TO_DAYEM(MDEV_ID, YYYYMMDDHHMISS, CHANNEL, MDEV_TYPE, DST);
