BEGIN 
SYS.DBMS_SCHEDULER.CREATE_JOB(
JOB_NAME => 'DAY_EM_SCHEDULER'
, JOB_TYPE => 'PLSQL_BLOCK'
, JOB_ACTION => 'BEGIN AIMIR.BATCH_DAY_EM; DBMS_RESULT_CACHE.FLUSH; END;'
, START_DATE => SYSTIMESTAMP
, REPEAT_INTERVAL => 'FREQ=SECONDLY; INTERVAL=1'
, COMMENTS => 'DAY_EM_BATCH_JOB'
);
END;

BEGIN
SYS.DBMS_SCHEDULER.ENABLE('DAY_EM_SCHEDULER');
END;
