DROP TABLE AIMIR.MONTH_EM;
CREATE TABLE AIMIR.MONTH_EM
(
MDEV_ID VARCHAR2(20) NOT NULL,
YYYYMM VARCHAR2(6) NOT NULL,
CHANNEL VARCHAR2(3) NOT NULL,
MDEV_TYPE VARCHAR2(20) NOT NULL,
DST NUMBER(2) NOT NULL,
DD VARCHAR2(2) NOT NULL,
METER_ID NUMBER(10),
METERINGTYPE NUMBER(2),
MDEV_ID_LAST NUMBER(1),
MODEM_ID NUMBER(10),
DEVICE_ID VARCHAR2(20),
DEVICE_TYPE VARCHAR2(15),
C_VALUE NUMBER(10),
BASEVALUE NUMBER(19, 4),
VALUE NUMBER(19, 4),
WRITEDATE VARCHAR2(14),
SUPPLIER_ID NUMBER(10),
CH_METHOD VARCHAR2(255),
CONTRACT_ID NUMBER(10),
ENDDEVICE_ID NUMBER(10)
);
CREATE INDEX AIMIR.PK_MONTH_EM ON AIMIR.MONTH_EM (MDEV_ID, YYYYMM, CHANNEL, MDEV_TYPE, DST, DD);
ALTER TABLE AIMIR.MONTH_EM ADD CONSTRAINT PK_MONTH_EM PRIMARY KEY (MDEV_ID, YYYYMM, CHANNEL, MDEV_TYPE, DST, DD);
