CREATE OR REPLACE TRIGGER AIMIR.TRI_MONTH_EM   
AFTER INSERT OR UPDATE ON AIMIR.DAY_EM  
FOR EACH ROW  
  
BEGIN   
  
MERGE INTO AIMIR.DAYEM_TO_MONTHEM USING DUAL   
  ON (MDEV_ID = :NEW.MDEV_ID AND YYYYMMDD = :NEW.YYYYMMDD AND CHANNEL = :NEW.CHANNEL AND MDEV_TYPE = :NEW.MDEV_TYPE AND DST = :NEW.DST AND HH = :NEW.HH)  
WHEN MATCHED THEN UPDATE SET WRITEDATE = :NEW.WRITEDATE
WHEN NOT MATCHED THEN INSERT VALUES (:NEW.MDEV_ID, :NEW.YYYYMMDD, :NEW.CHANNEL, :NEW.MDEV_TYPE, :NEW.DST, :NEW.HH, :NEW.WRITEDATE);  
                                
END;
