--(ORA-01722)발생시 Type일치 여부 및 DAY_WM과 Merge문에서 입력하는 Column 순서가 일치하는지 확인할 것.
create or replace PROCEDURE       BATCH_DAY_WM IS        
       
V_SQL VARCHAR2(100); 
       
BEGIN        
DBMS_OUTPUT.ENABLE;      
      
V_SQL := 'TRUNCATE TABLE AIMIR.DUMMY_LPWM_TO_DAYWM';        
EXECUTE IMMEDIATE V_SQL;        
INSERT INTO AIMIR.DUMMY_LPWM_TO_DAYWM SELECT /*+ INDEX(LPWM_TO_DAYWM IDX_LPWM_TO_DAYWM) */ MDEV_ID, YYYYMMDDHHMISS, CHANNEL, MDEV_TYPE, DST, WRITEDATE FROM AIMIR.LPWM_TO_DAYWM WHERE ROWNUM <= 100000;      
      
V_SQL := 'ANALYZE TABLE AIMIR.DUMMY_LPWM_TO_DAYWM ESTIMATE STATISTICS';      
EXECUTE IMMEDIATE V_SQL;   
           
MERGE INTO AIMIR.DAY_WM T_TABLE USING       
 (SELECT A.MDEV_ID, A.YYYYMMDD, A.CHANNEL, A.MDEV_TYPE, A.DST, A.HH, METER.ID METER_ID, A.METERINGTYPE, SUBSTR(A.MDEV_ID, LENGTH(A.MDEV_ID), 1) MDEV_ID_LAST, MODEM.ID MODEM_ID,       
  A.DEVICE_ID, A.DEVICE_TYPE, SUM(A.INTERVAL_YN) C_VALUE, M_BASEVALUE.BASEVALUE BASEVALUE, CASE WHEN CH_METHOD = 'MAX' THEN MAX(VALUE) WHEN CH_METHOD = 'SUM' THEN SUM(VALUE) WHEN CH_METHOD = 'AVG' THEN AVG(VALUE) END VALUE,       
  MIN(A.WRITEDATE) WRITEDATE, SUPPLIER.ID SUPPLIER_ID, CH_METHOD, CONTRACT_VALUE.CONTRACT_ID CONTRACT_ID, ENDDEVICE.ID ENDDEVICE_ID       
  FROM (SELECT MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, CHANNEL, MDEV_TYPE, DST, SUBSTR(YYYYMMDDHHMISS, 9, 2) HH, DEVICE_ID, DEVICE_TYPE, WRITEDATE, METERINGTYPE, INTERVAL_YN, VALUE FROM
        (SELECT /*+ RESULT_CACHE */ A.MDEV_ID, A.YYYYMMDDHHMISS, A.CHANNEL, A.MDEV_TYPE, A.DST, A.DEVICE_ID, A.DEVICE_TYPE, A.WRITEDATE, A.METERINGTYPE, A.INTERVAL_YN, A.VALUE VALUE, A.CONTRACT_ID
          FROM AIMIR.LP_WM A JOIN (SELECT /*+ INDEX_FFS(DUMMY_LPWM_TO_DAYWM, IDX_DUMMY_LPWM_TO_DAYWM) */ MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, CHANNEL, MDEV_TYPE, DST FROM AIMIR.DUMMY_LPWM_TO_DAYWM GROUP BY MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8), CHANNEL, MDEV_TYPE, DST) B     
          ON A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS BETWEEN B.YYYYMMDD||'000000' AND B.YYYYMMDD||'235959' AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST) 
         WHERE INTERVAL_YN = 1) A        
        LEFT JOIN (SELECT A.MDEV_ID, SUBSTR(A.YYYYMMDDHHMISS, 1, 8) YYYYMMDD, A.CHANNEL, A.MDEV_TYPE, A.DST, A.VALUE BASEVALUE FROM
                   (SELECT /*+ RESULT_CACHE */ A.MDEV_ID, A.YYYYMMDDHHMISS, A.CHANNEL, A.MDEV_TYPE, A.DST, A.DEVICE_ID, A.DEVICE_TYPE, A.WRITEDATE, A.METERINGTYPE, A.INTERVAL_YN, A.VALUE VALUE, A.CONTRACT_ID
                    FROM AIMIR.LP_WM A JOIN (SELECT /*+ INDEX_FFS(DUMMY_LPWM_TO_DAYWM, IDX_DUMMY_LPWM_TO_DAYWM) */ MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, CHANNEL, MDEV_TYPE, DST FROM AIMIR.DUMMY_LPWM_TO_DAYWM GROUP BY MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8), CHANNEL, MDEV_TYPE, DST) B     
                    ON A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS BETWEEN B.YYYYMMDD||'000000' AND B.YYYYMMDD||'235959' AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST) A
                   JOIN
                   (SELECT MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, MIN(YYYYMMDDHHMISS) YYYYMMDDHHMISS, CHANNEL, MDEV_TYPE, DST FROM 
                    (SELECT /*+ RESULT_CACHE */ A.MDEV_ID, A.YYYYMMDDHHMISS, A.CHANNEL, A.MDEV_TYPE, A.DST, A.DEVICE_ID, A.DEVICE_TYPE, A.WRITEDATE, A.METERINGTYPE, A.INTERVAL_YN, A.VALUE VALUE, A.CONTRACT_ID
                     FROM AIMIR.LP_WM A JOIN (SELECT /*+ INDEX_FFS(DUMMY_LPWM_TO_DAYWM, IDX_DUMMY_LPWM_TO_DAYWM) */ MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, CHANNEL, MDEV_TYPE, DST FROM AIMIR.DUMMY_LPWM_TO_DAYWM GROUP BY MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8), CHANNEL, MDEV_TYPE, DST) B     
                     ON A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS BETWEEN B.YYYYMMDD||'000000' AND B.YYYYMMDD||'235959' AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST) 
                     GROUP BY MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8), CHANNEL, MDEV_TYPE, DST) B
                   ON A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS = B.YYYYMMDDHHMISS AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST) M_BASEVALUE        
        ON A.MDEV_ID = M_BASEVALUE.MDEV_ID AND A.YYYYMMDD = M_BASEVALUE.YYYYMMDD AND A.CHANNEL = M_BASEVALUE.CHANNEL AND A.MDEV_TYPE = M_BASEVALUE.MDEV_TYPE AND A.DST = M_BASEVALUE.DST       
        LEFT JOIN (SELECT A.MDEV_ID, SUBSTR(A.YYYYMMDDHHMISS, 1, 8) YYYYMMDD, A.CHANNEL, A.MDEV_TYPE, A.DST, A.CONTRACT_ID FROM 
                   (SELECT /*+ RESULT_CACHE */ A.MDEV_ID, A.YYYYMMDDHHMISS, A.CHANNEL, A.MDEV_TYPE, A.DST, A.DEVICE_ID, A.DEVICE_TYPE, A.WRITEDATE, A.METERINGTYPE, A.INTERVAL_YN, A.VALUE VALUE, A.CONTRACT_ID
                   FROM AIMIR.LP_WM A JOIN (SELECT /*+ INDEX_FFS(DUMMY_LPWM_TO_DAYWM, IDX_DUMMY_LPWM_TO_DAYWM) */ MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, CHANNEL, MDEV_TYPE, DST FROM AIMIR.DUMMY_LPWM_TO_DAYWM GROUP BY MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8), CHANNEL, MDEV_TYPE, DST) B     
                   ON A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS BETWEEN B.YYYYMMDD||'000000' AND B.YYYYMMDD||'235959' AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST) A
                  JOIN
                  (SELECT MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, MAX(YYYYMMDDHHMISS) YYYYMMDDHHMISS, CHANNEL, MDEV_TYPE, DST FROM
                   (SELECT /*+ RESULT_CACHE */ A.MDEV_ID, A.YYYYMMDDHHMISS, A.CHANNEL, A.MDEV_TYPE, A.DST, A.DEVICE_ID, A.DEVICE_TYPE, A.WRITEDATE, A.METERINGTYPE, A.INTERVAL_YN, A.VALUE VALUE, A.CONTRACT_ID
                   FROM AIMIR.LP_WM A JOIN (SELECT /*+ INDEX_FFS(DUMMY_LPWM_TO_DAYWM, IDX_DUMMY_LPWM_TO_DAYWM) */ MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8) YYYYMMDD, CHANNEL, MDEV_TYPE, DST FROM AIMIR.DUMMY_LPWM_TO_DAYWM GROUP BY MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8), CHANNEL, MDEV_TYPE, DST) B     
                   ON A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS BETWEEN B.YYYYMMDD||'000000' AND B.YYYYMMDD||'235959' AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST)
                   GROUP BY MDEV_ID, SUBSTR(YYYYMMDDHHMISS, 1, 8), CHANNEL, MDEV_TYPE, DST) B
                  ON A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS = B.YYYYMMDDHHMISS AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST) CONTRACT_VALUE       
        ON A.MDEV_ID = CONTRACT_VALUE.MDEV_ID AND A.YYYYMMDD = CONTRACT_VALUE.YYYYMMDD AND A.CHANNEL = CONTRACT_VALUE.CHANNEL AND A.MDEV_TYPE = CONTRACT_VALUE.MDEV_TYPE AND A.DST = CONTRACT_VALUE.DST       
        LEFT JOIN AIMIR.METER METER ON A.MDEV_ID = METER.MDS_ID        
        LEFT JOIN AIMIR.MODEM MODEM ON METER.MODEM_ID = MODEM.ID        
        LEFT JOIN AIMIR.ENDDEVICE ENDDEVICE ON METER.DEVICEMODEL_ID = ENDDEVICE.DEVICEMODEL_ID        
        LEFT JOIN AIMIR.SUPPLIER SUPPLIER ON METER.SUPPLIER_ID = SUPPLIER.ID        
        LEFT JOIN AIMIR.METERCONFIG METERCONFIG ON METER.DEVICEMODEL_ID = METERCONFIG.DEVICEMODEL_FK        
        LEFT JOIN (SELECT CHANNEL_CONFIG.METERCONFIG_ID METERCONFIG_ID, DISPLAY_CHANNEL.CH_METHOD CH_METHOD       
                   FROM AIMIR.CHANNEL_CONFIG CHANNEL_CONFIG JOIN AIMIR.DISPLAY_CHANNEL DISPLAY_CHANNEL ON CHANNEL_CONFIG.CHANNEL_ID = DISPLAY_CHANNEL.ID       
                   GROUP BY CHANNEL_CONFIG.METERCONFIG_ID, DISPLAY_CHANNEL.CH_METHOD) CHANNEL_CONFIG ON METERCONFIG.ID = CHANNEL_CONFIG.METERCONFIG_ID       
  GROUP BY A.MDEV_ID, A.YYYYMMDD, A.CHANNEL, A.MDEV_TYPE, A.DST, A.HH, METER.ID, A.METERINGTYPE, SUBSTR(A.MDEV_ID, LENGTH(A.MDEV_ID), 1), MODEM.ID, A.DEVICE_ID, A.DEVICE_TYPE, M_BASEVALUE.BASEVALUE, SUPPLIER.ID, CH_METHOD, CONTRACT_VALUE.CONTRACT_ID, ENDDEVICE.ID) S_TABLE       
ON (T_TABLE.MDEV_ID = S_TABLE.MDEV_ID AND T_TABLE.YYYYMMDD = S_TABLE.YYYYMMDD AND T_TABLE.CHANNEL = S_TABLE.CHANNEL AND T_TABLE.MDEV_TYPE = S_TABLE.MDEV_TYPE AND T_TABLE.DST = S_TABLE.DST AND T_TABLE.HH = S_TABLE.HH)          
WHEN MATCHED THEN UPDATE SET T_TABLE.METER_ID = S_TABLE.METER_ID, T_TABLE.METERINGTYPE = S_TABLE.METERINGTYPE, T_TABLE.MDEV_ID_LAST = S_TABLE.MDEV_ID_LAST, T_TABLE.MODEM_ID = S_TABLE.MODEM_ID, T_TABLE.DEVICE_ID = S_TABLE.DEVICE_ID,         
                             T_TABLE.DEVICE_TYPE = S_TABLE.DEVICE_TYPE, T_TABLE.C_VALUE = S_TABLE.C_VALUE, T_TABLE.BASEVALUE = S_TABLE.BASEVALUE, T_TABLE.VALUE = S_TABLE.VALUE, T_TABLE.WRITEDATE = S_TABLE.WRITEDATE, T_TABLE.SUPPLIER_ID = S_TABLE.SUPPLIER_ID, T_TABLE.CH_METHOD = S_TABLE.CH_METHOD, T_TABLE.CONTRACT_ID = S_TABLE.CONTRACT_ID, T_TABLE.ENDDEVICE_ID = S_TABLE.ENDDEVICE_ID         
WHEN NOT MATCHED THEN INSERT VALUES (S_TABLE.MDEV_ID, S_TABLE.YYYYMMDD, S_TABLE.CHANNEL, S_TABLE.MDEV_TYPE, S_TABLE.DST, S_TABLE.HH, S_TABLE.METER_ID, S_TABLE.METERINGTYPE, S_TABLE.MDEV_ID_LAST, S_TABLE.MODEM_ID, S_TABLE.DEVICE_ID, S_TABLE.DEVICE_TYPE, S_TABLE.C_VALUE, S_TABLE.BASEVALUE, S_TABLE.VALUE, S_TABLE.WRITEDATE, S_TABLE.SUPPLIER_ID, S_TABLE.CH_METHOD, S_TABLE.CONTRACT_ID, S_TABLE.ENDDEVICE_ID);        
       
DELETE FROM AIMIR.LPWM_TO_DAYWM A WHERE EXISTS         
(SELECT 1 FROM AIMIR.DUMMY_LPWM_TO_DAYWM B WHERE A.MDEV_ID = B.MDEV_ID AND A.YYYYMMDDHHMISS = B.YYYYMMDDHHMISS AND A.CHANNEL = B.CHANNEL AND A.MDEV_TYPE = B.MDEV_TYPE AND A.DST = B.DST AND A.WRITEDATE = B.WRITEDATE);         
  
EXCEPTION WHEN OTHERS THEN            
          DBMS_OUTPUT.PUT_LINE('ERR CODE : ' || TO_CHAR(SQLCODE));          
          DBMS_OUTPUT.PUT_LINE('ERR MESSAGE : ' || SQLERRM);        
                 
END;