--Tablespace는 사이트에 따라 변경될 수 있음.
--컬럼 추가 혹은 순서 변경시 프로시저와 동일하게 맞출 것.
DROP TABLE AIMIR.MONTH_WM;
CREATE TABLE AIMIR.MONTH_WM
(
MDEV_ID VARCHAR2(20) NOT NULL,
YYYYMM VARCHAR2(6) NOT NULL,
CHANNEL VARCHAR2(3) NOT NULL,
MDEV_TYPE VARCHAR2(20) NOT NULL,
DST NUMBER(2) NOT NULL,
DD VARCHAR2(2) NOT NULL,
METER_ID NUMBER(10),
METERINGTYPE NUMBER(2),
MDEV_ID_LAST NUMBER(1),
MODEM_ID NUMBER(10),
DEVICE_ID VARCHAR2(20),
DEVICE_TYPE VARCHAR2(15),
C_VALUE NUMBER(10),
BASEVALUE NUMBER(19, 4),
VALUE NUMBER(19, 4),
WRITEDATE VARCHAR2(14),
SUPPLIER_ID NUMBER(10),
CH_METHOD VARCHAR2(255),
CONTRACT_ID NUMBER(10),
ENDDEVICE_ID NUMBER(10)
)
TABLESPACE AIMIRDAT
NOLOGGING;
CREATE INDEX AIMIR.PK_MONTH_WM ON AIMIR.MONTH_WM (MDEV_ID, YYYYMM, CHANNEL, MDEV_TYPE, DST, DD) NOLOGGING TABLESPACE AIMIRIDX;;
ALTER TABLE AIMIR.MONTH_WM ADD CONSTRAINT PK_MONTH_WM PRIMARY KEY (MDEV_ID, YYYYMM, CHANNEL, MDEV_TYPE, DST, DD);
