--Tablespace는 사이트에 따라 변경될 수 있음.
--DROP TABLE AIMIR.DUMMY_DAYWM_TO_MONTHWM;
CREATE TABLE AIMIR.DUMMY_DAYWM_TO_MONTHWM
(
MDEV_ID VARCHAR2(20) NOT NULL,
YYYYMMDD VARCHAR2(8) NOT NULL,
CHANNEL VARCHAR2(3) NOT NULL,
MDEV_TYPE VARCHAR2(20) NOT NULL,
DST NUMBER(2) NOT NULL,
HH VARCHAR2(2) NOT NULL,
WRITEDATE VARCHAR2(14)
)
NOCOMPRESS LOGGING
TABLESPACE "AIMIRDAT" ;

CREATE INDEX AIMIR.IDX_DUMMY_DAYWM_TO_MONTHWM ON AIMIR.DUMMY_DAYWM_TO_MONTHWM(MDEV_ID, YYYYMMDD, CHANNEL, MDEV_TYPE, DST)
TABLESPACE "AIMIRIDX" ;
