
package com.oracle.xmlns.ssys.nurimeterdataproxy.nurimeterdata;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-21T11:43:40.100+01:00
 * Generated source version: 3.1.5
 * 
 */
public final class ExecutePtt_ExecuteBindQSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/SSYS/NuriMeterDataProxy/NuriMeterData", "execute_bindQSService");

    private ExecutePtt_ExecuteBindQSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ExecuteBindQSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ExecuteBindQSService ss = new ExecuteBindQSService(wsdlURL, SERVICE_NAME);
        ExecutePtt port = ss.getExecuteBindQSPort();  
        
        {
        System.out.println("Invoking execute...");
        com.aimir.mars.integration.bulkreading.xml.cim.MeterReadingsType _execute_part1 = null;
        javax.xml.datatype.XMLGregorianCalendar _execute__return = port.execute(_execute_part1);
        System.out.println("execute.result=" + _execute__return);


        }

        System.exit(0);
    }

}
