package com.oracle.xmlns.ssys.nurimeterdataproxy.nurimeterdata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-08-31T16:21:32.733+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/SSYS/NuriMeterDataProxy/NuriMeterData", name = "NuriMeterData")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface NuriMeterData {

    @WebMethod(operationName = "NuriMeterData_bulk", action = "execute")
    @WebResult(name = "dateTime", targetNamespace = "http://xmlns.oracle.com/SSYS/NuriMeterDataProxy/NuriMeterData", partName = "part1")
    public javax.xml.datatype.XMLGregorianCalendar nuriMeterDataBulk(
        @WebParam(partName = "part1", name = "MeterReadings", targetNamespace = "http://com.aimir.nuritelecom.com/CIM")
        com.aimir.mars.integration.bulkreading.xml.cim.MeterReadingsType request
    );
}
