package com.oracle.xmlns.ssys.nurimeterdataproxy.nurimeterdata;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * OSB Service
 *
 * This class was generated by Apache CXF 3.1.5
 * 2016-08-31T16:21:32.782+02:00
 * Generated source version: 3.1.5
 * 
 */
@WebServiceClient(name = "NuriMeterData_bulk_bindQSService", 
                  wsdlLocation = "file:NuriMeterDataProxy.wsdl",
                  targetNamespace = "http://xmlns.oracle.com/SSYS/NuriMeterDataProxy/NuriMeterData") 
public class NuriMeterDataBulkBindQSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/SSYS/NuriMeterDataProxy/NuriMeterData", "NuriMeterData_bulk_bindQSService");
    public final static QName NuriMeterDataBulkBindQSPort = new QName("http://xmlns.oracle.com/SSYS/NuriMeterDataProxy/NuriMeterData", "NuriMeterData_bulk_bindQSPort");
    static {
        URL url = null;
        try {
            url = new URL("file:NuriMeterDataProxy.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NuriMeterDataBulkBindQSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:NuriMeterDataProxy.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NuriMeterDataBulkBindQSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NuriMeterDataBulkBindQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NuriMeterDataBulkBindQSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public NuriMeterDataBulkBindQSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public NuriMeterDataBulkBindQSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public NuriMeterDataBulkBindQSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns NuriMeterData
     */
    @WebEndpoint(name = "NuriMeterData_bulk_bindQSPort")
    public NuriMeterData getNuriMeterDataBulkBindQSPort() {
        return super.getPort(NuriMeterDataBulkBindQSPort, NuriMeterData.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NuriMeterData
     */
    @WebEndpoint(name = "NuriMeterData_bulk_bindQSPort")
    public NuriMeterData getNuriMeterDataBulkBindQSPort(WebServiceFeature... features) {
        return super.getPort(NuriMeterDataBulkBindQSPort, NuriMeterData.class, features);
    }

}
