CREATE TABLE `devicevendor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `supplier_id` int(11) DEFAULT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` int(11) DEFAULT NULL,
  `address` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `descr` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_DEVICEVENDOR_01` (`supplier_id`,`name`),
  CONSTRAINT `FK_DEVICEVENDOR_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `devicemodel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` int(11) NOT NULL,
  `type_id` int(11) DEFAULT NULL,
  `devicevendor_id` int(11) DEFAULT NULL,
  `mdsIdPattern` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT '[0-9]*',
  `description` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_DEVICEMODEL_01` (`name`),
  KEY `FK_DEVICEMODEL_type_id` (`type_id`),
  KEY `FK_DEVICEMODEL_devicevendor_id` (`devicevendor_id`),
  CONSTRAINT `FK_DEVICEMODEL_devicevendor_id` FOREIGN KEY (`devicevendor_id`) REFERENCES `devicevendor` (`id`),
  CONSTRAINT `FK_DEVICEMODEL_type_id` FOREIGN KEY (`type_id`) REFERENCES `code` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `deviceconfig` (
  `devicemodel_fk` int(11) DEFAULT NULL,
  KEY `FK_DEVICECONFIG_devicemodel_fk` (`devicemodel_fk`),
  CONSTRAINT `FK_DEVICECONFIG_devicemodel_fk` FOREIGN KEY (`devicemodel_fk`) REFERENCES `devicemodel` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `modemconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `devicemodel_fk` int(11) DEFAULT NULL,
  `ONDEMAND_PARSER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ONDEMAND_SAVER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PARSER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SAVER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `swRevision` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `swVersion` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_MODEMCONFIG_01` (`name`),
  KEY `FK_MODEMCONFIG_devicemodel_fk` (`devicemodel_fk`),
  CONSTRAINT `FK_MODEMCONFIG_devicemodel_fk` FOREIGN KEY (`devicemodel_fk`) REFERENCES `devicemodel` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




CREATE TABLE `meterconfig` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `devicemodel_fk` int(11) DEFAULT NULL,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ONDEMAND_PARSER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ONDEMAND_SAVER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PARSER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SAVER_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADAPTER_CLASS_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LP_INTERVAL` int(11) DEFAULT NULL,
  `meterClass` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meterProtocol` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `phase` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `powerSupplySpec` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PULSE_CONST` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_METERCONFIG_01` (`name`),
  KEY `FK_METERCONFIG_devicemodel_fk` (`devicemodel_fk`),
  CONSTRAINT `FK_METERCONFIG_devicemodel_fk` FOREIGN KEY (`devicemodel_fk`) REFERENCES `devicemodel` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `obiscode` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `access_right` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attribute_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `attribute_No` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `class_Id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `class_Name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `dataType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `descr` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `devicemodel_id` int(11) DEFAULT NULL,
  `OBIS_CODE` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_OBISCODE_01` (`OBIS_CODE`,`class_Id`,`attribute_No`,`devicemodel_id`),
  KEY `FK_OBISCODE_devicemodel_id` (`devicemodel_id`),
  CONSTRAINT `FK_OBISCODE_devicemodel_id` FOREIGN KEY (`devicemodel_id`) REFERENCES `devicemodel` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `channel_config` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `data_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `channel_id` int(11) DEFAULT NULL,
  `meterconfig_id` int(11) DEFAULT NULL,
  `channel_index` int(11) NOT NULL,
  `display_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_CHANNEL_CONFIG_0` (`data_type`,`channel_id`,`meterconfig_id`),
  KEY `FK_CHANNEL_CONFIG_meterconfig_id` (`meterconfig_id`),
  KEY `FK_CHANNEL_CONFIG_channel_id` (`channel_id`),
  CONSTRAINT `FK_CHANNEL_CONFIG_channel_id` FOREIGN KEY (`channel_id`) REFERENCES `display_channel` (`id`),
  CONSTRAINT `FK_CHANNEL_CONFIG_meterconfig_id` FOREIGN KEY (`meterconfig_id`) REFERENCES `meterconfig` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `each_meter_channel_config` (
  `channel_index` int(11) NOT NULL,
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` int(11) NOT NULL,
  `channel_id` int(11) DEFAULT NULL,
  `data_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `display_type` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `divisor` int(11) DEFAULT NULL,
  `last_value_format_code` int(11) DEFAULT NULL,
  `last_value_format_size` int(11) DEFAULT NULL,
  `lp_value_format_code` int(11) DEFAULT NULL,
  `lp_value_format_size` int(11) DEFAULT NULL,
  `multiplier` double DEFAULT NULL,
  `scalar` int(11) DEFAULT NULL,
  PRIMARY KEY (`channel_index`,`mdev_id`,`mdev_type`),
  KEY `FK_EACH_METER_CHANNEL_CONFIG_channel_id` (`channel_id`),
  CONSTRAINT `FK_EACH_METER_CHANNEL_CONFIG_channel_id` FOREIGN KEY (`channel_id`) REFERENCES `display_channel` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `mbus_slave_io_module` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `analog_current` double DEFAULT NULL,
  `analog_current_cnv` double DEFAULT NULL,
  `analog_voltage` double DEFAULT NULL,
  `analog_voltage_cnv` double DEFAULT NULL,
  `degital_1` bit(1) DEFAULT NULL,
  `degital_2` bit(1) DEFAULT NULL,
  `degital_3` bit(1) DEFAULT NULL,
  `degital_4` bit(1) DEFAULT NULL,
  `degital_5` bit(1) DEFAULT NULL,
  `degital_6` bit(1) DEFAULT NULL,
  `degital_7` bit(1) DEFAULT NULL,
  `degital_8` bit(1) DEFAULT NULL,
  `degital_current` int(11) DEFAULT NULL,
  `INSTALL_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LAST_UPDATE_TIME` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mds_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `scale_current` int(11) DEFAULT NULL,
  `scale_voltage` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_MBUS_SLAVE_IO_MODULE_01` (`mds_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `mcu_codi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CODI_AUTO_SETTING` bit(1) DEFAULT NULL,
  `CODI_CHANNEL` int(11) DEFAULT NULL,
  `CODI_ENABLE_ENCRYPT` int(11) DEFAULT NULL,
  `CODI_EXT_PAN_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_FW_BUILD` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_FW_VER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_HW_VER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_INDEX` int(11) DEFAULT NULL,
  `CODI_LINK_KEY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_MASK` int(11) DEFAULT NULL,
  `CODI_MULTICAST_HOPS` int(11) DEFAULT NULL,
  `CODI_NETWORK_KEY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_PAN_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_PERMIT` int(11) DEFAULT NULL,
  `CODI_RESET_KIND` int(11) DEFAULT NULL,
  `CODI_RF_POWER` int(11) DEFAULT NULL,
  `CODI_ROUTE_DISCOVERY` bit(1) DEFAULT NULL,
  `CODI_SHORT_ID` int(11) DEFAULT NULL,
  `CODI_STRING` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_TX_POWER_MODE` int(11) DEFAULT NULL,
  `CODI_TYPE` int(11) DEFAULT NULL,
  `CODI_ZA_IF_VER` int(11) DEFAULT NULL,
  `CODI_ZZ_IF_VER` int(11) DEFAULT NULL,
  `MCU_CODI_BINDING_ID` int(11) DEFAULT NULL,
  `MCU_CODI_DEVICE_ID` int(11) DEFAULT NULL,
  `MCU_CODI_MEMORY_ID` int(11) DEFAULT NULL,
  `MCU_CODI_NEIGHBOR_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `mcu` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `SYS_ID` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `INSTALL_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IP_ADDR` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IPV6_ADDR` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GS1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ICC_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IMEI` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROTOCOL_TYPE` int(11) DEFAULT NULL,
  `PROTOCOL_VERSION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `SYS_HW_VERSION` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_SW_VERSION` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_SW_REVISION` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LAST_COMM_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DEVICEMODEL_ID` int(11) DEFAULT NULL,
  `MCU_TYPE` int(11) DEFAULT NULL,
  `MAC_ADDR` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_TLS_PORT` int(11) DEFAULT NULL,
  `SYS_TLS_VERSION` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BATTERY_CAPACITY` int(11) DEFAULT NULL,
  `FW_STATE` int(11) DEFAULT NULL,
  `GPIOX` double DEFAULT NULL,
  `GPIOY` double DEFAULT NULL,
  `GPIOZ` double DEFAULT NULL,
  `LAST_MODIFIED_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LAST_TIME_SYNC_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LAST_SW_UPDATE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOC_DETAIL` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOW_BATTREY_FLAG` int(11) DEFAULT NULL,
  `MANUFACTURED_DATE` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MCU_CODI_ID` int(11) DEFAULT NULL,
  `MCU_STATUS` int(11) DEFAULT NULL,
  `MCU_VAR_ID` bigint(20) DEFAULT NULL,
  `MOBILE_USAGE_FLAG` int(11) DEFAULT NULL,
  `NAME_SPACE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NETWORK_KEY` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NETWORK_KEY_IDX` int(11) DEFAULT NULL,
  `NETWORK_STATUS` int(11) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `po` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POWER_STATE` int(11) DEFAULT NULL,
  `SERVICE_ATM` int(11) DEFAULT NULL,
  `SIM_NUMBER` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SUPPLIER_ID` int(11) DEFAULT NULL,
  `SYS_CONTACT` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_CUR_TEMP` int(11) DEFAULT NULL,
  `SYS_DESCR` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_ETHER_TYPE` int(11) DEFAULT NULL,
  `SYS_HW_BUILD` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_JOIN_NODE_COUNT` int(11) DEFAULT NULL,
  `SYS_LOCAL_PORT` int(11) DEFAULT NULL,
  `SYS_LOCATION` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_MAX_TEMP` int(11) DEFAULT NULL,
  `SYS_MIN_TEMP` int(11) DEFAULT NULL,
  `SYS_MOBILE_ACCESS_POINT_NAME` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_MOBILE_MODE` int(11) DEFAULT NULL,
  `SYS_MOBILE_TYPE` int(11) DEFAULT NULL,
  `SYS_MOBILE_VENDOR` int(11) DEFAULT NULL,
  `SYS_MODEL` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_OP_MODE` int(11) DEFAULT NULL,
  `SYS_PHONE_NUMBER` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_POWER_TYPE` int(11) DEFAULT NULL,
  `SYS_RESET_REASON` int(11) DEFAULT NULL,
  `SYS_SECURE_PORT` int(11) DEFAULT NULL,
  `SYS_SERIAL_NUMBER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_SERVER` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_SERVER_ALARM_PORT` int(11) DEFAULT NULL,
  `SYS_SERVER_PORT` int(11) DEFAULT NULL,
  `SYS_STATE` int(11) DEFAULT NULL,
  `SYS_STATE_MASK` int(11) DEFAULT NULL,
  `SYS_TIME` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_TIME_ZONE` int(11) DEFAULT NULL,
  `SYS_TYPE` int(11) DEFAULT NULL,
  `SYS_UPTIME` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_VENDOR` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `UPDATE_SERVER_PORT` int(11) DEFAULT NULL,
  `AMI_NETWORK_ADDRESS` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AMI_NETWORK_ADDRESS_V6` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AMI_NETWORK_DEPTH` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_MCU_01` (`SYS_ID`),
  KEY `FK_MCU_parent_id` (`parent_id`),
  KEY `FK_MCU_MCU_CODI_ID` (`MCU_CODI_ID`),
  KEY `FK_MCU_DEVICEMODEL_ID` (`DEVICEMODEL_ID`),
  KEY `FK_MCU_MCU_STATUS` (`MCU_STATUS`),
  KEY `FK_MCU_MCU_TYPE` (`MCU_TYPE`),
  KEY `FK_MCU_LOCATION_ID` (`LOCATION_ID`),
  KEY `FK_MCU_PROTOCOL_TYPE` (`PROTOCOL_TYPE`),
  KEY `FK_MCU_SUPPLIER_ID` (`SUPPLIER_ID`),
  CONSTRAINT `FK_MCU_DEVICEMODEL_ID` FOREIGN KEY (`DEVICEMODEL_ID`) REFERENCES `devicemodel` (`id`),
  CONSTRAINT `FK_MCU_LOCATION_ID` FOREIGN KEY (`LOCATION_ID`) REFERENCES `location` (`id`),
  CONSTRAINT `FK_MCU_MCU_CODI_ID` FOREIGN KEY (`MCU_CODI_ID`) REFERENCES `mcu_codi` (`id`),
  CONSTRAINT `FK_MCU_MCU_STATUS` FOREIGN KEY (`MCU_STATUS`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_MCU_MCU_TYPE` FOREIGN KEY (`MCU_TYPE`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_MCU_PROTOCOL_TYPE` FOREIGN KEY (`PROTOCOL_TYPE`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_MCU_SUPPLIER_ID` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FK_MCU_parent_id` FOREIGN KEY (`parent_id`) REFERENCES `mcu` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `mcu_codi_binding` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CODI_BIND_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_BIND_INDEX` int(11) DEFAULT NULL,
  `CODI_BIND_LOCAL` int(11) DEFAULT NULL,
  `CODI_BIND_REMOTE` int(11) DEFAULT NULL,
  `CODI_BIND_TYPE` int(11) DEFAULT NULL,
  `CODI_LAST_HEARD` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mcu_codi_device` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CODI_BAUD_RATE` int(11) DEFAULT NULL,
  `CODI_DATA_BIT` int(11) DEFAULT NULL,
  `CODI_DEVICE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_INDEX` int(11) DEFAULT NULL,
  `CODI_PARITY_BIT` int(11) DEFAULT NULL,
  `CODI_RTS_CTS` int(11) DEFAULT NULL,
  `CODI_STOP_BIT` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mcu_codi_memory` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CODI_ADDRESS_TABLE_SIZE` int(11) DEFAULT NULL,
  `CODI_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_INDEX` int(11) DEFAULT NULL,
  `CODI_KEY_TABLE_SIZE` int(11) DEFAULT NULL,
  `CODI_MAX_CHILDREN` int(11) DEFAULT NULL,
  `CODI_MAX_HOPS` int(11) DEFAULT NULL,
  `CODI_NEIGHBOR_TABLE_SIZE` int(11) DEFAULT NULL,
  `CODI_PACKET_BUFFER_COUNT` int(11) DEFAULT NULL,
  `CODI_ROUTE_TABLE_SIZE` int(11) DEFAULT NULL,
  `CODI_SOFTWARE_VERSION` int(11) DEFAULT NULL,
  `CODI_SOURCE_ROUTE_TABLE_SIZE` int(11) DEFAULT NULL,
  `CODI_WHOLE_ADDRESS_TABLE_SIZE` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mcu_codi_neighbor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `CODI_NEIGHBOR_AGE` int(11) DEFAULT NULL,
  `CODI_NEIGHBOR_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CODI_NEIGHBOR_IN_COST` int(11) DEFAULT NULL,
  `CODI_NEIGHBOR_INDEX` int(11) DEFAULT NULL,
  `CODI_NEIGHBOR_LQI` int(11) DEFAULT NULL,
  `CODI_NEIGHBOR_OUT_COST` int(11) DEFAULT NULL,
  `CODI_NEIGHBOR_SHORT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mcuinstallimg` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `currentTimeMillisName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MCU_ID` int(11) DEFAULT NULL,
  `orginalName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_MCUINSTALLIMG_MCU_ID` (`MCU_ID`),
  CONSTRAINT `FK_MCUINSTALLIMG_MCU_ID` FOREIGN KEY (`MCU_ID`) REFERENCES `mcu` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `mcuvar` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `varAlamLogSaveDay` int(11) DEFAULT NULL,
  `varAutoResetCheckIntegererval` int(11) DEFAULT NULL,
  `varAutoResetTime` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `varAutoTimesyncIntegereval` int(11) DEFAULT NULL,
  `varCheckDayMask` int(11) DEFAULT NULL,
  `varCheckHourMask` int(11) DEFAULT NULL,
  `varCheckPeriod` int(11) DEFAULT NULL,
  `varCheckRetry` int(11) DEFAULT NULL,
  `varCheckStartMin` int(11) DEFAULT NULL,
  `varCmdHistSaveDay` int(11) DEFAULT NULL,
  `varCommLogSAveDay` int(11) DEFAULT NULL,
  `varDataSaveDay` int(11) DEFAULT NULL,
  `varDefaultGeMeteringOPtion` int(11) DEFAULT NULL,
  `varEnableAutoRegister` bit(1) DEFAULT NULL,
  `varEnableAutoSinkReset` bit(1) DEFAULT NULL,
  `varEnableAutoTimesync` bit(1) DEFAULT NULL,
  `varEnableAutoUpload` bit(1) DEFAULT NULL,
  `varEnableCmdHistLog` bit(1) DEFAULT NULL,
  `varEnableCommLog` bit(1) DEFAULT NULL,
  `varEnableDebugLog` bit(1) DEFAULT NULL,
  `varEnableGarbageCleaning` bit(1) DEFAULT NULL,
  `varEnableGpsTimesync` bit(1) DEFAULT NULL,
  `varEnableHeater` bit(1) DEFAULT NULL,
  `varEnableHighRam` bit(1) DEFAULT NULL,
  `varEnableKeepAlive` bit(1) DEFAULT NULL,
  `varEnableMask` int(11) DEFAULT NULL,
  `varEnableMemoryCheck` bit(1) DEFAULT NULL,
  `varEnableMeterCheck` bit(1) DEFAULT NULL,
  `varEnableMeterErroeRecovery` bit(1) DEFAULT NULL,
  `varEnableMeterTimesync` bit(1) DEFAULT NULL,
  `varEnableMobileStaticLog` bit(1) DEFAULT NULL,
  `varEnableMonitoring` bit(1) DEFAULT NULL,
  `varEnableReadMeterEvent` bit(1) DEFAULT NULL,
  `varEnableRecovery` bit(1) DEFAULT NULL,
  `varEnableSecurity` bit(1) DEFAULT NULL,
  `varEnableTimeBroadcast` bit(1) DEFAULT NULL,
  `varEventAlertLevel` int(11) DEFAULT NULL,
  `varEventLogSaveDay` int(11) DEFAULT NULL,
  `varEventReadDayMask` int(11) DEFAULT NULL,
  `varEventReadHourMask` int(11) DEFAULT NULL,
  `varFlashCriticalRate` int(11) DEFAULT NULL,
  `varHeterOffTemp` int(11) DEFAULT NULL,
  `varHeterOnTemp` int(11) DEFAULT NULL,
  `varKeepAlaiveIntegererval` int(11) DEFAULT NULL,
  `varMaxAlamLogSize` int(11) DEFAULT NULL,
  `varMaxCmdLogSize` int(11) DEFAULT NULL,
  `varMaxCommLogSize` int(11) DEFAULT NULL,
  `varMaxEventLogSize` int(11) DEFAULT NULL,
  `varMaxMeterLogSize` int(11) DEFAULT NULL,
  `varMaxMobileLogSize` int(11) DEFAULT NULL,
  `varMaxUpgradeLogSize` int(11) DEFAULT NULL,
  `varMaxUploadLogSize` int(11) DEFAULT NULL,
  `varMemoryCriticalRate` int(11) DEFAULT NULL,
  `varMeterDayMask` int(11) DEFAULT NULL,
  `varMeterHourMask` int(11) DEFAULT NULL,
  `varMeterIssueDate` int(11) DEFAULT NULL,
  `varMeterStartMin` int(11) DEFAULT NULL,
  `varMeterStrategy` int(11) DEFAULT NULL,
  `varMeterTimesyncDayMask` int(11) DEFAULT NULL,
  `varMeterTimesyncHourMask` int(11) DEFAULT NULL,
  `varMeterUploadCycle` int(11) DEFAULT NULL,
  `varMeterUploadCycleType` int(11) DEFAULT NULL,
  `varMeterUploadRetry` int(11) DEFAULT NULL,
  `varMeterUploadStartHour` int(11) DEFAULT NULL,
  `varMeterUploadStartMin` int(11) DEFAULT NULL,
  `varMeterUploadTryTime` int(11) DEFAULT NULL,
  `varMeteringPeriod` int(11) DEFAULT NULL,
  `varMeteringRetry` int(11) DEFAULT NULL,
  `varMobileLiveCheckIntegererval` int(11) DEFAULT NULL,
  `varMobileLiveCheckMEthod` int(11) DEFAULT NULL,
  `varMobileLogSaveDay` int(11) DEFAULT NULL,
  `varNapcGroupIntegererval` int(11) DEFAULT NULL,
  `varNapcRetruClear` int(11) DEFAULT NULL,
  `varNapcRetry` bit(1) DEFAULT NULL,
  `varNapcRetryHour` int(11) DEFAULT NULL,
  `varNapcRetryStartSecond` int(11) DEFAULT NULL,
  `varRecoveryDayMask` int(11) DEFAULT NULL,
  `varRecoveryHourMask` int(11) DEFAULT NULL,
  `varRecoveryPeriod` int(11) DEFAULT NULL,
  `varRecoveryRetry` int(11) DEFAULT NULL,
  `varRecoveryStartMin` int(11) DEFAULT NULL,
  `varScanningStrategy` int(11) DEFAULT NULL,
  `varSendDelay` int(11) DEFAULT NULL,
  `varSensorCleaningThreshold` int(11) DEFAULT NULL,
  `varSensorKeepAlive` int(11) DEFAULT NULL,
  `varSensorLimit` int(11) DEFAULT NULL,
  `varSensorMeterSaveCount` int(11) DEFAULT NULL,
  `varSinkAckWaitTime` int(11) DEFAULT NULL,
  `varSinkLedTurnOffIntegererval` int(11) DEFAULT NULL,
  `varSinkPollingIntegererval` int(11) DEFAULT NULL,
  `varSinkResetDelay` int(11) DEFAULT NULL,
  `varSinkResetIntegererval` int(11) DEFAULT NULL,
  `varStatusMonitorTime` int(11) DEFAULT NULL,
  `varSysMeteringThreadCount` int(11) DEFAULT NULL,
  `varSysPowerOffDelay` int(11) DEFAULT NULL,
  `varSysTempMonIntegererval` int(11) DEFAULT NULL,
  `varTimeBoardcastIntegererval` int(11) DEFAULT NULL,
  `varTimeSyncStrategy` int(11) DEFAULT NULL,
  `varTimesyncLogSaveDay` int(11) DEFAULT NULL,
  `varTimesyncLogSize` int(11) DEFAULT NULL,
  `varTimesyncThreshold` int(11) DEFAULT NULL,
  `varTransactionSaveDay` int(11) DEFAULT NULL,
  `varUpgradeLogSaveDay` int(11) DEFAULT NULL,
  `varUploadLogSaveDay` int(11) DEFAULT NULL,
  `varUploadTime` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `varValueMask` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `modem` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `MODEM` varchar(31) COLLATE utf8mb4_unicode_ci NOT NULL,
  `DEVICE_SERIAL` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `FW_VER` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HW_VER` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AMI_NETWORK_ADDRESS` varchar(128) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AMI_NETWORK_DEPTH` int(11) DEFAULT NULL,
  `BOOTLOADER_VER` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `COMM_STATE` int(11) DEFAULT NULL,
  `CPU_USAGE` int(11) DEFAULT NULL,
  `CURRENT_THRESHOLD` double DEFAULT NULL,
  `FW_REVISION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GPIOX` double DEFAULT NULL,
  `GPIOY` double DEFAULT NULL,
  `GPIOZ` double DEFAULT NULL,
  `GS1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ICC_ID` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ID_TYPE` int(11) DEFAULT NULL,
  `IMEI` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IMSI` varchar(36) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSTALL_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSTALLED_SITE_IMG` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INTERFACE_TYPE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IP_ADDR` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LAST_LINK_TIME` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LAST_RESET_CODE` int(11) DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `LP_PERIOD` int(11) DEFAULT NULL,
  `MAC_ADDR` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MANUFACTURED_DATE` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MCU_ID` int(11) DEFAULT NULL,
  `MEMORY_USAGE` int(11) DEFAULT NULL,
  `DEVICEMODEL_ID` int(11) DEFAULT NULL,
  `MODEM_STATUS` int(11) DEFAULT NULL,
  `MODEM_TYPE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NAME_SPACE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NODE_KIND` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NODE_TYPE` int(11) DEFAULT NULL,
  `MODEM_ID` int(11) DEFAULT NULL,
  `PHONE_NUMBER` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PO` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `POWER_THRESHOLD` double DEFAULT NULL,
  `PROTOCOL_TYPE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROTOCOL_VERSION` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RESET_COUNT` int(11) DEFAULT NULL,
  `RF_POWER` bigint(20) DEFAULT NULL,
  `SIM_NUMBER` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SUPPLIER_ID` int(11) DEFAULT NULL,
  `SW_VER` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ZDZD_IF_VERSION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `APN_ADDRESS` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `APN_ID` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `APN_PASSWORD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BAND_WIDTH` int(11) DEFAULT NULL,
  `LINK_KEY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ETX` int(11) DEFAULT NULL,
  `FREQUENCY` int(11) DEFAULT NULL,
  `HOPS_TO_BASESTATION` int(11) DEFAULT NULL,
  `IPV6_ADDRESS` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `listen_port` int(11) DEFAULT NULL,
  `LQI` int(11) DEFAULT NULL,
  `METERING_INTERVAL` int(11) DEFAULT NULL,
  `METERING_TIME_RANGE` int(11) DEFAULT NULL,
  `PAN_ID` int(11) DEFAULT NULL,
  `RESET_INTERVAL` int(11) DEFAULT NULL,
  `RSSI` int(11) DEFAULT NULL,
  `SECURITY_KEY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `EUI_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROD_MAKE_DATE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROD_MAKER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PROD_SERIAL` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ACTIVE_TIME` int(11) DEFAULT NULL,
  `ALARM_FLAG` int(11) DEFAULT NULL,
  `ALARM_MASK` int(11) DEFAULT NULL,
  `AUTO_TRAP_FLAG` bit(1) DEFAULT NULL,
  `BATTERY_CAPACITY` double DEFAULT NULL,
  `BATTERY_STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BATTERY_VOLT` double DEFAULT NULL,
  `CHANNEL_ID` int(11) DEFAULT NULL,
  `EXTPAN_ID` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIXED_RESET` varchar(5) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LP_CHOICE` int(11) DEFAULT NULL,
  `MANUAL_ENABLE` bit(1) DEFAULT NULL,
  `METERING_DAY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `METERING_HOUR` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NEED_JOIN_SET` bit(1) DEFAULT NULL,
  `NETWORK_KEY` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NETWORK_TYPE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `OPERATING_DAY` int(11) DEFAULT NULL,
  `PERMIT_MODE` int(11) DEFAULT NULL,
  `PERMIT_STATE` int(11) DEFAULT NULL,
  `POWER_TYPE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `RESET_REASON` int(11) DEFAULT NULL,
  `SECURITY_ENABLE` bit(1) DEFAULT NULL,
  `SOLAR_ADV` double DEFAULT NULL,
  `SOLAR_BDCV` double DEFAULT NULL,
  `SOLAR_CHG_BV` double DEFAULT NULL,
  `TEST_FLAG` bit(1) DEFAULT NULL,
  `TRAP_DATE` int(11) DEFAULT NULL,
  `TRAP_HOUR` int(11) DEFAULT NULL,
  `TRAP_Minute` int(11) DEFAULT NULL,
  `TRAP_SECOND` int(11) DEFAULT NULL,
  `VOLT_OFFSET` double DEFAULT NULL,
  `CELL_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ERROR_STATUS` int(11) DEFAULT NULL,
  `MOBILE_NETWORK_TYPE` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MODULE_REVISION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MODULE_VERSION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TX_POWER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_CONTACT` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_DESCR` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_FACTORY_RESET` int(11) DEFAULT NULL,
  `SYS_FW_VERSION` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_IP_ADDR` varchar(16) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_LOCATION` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_NAME` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_NODE_TYPE` int(11) DEFAULT NULL,
  `SYS_OBJECT_ID` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_PORT` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_RESET` int(11) DEFAULT NULL,
  `SYS_RTS_CTSENABLE` bit(1) DEFAULT NULL,
  `SYS_SERIAL_PARITY_TYPE` int(11) DEFAULT NULL,
  `SYS_SERIAL_RATE` int(11) DEFAULT NULL,
  `SYS_SERIAL_STOP_BIT` int(11) DEFAULT NULL,
  `SYS_SERIAL_WORDBIT` int(11) DEFAULT NULL,
  `SYS_SERVICE` int(11) DEFAULT NULL,
  `SYS_STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_UPTIME` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SYS_USE_DHCP` int(11) DEFAULT NULL,
  `REPEATING_DAY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPEATING_HOUR` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `REPEATING_SETUP_SEC` int(11) DEFAULT NULL,
  `ARM_FW_BUILD` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ARM_FW_VER` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ARM_HW_VER` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ARM_MODEL` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_MODEM_01` (`DEVICE_SERIAL`),
  KEY `FK_MODEM_DEVICEMODEL_ID` (`DEVICEMODEL_ID`),
  KEY `FK_MODEM_LOCATION_ID` (`LOCATION_ID`),
  KEY `FK_MODEM_MODEM_STATUS` (`MODEM_STATUS`),
  KEY `FK_MODEM_SUPPLIER_ID` (`SUPPLIER_ID`),
  KEY `FK_MODEM_MCU_ID` (`MCU_ID`),
  KEY `FK_MODEM_MODEM_ID` (`MODEM_ID`),
  CONSTRAINT `FK_MODEM_DEVICEMODEL_ID` FOREIGN KEY (`DEVICEMODEL_ID`) REFERENCES `devicemodel` (`id`),
  CONSTRAINT `FK_MODEM_LOCATION_ID` FOREIGN KEY (`LOCATION_ID`) REFERENCES `location` (`id`),
  CONSTRAINT `FK_MODEM_MCU_ID` FOREIGN KEY (`MCU_ID`) REFERENCES `mcu` (`id`),
  CONSTRAINT `FK_MODEM_MODEM_ID` FOREIGN KEY (`MODEM_ID`) REFERENCES `modem` (`id`),
  CONSTRAINT `FK_MODEM_MODEM_STATUS` FOREIGN KEY (`MODEM_STATUS`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_MODEM_SUPPLIER_ID` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




CREATE TABLE `meter` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `METER` varchar(31) COLLATE utf8mb4_unicode_ci NOT NULL,
  `MDS_ID` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `WRITE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `LP_INTERVAL` int(11) DEFAULT NULL,
  `metertype_id` int(11) DEFAULT NULL,
  `devicemodel_id` int(11) DEFAULT NULL,
  `MODEM_ID` int(11) DEFAULT NULL,
  `SUPPLIER_ID` int(11) DEFAULT NULL,
  `INSTALL_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LAST_METERING_VALUE` double DEFAULT NULL,
  `LAST_READ_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `METER_STATUS` int(11) DEFAULT NULL,
  `LAST_TIMESYNC_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `conditions` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DELETE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DistTrfmrSubstation_ID` int(11) DEFAULT NULL,
  `distTrfmrSubstationMeter_A_id` int(11) DEFAULT NULL,
  `distTrfmrSubstationMeter_B_id` int(11) DEFAULT NULL,
  `distTrfmrSubstationMeter_C_id` int(11) DEFAULT NULL,
  `ENDDEVICE_ID` int(11) DEFAULT NULL,
  `EXPIRATION_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `friendly_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `GPIOX` double DEFAULT NULL,
  `GPIOY` double DEFAULT NULL,
  `GPIOZ` double DEFAULT NULL,
  `GS1` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `HW_VERSION` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `IHD_ID` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `installDateHidden` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `installDateUpdate` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSTALL_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSTALL_PROPERTY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `INSTALLED_SITE_IMG` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_manual_meter` int(11) DEFAULT NULL,
  `MANUFACTURED_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `METER_CAUTION` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `METER_ERROR` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `MODEM_PORT` int(11) DEFAULT NULL,
  `MSA` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PHASE` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PREPAYMENT_METER` bit(1) DEFAULT NULL,
  `PULSE_CONSTANT` double DEFAULT NULL,
  `PURCHASE_PRICE` double DEFAULT NULL,
  `QUALIFIED_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SHORT_ID` int(11) DEFAULT NULL,
  `SW_NAME` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SW_UPDATE_DATE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SW_VERSION` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `TIME_DIFF` bigint(20) DEFAULT NULL,
  `USAGE_THRESHOLD` double DEFAULT NULL,
  `CT` double DEFAULT NULL,
  `DST_APPLY_ON` bit(1) DEFAULT NULL,
  `DST_SEASON_On` bit(1) DEFAULT NULL,
  `METERELEMENT_ID` int(11) DEFAULT NULL,
  `POWER_GRID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SWITCH_ACTIVATE_STATUS` int(11) DEFAULT NULL,
  `SWITCH_STATUS` int(11) DEFAULT NULL,
  `TRANSFORMER_RATIO` double DEFAULT NULL,
  `VT` double DEFAULT NULL,
  `ALARM_STATUS` int(11) DEFAULT NULL,
  `CORRECT_PULSE` double DEFAULT NULL,
  `CURRENT_PULSE` double DEFAULT NULL,
  `INIT_PULSE` double DEFAULT NULL,
  `APPARATUS_ROOM_NUMBER` int(11) DEFAULT NULL,
  `FLOW_PER_UNIT_PULSE` int(11) DEFAULT NULL,
  `HEAT_TYPE` int(11) DEFAULT NULL,
  `HEATING_AREA` double DEFAULT NULL,
  `INSTALLED_PRESS_SENSOR` bit(1) DEFAULT NULL,
  `METERING_UNIT` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `NUM_OF_ROOM` int(11) DEFAULT NULL,
  `STANDARD` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `QMAX` double DEFAULT NULL,
  `METER_SIZE` double DEFAULT NULL,
  `UNDER_GROUND` bit(1) DEFAULT NULL,
  `VALVE_SERIAL` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_METER_01` (`MDS_ID`),
  KEY `FK_METER_metertype_id` (`metertype_id`),
  KEY `FK_METER_MODEM_ID` (`MODEM_ID`),
  KEY `FK_METER_LOCATION_ID` (`LOCATION_ID`),
  KEY `FK_METER_SUPPLIER_ID` (`SUPPLIER_ID`),
  KEY `FK_METER_devicemodel_id` (`devicemodel_id`),
  KEY `FK_METER_METER_STATUS` (`METER_STATUS`),
  CONSTRAINT `FK_METER_metertype_id` FOREIGN KEY (`metertype_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_METER_MODEM_ID` FOREIGN KEY (`MODEM_ID`) REFERENCES `modem` (`id`),
  CONSTRAINT `FK_METER_LOCATION_ID` FOREIGN KEY (`LOCATION_ID`) REFERENCES `location` (`id`),
  CONSTRAINT `FK_METER_SUPPLIER_ID` FOREIGN KEY (`SUPPLIER_ID`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FK_METER_devicemodel_id` FOREIGN KEY (`devicemodel_id`) REFERENCES `devicemodel` (`id`),
  CONSTRAINT `FK_METER_METER_STATUS` FOREIGN KEY (`METER_STATUS`) REFERENCES `code` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


