
CREATE TABLE `customer` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `address1` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address2` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `aliasName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `deniedReason` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emailYn` int(11) DEFAULT 1,
  `failedLoginCount` int(11) DEFAULT NULL,
  `IS_FIRSTLOGIN` bit(1) DEFAULT NULL,
  `LAST_CHARGE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastLoginTime` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastPasswordChangeTime` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `locale` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `LOCATION_ID` int(11) DEFAULT NULL,
  `loginDenied` bit(1) DEFAULT NULL,
  `loginId` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobileNumber` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(256) COLLATE utf8mb4_unicode_ci NOT NULL,
  `OPERATOR_STATUS` int(11) DEFAULT 1,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pucNumber` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `role_id` int(11) DEFAULT NULL,
  `showDefaultDashboard` bit(1) DEFAULT NULL,
  `smsYn` int(11) DEFAULT 1,
  `supplier_id` int(11) DEFAULT NULL,
  `telNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `UPDATE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USE_LOCATION` bit(1) DEFAULT NULL,
  `WRITE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `zipCode` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `address3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `co2MileId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `customtype_id` int(11) DEFAULT NULL,
  `customerNo` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `demandResponse` bit(1) DEFAULT NULL,
  `familyCnt` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `identityOrCompanyRegNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `initials` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mobileNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postalAddressLine1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postalAddressLine2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postalCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `postalSuburb` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telephoneNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vatNo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `workTelephone` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_CUSTOMER_01` (`customerNo`),
  UNIQUE KEY `UK_CUSTOMER_02` (`loginId`),
  KEY `FK_CUSTOMER_role_id` (`role_id`),
  KEY `FK_CUSTOMER_customtype_id` (`customtype_id`),
  KEY `FK_CUSTOMER_LOCATION_ID` (`LOCATION_ID`),
  KEY `FK_CUSTOMER_supplier_id` (`supplier_id`),
  CONSTRAINT `FK_CUSTOMER_LOCATION_ID` FOREIGN KEY (`LOCATION_ID`) REFERENCES `location` (`id`),
  CONSTRAINT `FK_CUSTOMER_customtype_id` FOREIGN KEY (`customtype_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_CUSTOMER_role_id` FOREIGN KEY (`role_id`) REFERENCES `role` (`id`),
  CONSTRAINT `FK_CUSTOMER_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;




CREATE TABLE `contract` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ADDRESS1` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ADDRESS3` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `AMOUNT_PAID` double DEFAULT NULL,
  `APPLY_DATE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ARREARS_CONTRACT_COUNT` int(11) DEFAULT NULL,
  `ARREARS_PAYMENT_COUNT` int(11) DEFAULT NULL,
  `barcode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `BILL_DATE` int(11) DEFAULT 1,
  `CASH_POINT` int(11) DEFAULT NULL,
  `CHARGE_AVAILABLE` int(11) DEFAULT 1,
  `chargedCredit` double DEFAULT NULL,
  `CONTRACT_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contractDemand` double DEFAULT NULL,
  `contractIndex` int(11) DEFAULT NULL,
  `CONTRACT_NUMBER` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `CONTRACT_PRICE` double DEFAULT NULL,
  `creditstatus_id` int(11) DEFAULT NULL,
  `credittype_id` int(11) DEFAULT NULL,
  `CURRENTARREARS` float DEFAULT 0,
  `currentCredit` double DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `DELAY_DAY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `distTrfmrSubstationMeter_A_id` int(11) DEFAULT NULL,
  `distTrfmrSubstationMeter_B_id` int(11) DEFAULT NULL,
  `distTrfmrSubstationMeter_C_id` int(11) DEFAULT NULL,
  `emergencyCreditAutoChange` bit(1) DEFAULT NULL,
  `emergencyCreditAvailable` bit(1) DEFAULT NULL,
  `emergencyCreditMaxDuration` int(11) DEFAULT NULL,
  `emergencyCreditStartTime` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FIRSTARREARS` double DEFAULT NULL,
  `keyNum` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `keytype_id` int(11) DEFAULT NULL,
  `lastChargeCnt` int(11) DEFAULT NULL,
  `LAST_NOTIFICATION_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastTokenDate` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastTokenId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `NOTIFICATION_INTERVAL` int(11) DEFAULT NULL,
  `NOTIFICATION_PERIOD` int(11) DEFAULT NULL,
  `NOTIFICATION_TIME` int(11) DEFAULT NULL,
  `NOTIFICATION_WEEKLY_FRI` bit(1) DEFAULT NULL,
  `NOTIFICATION_WEEKLY_MON` bit(1) DEFAULT NULL,
  `NOTIFICATION_WEEKLY_SAT` bit(1) DEFAULT NULL,
  `NOTIFICATION_WEEKLY_SUN` bit(1) DEFAULT NULL,
  `NOTIFICATION_WEEKLY_THU` bit(1) DEFAULT NULL,
  `NOTIFICATION_WEEKLY_TUE` bit(1) DEFAULT NULL,
  `NOTIFICATION_WEEKLY_WED` bit(1) DEFAULT NULL,
  `OLDARREARS` float DEFAULT 0,
  `operator_id` int(11) DEFAULT NULL,
  `preMdsId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PREPAY_START_TIME` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prepaymentPowerDelay` double DEFAULT NULL,
  `prepaymentThreshold` int(11) DEFAULT NULL,
  `RECEIPT_NUMBER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SERVICE_POINT_ID` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `SERVICETYPE2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `servicetype_id` int(11) DEFAULT NULL,
  `sic_id` int(11) DEFAULT NULL,
  `SMS_NUMBER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `tariffIndex_id` int(11) DEFAULT NULL,
  `THRESHOLD1` double DEFAULT NULL,
  `THRESHOLD2` double DEFAULT NULL,
  `THRESHOLD3` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_CONTRACT_01` (`CONTRACT_NUMBER`),
  KEY `FK_CONTRACT_status_id` (`status_id`),
  KEY `FK_CONTRACT_location_id` (`location_id`),
  KEY `FK_CONTRACT_supplier_id` (`supplier_id`),
  KEY `FK_CONTRACT_tariffIndex_id` (`tariffIndex_id`),
  KEY `FK_CONTRACT_keytype_id` (`keytype_id`),
  KEY `FK_CONTRACT_customer_id` (`customer_id`),
  KEY `FK_CONTRACT_creditstatus_id` (`creditstatus_id`),
  KEY `FK_CONTRACT_credittype_id` (`credittype_id`),
  KEY `FK_CONTRACT_sic_id` (`sic_id`),
  KEY `FK_CONTRACT_operator_id` (`operator_id`),
  KEY `FK_CONTRACT_servicetype_id` (`servicetype_id`),
  KEY `FK_CONTRACT_meter_id` (`meter_id`),
  CONSTRAINT `FK_CONTRACT_creditstatus_id` FOREIGN KEY (`creditstatus_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_CONTRACT_credittype_id` FOREIGN KEY (`credittype_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_CONTRACT_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `FK_CONTRACT_keytype_id` FOREIGN KEY (`keytype_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_CONTRACT_location_id` FOREIGN KEY (`location_id`) REFERENCES `location` (`id`),
  CONSTRAINT `FK_CONTRACT_meter_id` FOREIGN KEY (`meter_id`) REFERENCES `meter` (`id`),
  CONSTRAINT `FK_CONTRACT_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `operator` (`id`),
  CONSTRAINT `FK_CONTRACT_servicetype_id` FOREIGN KEY (`servicetype_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_CONTRACT_sic_id` FOREIGN KEY (`sic_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_CONTRACT_status_id` FOREIGN KEY (`status_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_CONTRACT_supplier_id` FOREIGN KEY (`supplier_id`) REFERENCES `supplier` (`id`),
  CONSTRAINT `FK_CONTRACT_tariffIndex_id` FOREIGN KEY (`tariffIndex_id`) REFERENCES `tarifftype` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `operator_contract` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contract_id` int(11) DEFAULT NULL,
  `CONTRACT_STATUS` char(1) COLLATE utf8mb4_unicode_ci DEFAULT '1',
  `CUSTOMER_NUMBER` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `FRIENDLYNAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operator_id` int(11) DEFAULT NULL,
  `UPDATE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WRITE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_OPERATOR_CONTRACT_operator_id` (`operator_id`),
  KEY `FK_OPERATOR_CONTRACT_contract_id` (`contract_id`),
  CONSTRAINT `FK_OPERATOR_CONTRACT_contract_id` FOREIGN KEY (`contract_id`) REFERENCES `contract` (`id`),
  CONSTRAINT `FK_OPERATOR_CONTRACT_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `operator` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contractcapacity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `capacity` double DEFAULT NULL,
  `CONTRACT_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CONTRACT_NUMBER` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contractTypeCode_id` int(11) DEFAULT NULL,
  `threshold1` double DEFAULT NULL,
  `threshold2` double DEFAULT NULL,
  `threshold3` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_CONTRACTCAPACITY_01` (`CONTRACT_NUMBER`),
  KEY `FK_CONTRACTCAPACITY_contractTypeCode_id` (`contractTypeCode_id`),
  CONSTRAINT `FK_CONTRACTCAPACITY_contractTypeCode_id` FOREIGN KEY (`contractTypeCode_id`) REFERENCES `tarifftype` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `contractchangelog` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `afterValue` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `beforeValue` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `changeField` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `descr` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `operator_id` int(11) DEFAULT NULL,
  `startDatetime` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `writeDatetime` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_CONTRACTCHANGELOG_customer_id` (`customer_id`),
  KEY `FK_CONTRACTCHANGELOG_contract_id` (`contract_id`),
  KEY `FK_CONTRACTCHANGELOG_operator_id` (`operator_id`),
  CONSTRAINT `FK_CONTRACTCHANGELOG_contract_id` FOREIGN KEY (`contract_id`) REFERENCES `contract` (`id`),
  CONSTRAINT `FK_CONTRACTCHANGELOG_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `FK_CONTRACTCHANGELOG_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `operator` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `prepayment_auth_device` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `authKey` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `friendlyName` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `WRITE_DATE` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `vendor_casher` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `casherId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `isFirst` bit(1) DEFAULT NULL,
  `isManager` bit(1) DEFAULT NULL,
  `lastUpdateDate` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `macAddress` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `vendor_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_VENDOR_CASHER_vendor_id` (`vendor_id`),
  CONSTRAINT `FK_VENDOR_CASHER_vendor_id` FOREIGN KEY (`vendor_id`) REFERENCES `operator` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
