
CREATE TABLE `networkinfolog` (
  `command` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dateTime` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `targetNode` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `antAttenuation` double DEFAULT NULL,
  `cellId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `coapResponseTime` double DEFAULT NULL,
  `cpuUsage` int(11) DEFAULT NULL,
  `currentNetworkStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `etx` double DEFAULT NULL,
  `frequency` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hops` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `imei` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `imsi` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ipAddr` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastConnectionStatus` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `linkBudget` double DEFAULT NULL,
  `loss` double DEFAULT NULL,
  `lqi` double DEFAULT NULL,
  `memoryUsage` int(11) DEFAULT NULL,
  `mobileNetworkType` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mtClock` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obisCode` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obisResponseTime` double DEFAULT NULL,
  `obisResult` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `obisValue` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `packetSize` int(11) DEFAULT NULL,
  `rssi` double DEFAULT NULL,
  `rtt` double DEFAULT NULL,
  `temperature` double DEFAULT NULL,
  `totalTxSize` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `ttl` double DEFAULT NULL,
  `txPower` double DEFAULT NULL,
  `weather` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`command`,`dateTime`,`targetNode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;