CREATE TABLE `debtlog` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `prepaymentLog_id` bigint(20) DEFAULT NULL,
  `chargedDebt` double DEFAULT NULL,
  `customerId` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DEBT` double DEFAULT NULL,
  `DEBT_REF` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `DEBT_TYPE` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PARTPAYINFO` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `PRE_DEBT` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_DEBTLOG_01` (`customerId`,`prepaymentLog_id`,`DEBT_REF`,`DEBT_TYPE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE `prepaymentlog` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `ACTIVE_ENERGY_EXPORT` double DEFAULT NULL,
  `ACTIVE_ENERGY_IMPORT` double DEFAULT NULL,
  `additionalSubsidy` double DEFAULT NULL,
  `ARREARS` double DEFAULT NULL,
  `auth_code` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `balance` double DEFAULT NULL,
  `BANK_OFFICE_CODE` int(11) DEFAULT NULL,
  `CANCEL_DATE` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `CANCEL_REASON` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `chargedArrears` double DEFAULT NULL,
  `chargedCredit` double DEFAULT NULL,
  `CHEQUE_NO` varchar(25) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `DAYS_FROM_CHARGE` int(11) DEFAULT NULL,
  `DEBT_REF` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `descr` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `emergencyCreditAvailable` int(11) DEFAULT NULL,
  `govLevy` double DEFAULT NULL,
  `INIT_CREDIT` float DEFAULT 0,
  `IS_CANCELED` bit(1) DEFAULT NULL,
  `keyNum` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `keytype_id` int(11) DEFAULT NULL,
  `LAST_LP_TIME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lastTokenDate` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastTokenId` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lifeLineSubsidy` double DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `monthlyPaidAmount` double DEFAULT NULL,
  `monthlyServiceCharge` double DEFAULT NULL,
  `monthlyTotalAmount` double DEFAULT NULL,
  `municipalityCode_id` int(11) DEFAULT NULL,
  `operator_id` int(11) DEFAULT NULL,
  `PARTPAYINFO` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `pay_type_code` int(11) DEFAULT NULL,
  `power_limit` double DEFAULT NULL,
  `PRE_ARREARS` double DEFAULT NULL,
  `PRE_BALANCE` double DEFAULT NULL,
  `publicLevy` double DEFAULT NULL,
  `subsidy` double DEFAULT NULL,
  `tariffIndex_id` int(11) DEFAULT NULL,
  `used_Consumption` double DEFAULT NULL,
  `used_Cost` double DEFAULT NULL,
  `utilityRelief` double DEFAULT NULL,
  `vat` double DEFAULT NULL,
  `vatOnSubsidy` double DEFAULT NULL,
  `vendorCasher_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_PREPAYMENTLOG_keytype_id` (`keytype_id`),
  KEY `FK_PREPAYMENTLOG_municipalityCode_id` (`municipalityCode_id`),
  KEY `FK_PREPAYMENTLOG_tariffIndex_id` (`tariffIndex_id`),
  KEY `FK_PREPAYMENTLOG_customer_id` (`customer_id`),
  KEY `FK_PREPAYMENTLOG_vendorCasher_id` (`vendorCasher_id`),
  KEY `FK_PREPAYMENTLOG_location_id` (`location_id`),
  KEY `FK_PREPAYMENTLOG_pay_type_code` (`pay_type_code`),
  KEY `FK_PREPAYMENTLOG_contract_id` (`contract_id`),
  KEY `FK_PREPAYMENTLOG_operator_id` (`operator_id`),
  CONSTRAINT `FK_PREPAYMENTLOG_contract_id` FOREIGN KEY (`contract_id`) REFERENCES `contract` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_keytype_id` FOREIGN KEY (`keytype_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_location_id` FOREIGN KEY (`location_id`) REFERENCES `location` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_municipalityCode_id` FOREIGN KEY (`municipalityCode_id`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `operator` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_pay_type_code` FOREIGN KEY (`pay_type_code`) REFERENCES `code` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_tariffIndex_id` FOREIGN KEY (`tariffIndex_id`) REFERENCES `tarifftype` (`id`),
  CONSTRAINT `FK_PREPAYMENTLOG_vendorCasher_id` FOREIGN KEY (`vendorCasher_id`) REFERENCES `vendor_casher` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE `deposit_history` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `prepaymentLog_id` bigint(20) DEFAULT NULL,
  `CANCEL_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `change_date` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `charge_credit` double DEFAULT NULL,
  `charge_deposit` double DEFAULT NULL,
  `commission` float DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `customer_id` int(11) DEFAULT NULL,
  `deposit` float DEFAULT 0,
  `IS_CANCELED` bit(1) DEFAULT NULL,
  `loginUser_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `netValue` double DEFAULT NULL,
  `operator_id` int(11) DEFAULT NULL,
  `tax` double DEFAULT NULL,
  `taxRate` float DEFAULT NULL,
  `value` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_DEPOSIT_HISTORY_contract_id` (`contract_id`),
  KEY `FK_DEPOSIT_HISTORY_customer_id` (`customer_id`),
  KEY `FK_DEPOSIT_HISTORY_operator_id` (`operator_id`),
  KEY `FK_DEPOSIT_HISTORY_prepaymentLog_id` (`prepaymentLog_id`),
  KEY `FK_DEPOSIT_HISTORY_loginUser_id` (`loginUser_id`),
  KEY `FK_DEPOSIT_HISTORY_meter_id` (`meter_id`),
  CONSTRAINT `FK_DEPOSIT_HISTORY_contract_id` FOREIGN KEY (`contract_id`) REFERENCES `contract` (`id`),
  CONSTRAINT `FK_DEPOSIT_HISTORY_customer_id` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
  CONSTRAINT `FK_DEPOSIT_HISTORY_loginUser_id` FOREIGN KEY (`loginUser_id`) REFERENCES `operator` (`id`),
  CONSTRAINT `FK_DEPOSIT_HISTORY_meter_id` FOREIGN KEY (`meter_id`) REFERENCES `meter` (`id`),
  CONSTRAINT `FK_DEPOSIT_HISTORY_operator_id` FOREIGN KEY (`operator_id`) REFERENCES `operator` (`id`),
  CONSTRAINT `FK_DEPOSIT_HISTORY_prepaymentLog_id` FOREIGN KEY (`prepaymentLog_id`) REFERENCES `prepaymentlog` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



