CREATE TABLE `meteringdata_gm` (
  `yyyymmddhhmmss` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dst` int(11) NOT NULL DEFAULT 0,
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ch1` double DEFAULT NULL,
  `ch2` double DEFAULT NULL,
  `ch3` double DEFAULT NULL,
  `ch4` double DEFAULT NULL,
  `ch5` double DEFAULT NULL,
  `ch6` double DEFAULT NULL,
  `ch7` double DEFAULT NULL,
  `device_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meteringType` int(11) DEFAULT NULL,
  `value` double DEFAULT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) NOT NULL,
  PRIMARY KEY (`yyyymmddhhmmss`,`dst`,`mdev_id`,`mdev_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meteringdata_hm` (
  `yyyymmddhhmmss` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dst` int(11) NOT NULL DEFAULT 0,
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ch1` double DEFAULT NULL,
  `ch2` double DEFAULT NULL,
  `ch3` double DEFAULT NULL,
  `ch4` double DEFAULT NULL,
  `ch5` double DEFAULT NULL,
  `ch6` double DEFAULT NULL,
  `ch7` double DEFAULT NULL,
  `device_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meteringType` int(11) DEFAULT NULL,
  `value` double DEFAULT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) NOT NULL,
  PRIMARY KEY (`yyyymmddhhmmss`,`dst`,`mdev_id`,`mdev_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meteringdata_nm` (
  `yyyymmddhhmmss` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dst` int(11) NOT NULL DEFAULT 0,
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ch1` double DEFAULT NULL,
  `ch2` double DEFAULT NULL,
  `ch3` double DEFAULT NULL,
  `ch4` double DEFAULT NULL,
  `ch5` double DEFAULT NULL,
  `ch6` double DEFAULT NULL,
  `ch7` double DEFAULT NULL,
  `device_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meteringType` int(11) DEFAULT NULL,
  `value` double DEFAULT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) NOT NULL,
  PRIMARY KEY (`yyyymmddhhmmss`,`dst`,`mdev_id`,`mdev_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meteringdata_spm` (
  `yyyymmddhhmmss` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dst` int(11) NOT NULL DEFAULT 0,
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `ch1` double DEFAULT NULL,
  `ch2` double DEFAULT NULL,
  `ch3` double DEFAULT NULL,
  `ch4` double DEFAULT NULL,
  `ch5` double DEFAULT NULL,
  `ch6` double DEFAULT NULL,
  `ch7` double DEFAULT NULL,
  `device_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meteringType` int(11) DEFAULT NULL,
  `value` double DEFAULT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) NOT NULL,
  PRIMARY KEY (`yyyymmddhhmmss`,`dst`,`mdev_id`,`mdev_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `meteringdata_thum` (
  `yyyymmddhhmmss` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dst` int(11) NOT NULL DEFAULT 0,
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` int(11) NOT NULL,
  `bu` double DEFAULT NULL,
  `cbValue` double DEFAULT NULL,
  `chValue` double DEFAULT NULL,
  `ctValue` double DEFAULT NULL,
  `device_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_type` int(11) DEFAULT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hu` double DEFAULT NULL,
  `meteringType` int(11) DEFAULT NULL,
  `period` double DEFAULT NULL,
  `tu` double DEFAULT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `supplier_id` int(11) NOT NULL,
  PRIMARY KEY (`yyyymmddhhmmss`,`dst`,`mdev_id`,`mdev_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
