CREATE TABLE `power_quality` (
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `yyyymmddhhmm` varchar(12) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` int(11) NOT NULL,
  `dst` int(11) NOT NULL DEFAULT 0,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hhmm` varchar(4) COLLATE utf8mb4_unicode_ci NOT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `device_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_type` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `vol_a` double DEFAULT NULL,
  `vol_b` double DEFAULT NULL,
  `vol_c` double DEFAULT NULL,
  `curr_a` double DEFAULT NULL,
  `curr_b` double DEFAULT NULL,
  `curr_c` double DEFAULT NULL,  
  `vol_angle_a` double DEFAULT NULL,
  `vol_angle_b` double DEFAULT NULL,
  `vol_angle_c` double DEFAULT NULL,
  `curr_angle_a` double DEFAULT NULL,
  `curr_angle_b` double DEFAULT NULL,
  `curr_angle_c` double DEFAULT NULL,
  `kw_a` double DEFAULT NULL,
  `kw_b` double DEFAULT NULL,
  `kw_c` double DEFAULT NULL,
  `kvar_a` double DEFAULT NULL,
  `kvar_b` double DEFAULT NULL,
  `kvar_c` double DEFAULT NULL,
  `kva_a` double DEFAULT NULL,
  `kva_b` double DEFAULT NULL,
  `kva_c` double DEFAULT NULL,
  `pf_a` double DEFAULT NULL,
  `pf_b` double DEFAULT NULL,
  `pf_c` double DEFAULT NULL,
  `pf_total` double DEFAULT NULL,
  `curr_1st_harmonic_mag_a` double DEFAULT NULL,
  `curr_1st_harmonic_mag_b` double DEFAULT NULL,
  `curr_1st_harmonic_mag_c` double DEFAULT NULL,
  `curr_2nd_harmonic_mag_a` double DEFAULT NULL,
  `curr_2nd_harmonic_mag_b` double DEFAULT NULL,
  `curr_2nd_harmonic_mag_c` double DEFAULT NULL,
  `curr_harmonic_a` double DEFAULT NULL,
  `curr_harmonic_b` double DEFAULT NULL,
  `curr_harmonic_c` double DEFAULT NULL,
  `curr_seq_n` double DEFAULT NULL,
  `curr_seq_p` double DEFAULT NULL,
  `curr_seq_z` double DEFAULT NULL,
  `curr_thd_a` double DEFAULT NULL,
  `curr_thd_b` double DEFAULT NULL,
  `curr_thd_c` double DEFAULT NULL,
  `distortion_kva_a` double DEFAULT NULL,
  `distortion_kva_b` double DEFAULT NULL,
  `distortion_kva_c` double DEFAULT NULL,
  `distortion_pf_a` double DEFAULT NULL,
  `distortion_pf_b` double DEFAULT NULL,
  `distortion_pf_c` double DEFAULT NULL,
  `distortion_pf_total` double DEFAULT NULL,
  `line_AB` double DEFAULT NULL,
  `line_BC` double DEFAULT NULL,
  `line_CA` double DEFAULT NULL,
  `line_frequency` double DEFAULT NULL,
  `ph_curr_pqm_a` double DEFAULT NULL,
  `ph_curr_pqm_b` double DEFAULT NULL,
  `ph_curr_pqm_c` double DEFAULT NULL,
  `ph_fund_curr_a` double DEFAULT NULL,
  `ph_fund_curr_b` double DEFAULT NULL,
  `ph_fund_curr_c` double DEFAULT NULL,
  `ph_fund_vol_a` double DEFAULT NULL,
  `ph_fund_vol_b` double DEFAULT NULL,
  `ph_fund_vol_c` double DEFAULT NULL,
  `ph_vol_pqm_a` double DEFAULT NULL,
  `ph_vol_pqm_b` double DEFAULT NULL,
  `ph_vol_pqm_c` double DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `system_pf_angle` double DEFAULT NULL,
  `tdd_a` double DEFAULT NULL,
  `tdd_b` double DEFAULT NULL,
  `tdd_c` double DEFAULT NULL,
  `vol_1st_harmonic_mag_a` double DEFAULT NULL,
  `vol_1st_harmonic_mag_b` double DEFAULT NULL,
  `vol_1st_harmonic_mag_c` double DEFAULT NULL,
  `vol_2nd_harmonic_a` double DEFAULT NULL,
  `vol_2nd_harmonic_b` double DEFAULT NULL,
  `vol_2nd_harmonic_c` double DEFAULT NULL,
  `vol_2nd_harmonic_mag_a` double DEFAULT NULL,
  `vol_2nd_harmonic_mag_b` double DEFAULT NULL,
  `vol_2nd_harmonic_mag_c` double DEFAULT NULL,
  `vol_seq_n` double DEFAULT NULL,
  `vol_seq_p` double DEFAULT NULL,
  `vol_seq_z` double DEFAULT NULL,
  `vol_thd_a` double DEFAULT NULL,
  `vol_thd_b` double DEFAULT NULL,
  `vol_thd_c` double DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
PARTITION BY RANGE COLUMNS(yyyymmddhhmm)
(
 PARTITION POWER_QUALITY_201909_01 VALUES LESS THAN ('201909110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201909_02 VALUES LESS THAN ('201909210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201909_03 VALUES LESS THAN ('201910010000') ENGINE=InnoDB, 
 PARTITION POWER_QUALITY_201910_01 VALUES LESS THAN ('201910110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201910_02 VALUES LESS THAN ('201910210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201910_03 VALUES LESS THAN ('201911010000') ENGINE=InnoDB, 
 PARTITION POWER_QUALITY_201911_01 VALUES LESS THAN ('201911110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201911_02 VALUES LESS THAN ('201911210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201911_03 VALUES LESS THAN ('201912010000') ENGINE=InnoDB, 
 PARTITION POWER_QUALITY_201912_01 VALUES LESS THAN ('201912110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201912_02 VALUES LESS THAN ('201912210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_201912_03 VALUES LESS THAN ('202001010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202001_01 VALUES LESS THAN ('202001110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202001_02 VALUES LESS THAN ('202001210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202001_03 VALUES LESS THAN ('202002010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202002_01 VALUES LESS THAN ('202002110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202002_02 VALUES LESS THAN ('202002210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202002_03 VALUES LESS THAN ('202003010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202003_01 VALUES LESS THAN ('202003110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202003_02 VALUES LESS THAN ('202003210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202003_03 VALUES LESS THAN ('202004010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202004_01 VALUES LESS THAN ('202004110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202004_02 VALUES LESS THAN ('202004210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202004_03 VALUES LESS THAN ('202005010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202005_01 VALUES LESS THAN ('202005110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202005_02 VALUES LESS THAN ('202005210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202005_03 VALUES LESS THAN ('202006010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202006_01 VALUES LESS THAN ('202006110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202006_02 VALUES LESS THAN ('202006210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202006_03 VALUES LESS THAN ('202007010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202007_01 VALUES LESS THAN ('202007110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202007_02 VALUES LESS THAN ('202007210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202007_03 VALUES LESS THAN ('202008010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202008_01 VALUES LESS THAN ('202008110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202008_02 VALUES LESS THAN ('202008210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202008_03 VALUES LESS THAN ('202009010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202009_01 VALUES LESS THAN ('202009110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202009_02 VALUES LESS THAN ('202009210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202009_03 VALUES LESS THAN ('202010010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202010_01 VALUES LESS THAN ('202010110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202010_02 VALUES LESS THAN ('202010210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202010_03 VALUES LESS THAN ('202011010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202011_01 VALUES LESS THAN ('202011110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202011_02 VALUES LESS THAN ('202011210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202011_03 VALUES LESS THAN ('202012010000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202012_01 VALUES LESS THAN ('202012110000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202012_02 VALUES LESS THAN ('202012210000') ENGINE=InnoDB,
 PARTITION POWER_QUALITY_202012_03 VALUES LESS THAN ('202101010000')  ENGINE=InnoDB
);


CREATE UNIQUE INDEX PK_POWER_QUALITY ON AIMIR.POWER_QUALITY (MDEV_ID, yyyymmddhhmm, MDEV_TYPE, DST);
ALTER TABLE POWER_QUALITY ADD CONSTRAINT PK_POWER_QUALITY PRIMARY KEY(MDEV_ID, yyyymmddhhmm, MDEV_TYPE, DST);




CREATE TABLE `power_quality_status` (
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` int(11) NOT NULL,
  `yyyymmddhhmmss` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `device_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `device_type` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `distortion_a_cnt` int(11) DEFAULT NULL,
  `distortion_a_dur` bigint(20) DEFAULT NULL,
  `distortion_b_cnt` int(11) DEFAULT NULL,
  `distortion_b_dur` bigint(20) DEFAULT NULL,
  `distortion_c_cnt` int(11) DEFAULT NULL,
  `distortion_c_dur` bigint(20) DEFAULT NULL,
  `distortion_cnt` int(11) DEFAULT NULL,
  `distortion_dur` bigint(20) DEFAULT NULL,
  `distortion_ing` bit(1) DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `harmonic_cnt` int(11) DEFAULT NULL,
  `harmonic_dur` bigint(20) DEFAULT NULL,
  `harmonic_ing` bit(1) DEFAULT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci NOT NULL,
  `high_frequency_cnt` int(11) DEFAULT NULL,
  `high_frequency_dur` bigint(20) DEFAULT NULL,
  `high_frequency_ing` bit(1) DEFAULT NULL,
  `high_neutral_curr_cnt` int(11) DEFAULT NULL,
  `high_neutral_curr_dur` bigint(20) DEFAULT NULL,
  `high_neutral_curr_ing` bit(1) DEFAULT NULL,
  `high_vol_cnt` int(11) DEFAULT NULL,
  `high_vol_dur` bigint(20) DEFAULT NULL,
  `high_vol_ing` bit(1) DEFAULT NULL,
  `imbalance_curr_cnt` int(11) DEFAULT NULL,
  `imbalance_curr_dur` bigint(20) DEFAULT NULL,
  `imbalance_curr_ing` bit(1) DEFAULT NULL,
  `imbalance_vol_cnt` int(11) DEFAULT NULL,
  `imbalance_vol_dur` bigint(20) DEFAULT NULL,
  `imbalance_vol_ing` bit(1) DEFAULT NULL,
  `low_curr_cnt` int(11) DEFAULT NULL,
  `low_curr_dur` bigint(20) DEFAULT NULL,
  `low_curr_ing` bit(1) DEFAULT NULL,
  `low_vol_cnt` int(11) DEFAULT NULL,
  `low_vol_dur` bigint(20) DEFAULT NULL,
  `low_vol_ing` bit(1) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `over_curr_cnt` int(11) DEFAULT NULL,
  `over_curr_dur` bigint(20) DEFAULT NULL,
  `over_curr_ing` bit(1) DEFAULT NULL,
  `pfactor_cnt` int(11) DEFAULT NULL,
  `pfactor_dur` bigint(20) DEFAULT NULL,
  `pfactor_ing` bit(1) DEFAULT NULL,
  `polarity_cross_phase_cnt` int(11) DEFAULT NULL,
  `polarity_cross_phase_dur` bigint(20) DEFAULT NULL,
  `polarity_cross_phase_ing` bit(1) DEFAULT NULL,
  `reverse_pwr_cnt` int(11) DEFAULT NULL,
  `reverse_pwr_dur` bigint(20) DEFAULT NULL,
  `reverse_pwr_ing` bit(1) DEFAULT NULL,
  `service_vol_cnt` int(11) DEFAULT NULL,
  `service_vol_dur` bigint(20) DEFAULT NULL,
  `service_vol_ing` bit(1) DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `tdd_cnt` int(11) DEFAULT NULL,
  `tdd_dur` bigint(20) DEFAULT NULL,
  `tdd_ing` bit(1) DEFAULT NULL,
  `thd_curr_cnt` int(11) DEFAULT NULL,
  `thd_curr_dur` bigint(20) DEFAULT NULL,
  `thd_curr_ing` bit(1) DEFAULT NULL,
  `thd_vol_cnt` int(11) DEFAULT NULL,
  `thd_vol_dur` bigint(20) DEFAULT NULL,
  `thd_vol_ing` bit(1) DEFAULT NULL,
  `vol_a_sag_cnt` int(11) DEFAULT NULL,
  `vol_a_sag_dur` bigint(20) DEFAULT NULL,
  `vol_a_swell_cnt` int(11) DEFAULT NULL,
  `vol_a_swell_dur` bigint(20) DEFAULT NULL,
  `vol_b_sag_cnt` int(11) DEFAULT NULL,
  `vol_b_sag_dur` bigint(20) DEFAULT NULL,
  `vol_b_swell_cnt` int(11) DEFAULT NULL,
  `vol_b_swell_dur` bigint(20) DEFAULT NULL,
  `vol_c_sag_cnt` int(11) DEFAULT NULL,
  `vol_c_sag_dur` bigint(20) DEFAULT NULL,
  `vol_c_swell_cnt` int(11) DEFAULT NULL,
  `vol_c_swell_dur` bigint(20) DEFAULT NULL,
  `vol_cut_cnt` int(11) DEFAULT NULL,
  `vol_cut_dur` bigint(20) DEFAULT NULL,
  `vol_cut_ing` bit(1) DEFAULT NULL,
  `vol_flicker_cnt` int(11) DEFAULT NULL,
  `vol_flicker_dur` bigint(20) DEFAULT NULL,
  `vol_flicker_ing` bit(1) DEFAULT NULL,
  `vol_fluctuation_cnt` int(11) DEFAULT NULL,
  `vol_fluctuation_dur` bigint(20) DEFAULT NULL,
  `vol_fluctuation_ing` bit(1) DEFAULT NULL,
  `vol_sag_cnt` int(11) DEFAULT NULL,
  `vol_sag_dur` bigint(20) DEFAULT NULL,
  `vol_sag_ing` bit(1) DEFAULT NULL,
  `vol_swell_cnt` int(11) DEFAULT NULL,
  `vol_swell_dur` bigint(20) DEFAULT NULL,
  `vol_swell_ing` bit(1) DEFAULT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci NOT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`mdev_id`,`mdev_type`,`yyyymmddhhmmss`) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;