CREATE TABLE `billing_day_em` (
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '000000',
  `mdev_type` int(11) NOT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `activeEnergyExportRate1` double DEFAULT NULL,
  `activeEnergyExportRate2` double DEFAULT NULL,
  `activeEnergyExportRate3` double DEFAULT NULL,
  `activeEnergyExportRate4` double DEFAULT NULL,
  `activeEnergyExportRateTotal` double DEFAULT NULL,
  `activeEnergyImportRate1` double DEFAULT NULL,
  `activeEnergyImportRate2` double DEFAULT NULL,
  `activeEnergyImportRate3` double DEFAULT NULL,
  `activeEnergyImportRate4` double DEFAULT NULL,
  `activeEnergyImportRateTotal` double DEFAULT NULL,
  `activeEnergyRate1` double DEFAULT NULL,
  `activeEnergyRate2` double DEFAULT NULL,
  `activeEnergyRate3` double DEFAULT NULL,
  `activeEnergyRate4` double DEFAULT NULL,
  `activeEnergyRateTot` double DEFAULT NULL,
  `activePwrDmdMaxTimeRate1` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate2` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate3` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate4` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRateTot` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrMaxDmdRate1` double DEFAULT NULL,
  `activePwrMaxDmdRate2` double DEFAULT NULL,
  `activePwrMaxDmdRate3` double DEFAULT NULL,
  `activePwrMaxDmdRate4` double DEFAULT NULL,
  `activePwrMaxDmdRateTot` double DEFAULT NULL,
  `activePwrDmdMaxExportRate1` double DEFAULT NULL,
  `activePwrDmdMaxExportRate2` double DEFAULT NULL,
  `activePwrDmdMaxExportRate3` double DEFAULT NULL,
  `activePwrDmdMaxExportRate4` double DEFAULT NULL,
  `activePwrDmdMaxExportRateTotal` double DEFAULT NULL,
  `activePwrDmdMaxImportRate1` double DEFAULT NULL,
  `activePwrDmdMaxImportRate2` double DEFAULT NULL,
  `activePwrDmdMaxImportRate3` double DEFAULT NULL,
  `activePwrDmdMaxImportRate4` double DEFAULT NULL,
  `activePwrDmdMaxImportRateTotal` double DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `atvPwrDmdMaxTimeExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `atvPwrDmdMaxTimeImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `additionalCosts` double DEFAULT NULL,
  `bill` double DEFAULT NULL,
  `CO2_EMISSIONS` double DEFAULT NULL,
  `co2Miles` double DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate1` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate2` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate3` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate4` double DEFAULT NULL,
  `cummAtvPwrDmdMaxExpRateTot` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate1` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate2` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate3` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate4` double DEFAULT NULL,
  `cummAtvPwrDmdMaxImpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRateTot` double DEFAULT NULL,
  `cummkVah1Rate1` double DEFAULT NULL,
  `cummkVah1Rate2` double DEFAULT NULL,
  `cummkVah1Rate3` double DEFAULT NULL,
  `cummkVah1Rate4` double DEFAULT NULL,
  `cummkVah1RateTotal` double DEFAULT NULL,
  `cummActivePwrDmdRate1` double DEFAULT NULL,
  `cummActivePwrDmdRate2` double DEFAULT NULL,
  `cummActivePwrDmdRate3` double DEFAULT NULL,
  `cummActivePwrDmdRate4` double DEFAULT NULL,
  `cummActivePwrDmdRateTot` double DEFAULT NULL,
  `cummReactivePwrDmdRate1` double DEFAULT NULL,
  `cummReactivePwrDmdRate2` double DEFAULT NULL,
  `cummReactivePwrDmdRate3` double DEFAULT NULL,
  `cummReactivePwrDmdRate4` double DEFAULT NULL,
  `cummReactivePwrDmdRateTot` double DEFAULT NULL,
  `discountedRates` double DEFAULT NULL,
  `importkWhPhaseA` double DEFAULT NULL,
  `importkWhPhaseB` double DEFAULT NULL,
  `importkWhPhaseC` double DEFAULT NULL,
  `kvah` double DEFAULT NULL,
  `maxDmdkVah1Rate1` double DEFAULT NULL,
  `maxDmdkVah1Rate2` double DEFAULT NULL,
  `maxDmdkVah1Rate3` double DEFAULT NULL,
  `maxDmdkVah1Rate4` double DEFAULT NULL,
  `maxDmdkVah1RateTotal` double DEFAULT NULL,
  `maxDmdkVah1TimeRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRateTotal` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `newMiles` double DEFAULT NULL,
  `pf` double DEFAULT NULL,
  `reactiveEnergyLagExportRate1` double DEFAULT NULL,
  `reactiveEnergyLagExportRate2` double DEFAULT NULL,
  `reactiveEnergyLagExportRate3` double DEFAULT NULL,
  `reactiveEnergyLagExportRate4` double DEFAULT NULL,
  `rtvEnergyLagExpRateTot` double DEFAULT NULL,
  `reactiveEnergyLagImportRate1` double DEFAULT NULL,
  `reactiveEnergyLagImportRate2` double DEFAULT NULL,
  `reactiveEnergyLagImportRate3` double DEFAULT NULL,
  `reactiveEnergyLagImportRate4` double DEFAULT NULL,
  `rtvEnergyLagImpRateTot` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate1` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate2` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate3` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate4` double DEFAULT NULL,
  `rtvEnergyLeadExpRateTot` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate1` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate2` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate3` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate4` double DEFAULT NULL,
  `rtvEnergyLeadImpRateTot` double DEFAULT NULL,
  `reactiveEnergyRate1` double DEFAULT NULL,
  `reactiveEnergyRate2` double DEFAULT NULL,
  `reactiveEnergyRate3` double DEFAULT NULL,
  `reactiveEnergyRate4` double DEFAULT NULL,
  `reactiveEnergyRateTot` double DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate1` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate2` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate3` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate4` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRateTot` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrMaxDmdRate1` double DEFAULT NULL,
  `reactivePwrMaxDmdRate2` double DEFAULT NULL,
  `reactivePwrMaxDmdRate3` double DEFAULT NULL,
  `reactivePwrMaxDmdRate4` double DEFAULT NULL,
  `reactivePwrMaxDmdRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remainingmiles` double DEFAULT NULL,
  `SEND_RESULT` bit(1) DEFAULT NULL,
  `USAGE_READ_FROM_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USAGE_READ_TO_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `usingMiles` double DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL
) ENGINE=InnoDB 
PARTITION BY RANGE COLUMNS(yyyymmdd)
(
 PARTITION BILLING_DAY_EM_201909 VALUES LESS THAN ('20190930') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_201910 VALUES LESS THAN ('20191031') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_201911 VALUES LESS THAN ('20191130') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_201912 VALUES LESS THAN ('20191231') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202001 VALUES LESS THAN ('20200131') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202002 VALUES LESS THAN ('20200229') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202003 VALUES LESS THAN ('20200331') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202004 VALUES LESS THAN ('20200430') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202005 VALUES LESS THAN ('20200531') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202006 VALUES LESS THAN ('20200631') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202007 VALUES LESS THAN ('20200731') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202008 VALUES LESS THAN ('20200831') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202009 VALUES LESS THAN ('20200930') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202010 VALUES LESS THAN ('20201031') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202011 VALUES LESS THAN ('20201130') ENGINE=InnoDB,
 PARTITION BILLING_DAY_EM_202012 VALUES LESS THAN ('20201231') ENGINE=InnoDB
 );
 
CREATE UNIQUE INDEX PK_BILLING_DAY_EM ON AIMIR.BILLING_DAY_EM (`mdev_id`,`yyyymmdd`,`hhmmss`,`mdev_type`);
ALTER TABLE BILLING_DAY_EM ADD CONSTRAINT PK_BILLING_DAY_EM PRIMARY KEY(`mdev_id`,`yyyymmdd`,`hhmmss`,`mdev_type`);



CREATE TABLE `billing_month_em` (
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '000000',
  `mdev_type` int(11) NOT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `activeEnergyExportRate1` double DEFAULT NULL,
  `activeEnergyExportRate2` double DEFAULT NULL,
  `activeEnergyExportRate3` double DEFAULT NULL,
  `activeEnergyExportRate4` double DEFAULT NULL,
  `activeEnergyExportRateTotal` double DEFAULT NULL,
  `activeEnergyImportRate1` double DEFAULT NULL,
  `activeEnergyImportRate2` double DEFAULT NULL,
  `activeEnergyImportRate3` double DEFAULT NULL,
  `activeEnergyImportRate4` double DEFAULT NULL,
  `activeEnergyImportRateTotal` double DEFAULT NULL,
  `activeEnergyRate1` double DEFAULT NULL,
  `activeEnergyRate2` double DEFAULT NULL,
  `activeEnergyRate3` double DEFAULT NULL,
  `activeEnergyRate4` double DEFAULT NULL,
  `activeEnergyRateTot` double DEFAULT NULL,
  `activePwrDmdMaxTimeRate1` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate2` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate3` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate4` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRateTot` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrMaxDmdRate1` double DEFAULT NULL,
  `activePwrMaxDmdRate2` double DEFAULT NULL,
  `activePwrMaxDmdRate3` double DEFAULT NULL,
  `activePwrMaxDmdRate4` double DEFAULT NULL,
  `activePwrMaxDmdRateTot` double DEFAULT NULL,
  `activePwrDmdMaxExportRate1` double DEFAULT NULL,
  `activePwrDmdMaxExportRate2` double DEFAULT NULL,
  `activePwrDmdMaxExportRate3` double DEFAULT NULL,
  `activePwrDmdMaxExportRate4` double DEFAULT NULL,
  `activePwrDmdMaxExportRateTotal` double DEFAULT NULL,
  `activePwrDmdMaxImportRate1` double DEFAULT NULL,
  `activePwrDmdMaxImportRate2` double DEFAULT NULL,
  `activePwrDmdMaxImportRate3` double DEFAULT NULL,
  `activePwrDmdMaxImportRate4` double DEFAULT NULL,
  `activePwrDmdMaxImportRateTotal` double DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `atvPwrDmdMaxTimeExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `atvPwrDmdMaxTimeImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `additionalCosts` double DEFAULT NULL,
  `bill` double DEFAULT NULL,
  `CO2_EMISSIONS` double DEFAULT NULL,
  `co2Miles` double DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate1` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate2` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate3` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate4` double DEFAULT NULL,
  `cummAtvPwrDmdMaxExpRateTot` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate1` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate2` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate3` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate4` double DEFAULT NULL,
  `cummAtvPwrDmdMaxImpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRateTot` double DEFAULT NULL,
  `cummkVah1Rate1` double DEFAULT NULL,
  `cummkVah1Rate2` double DEFAULT NULL,
  `cummkVah1Rate3` double DEFAULT NULL,
  `cummkVah1Rate4` double DEFAULT NULL,
  `cummkVah1RateTotal` double DEFAULT NULL,
  `cummActivePwrDmdRate1` double DEFAULT NULL,
  `cummActivePwrDmdRate2` double DEFAULT NULL,
  `cummActivePwrDmdRate3` double DEFAULT NULL,
  `cummActivePwrDmdRate4` double DEFAULT NULL,
  `cummActivePwrDmdRateTot` double DEFAULT NULL,
  `cummReactivePwrDmdRate1` double DEFAULT NULL,
  `cummReactivePwrDmdRate2` double DEFAULT NULL,
  `cummReactivePwrDmdRate3` double DEFAULT NULL,
  `cummReactivePwrDmdRate4` double DEFAULT NULL,
  `cummReactivePwrDmdRateTot` double DEFAULT NULL,
  `discountedRates` double DEFAULT NULL,
  `importkWhPhaseA` double DEFAULT NULL,
  `importkWhPhaseB` double DEFAULT NULL,
  `importkWhPhaseC` double DEFAULT NULL,
  `kvah` double DEFAULT NULL,
  `maxDmdkVah1Rate1` double DEFAULT NULL,
  `maxDmdkVah1Rate2` double DEFAULT NULL,
  `maxDmdkVah1Rate3` double DEFAULT NULL,
  `maxDmdkVah1Rate4` double DEFAULT NULL,
  `maxDmdkVah1RateTotal` double DEFAULT NULL,
  `maxDmdkVah1TimeRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRateTotal` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `newMiles` double DEFAULT NULL,
  `pf` double DEFAULT NULL,
  `reactiveEnergyLagExportRate1` double DEFAULT NULL,
  `reactiveEnergyLagExportRate2` double DEFAULT NULL,
  `reactiveEnergyLagExportRate3` double DEFAULT NULL,
  `reactiveEnergyLagExportRate4` double DEFAULT NULL,
  `rtvEnergyLagExpRateTot` double DEFAULT NULL,
  `reactiveEnergyLagImportRate1` double DEFAULT NULL,
  `reactiveEnergyLagImportRate2` double DEFAULT NULL,
  `reactiveEnergyLagImportRate3` double DEFAULT NULL,
  `reactiveEnergyLagImportRate4` double DEFAULT NULL,
  `rtvEnergyLagImpRateTot` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate1` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate2` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate3` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate4` double DEFAULT NULL,
  `rtvEnergyLeadExpRateTot` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate1` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate2` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate3` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate4` double DEFAULT NULL,
  `rtvEnergyLeadImpRateTot` double DEFAULT NULL,
  `reactiveEnergyRate1` double DEFAULT NULL,
  `reactiveEnergyRate2` double DEFAULT NULL,
  `reactiveEnergyRate3` double DEFAULT NULL,
  `reactiveEnergyRate4` double DEFAULT NULL,
  `reactiveEnergyRateTot` double DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate1` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate2` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate3` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate4` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRateTot` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrMaxDmdRate1` double DEFAULT NULL,
  `reactivePwrMaxDmdRate2` double DEFAULT NULL,
  `reactivePwrMaxDmdRate3` double DEFAULT NULL,
  `reactivePwrMaxDmdRate4` double DEFAULT NULL,
  `reactivePwrMaxDmdRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remainingmiles` double DEFAULT NULL,
  `SEND_RESULT` bit(1) DEFAULT NULL,
  `USAGE_READ_FROM_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USAGE_READ_TO_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `usingMiles` double DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL
) ENGINE=InnoDB 
PARTITION BY RANGE COLUMNS(yyyymmdd)
(
 PARTITION BILLING_MONTH_EM_2019 VALUES LESS THAN ('20200101') ENGINE=InnoDB,
 PARTITION BILLING_MONTH_EM_2020 VALUES LESS THAN ('20210101') ENGINE=InnoDB,
 PARTITION BILLING_MONTH_EM_2021 VALUES LESS THAN ('20220101') ENGINE=InnoDB
 );
 
CREATE UNIQUE INDEX PK_BILLING_MONTH_EM ON AIMIR.BILLING_MONTH_EM (`mdev_id`,`yyyymmdd`,`hhmmss`,`mdev_type`);
ALTER TABLE BILLING_MONTH_EM ADD CONSTRAINT PK_BILLING_MONTH_EM PRIMARY KEY(`mdev_id`,`yyyymmdd`,`hhmmss`,`mdev_type`);

CREATE TABLE `realtime_billing_em` (
  `hhmmss` varchar(6) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '000000',
  `mdev_id` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `mdev_type` int(11) NOT NULL,
  `yyyymmdd` varchar(8) COLLATE utf8mb4_unicode_ci NOT NULL,
  `activeEnergyExportRate1` double DEFAULT NULL,
  `activeEnergyExportRate2` double DEFAULT NULL,
  `activeEnergyExportRate3` double DEFAULT NULL,
  `activeEnergyExportRate4` double DEFAULT NULL,
  `activeEnergyExportRateTotal` double DEFAULT NULL,
  `activeEnergyImportRate1` double DEFAULT NULL,
  `activeEnergyImportRate2` double DEFAULT NULL,
  `activeEnergyImportRate3` double DEFAULT NULL,
  `activeEnergyImportRate4` double DEFAULT NULL,
  `activeEnergyImportRateTotal` double DEFAULT NULL,
  `activeEnergyRate1` double DEFAULT NULL,
  `activeEnergyRate2` double DEFAULT NULL,
  `activeEnergyRate3` double DEFAULT NULL,
  `activeEnergyRate4` double DEFAULT NULL,
  `activeEnergyRateTot` double DEFAULT NULL,
  `activePwrDmdMaxTimeRate1` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate2` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate3` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRate4` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeRateTot` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrMaxDmdRate1` double DEFAULT NULL,
  `activePwrMaxDmdRate2` double DEFAULT NULL,
  `activePwrMaxDmdRate3` double DEFAULT NULL,
  `activePwrMaxDmdRate4` double DEFAULT NULL,
  `activePwrMaxDmdRateTot` double DEFAULT NULL,
  `activePwrDmdMaxExportRate1` double DEFAULT NULL,
  `activePwrDmdMaxExportRate2` double DEFAULT NULL,
  `activePwrDmdMaxExportRate3` double DEFAULT NULL,
  `activePwrDmdMaxExportRate4` double DEFAULT NULL,
  `activePwrDmdMaxExportRateTotal` double DEFAULT NULL,
  `activePwrDmdMaxImportRate1` double DEFAULT NULL,
  `activePwrDmdMaxImportRate2` double DEFAULT NULL,
  `activePwrDmdMaxImportRate3` double DEFAULT NULL,
  `activePwrDmdMaxImportRate4` double DEFAULT NULL,
  `activePwrDmdMaxImportRateTotal` double DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeExportRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `atvPwrDmdMaxTimeExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activePwrDmdMaxTimeImportRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `atvPwrDmdMaxTimeImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `additionalCosts` double DEFAULT NULL,
  `bill` double DEFAULT NULL,
  `CO2_EMISSIONS` double DEFAULT NULL,
  `co2Miles` double DEFAULT NULL,
  `contract_id` int(11) DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate1` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate2` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate3` double DEFAULT NULL,
  `cummActivePwrDmdMaxExportRate4` double DEFAULT NULL,
  `cummAtvPwrDmdMaxExpRateTot` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate1` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate2` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate3` double DEFAULT NULL,
  `cummActivePwrDmdMaxImportRate4` double DEFAULT NULL,
  `cummAtvPwrDmdMaxImpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagExpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLagImpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadExpRateTot` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate1` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate2` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate3` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRate4` double DEFAULT NULL,
  `cummRtvPwrDmdMaxLeadImpRateTot` double DEFAULT NULL,
  `cummkVah1Rate1` double DEFAULT NULL,
  `cummkVah1Rate2` double DEFAULT NULL,
  `cummkVah1Rate3` double DEFAULT NULL,
  `cummkVah1Rate4` double DEFAULT NULL,
  `cummkVah1RateTotal` double DEFAULT NULL,
  `cummActivePwrDmdRate1` double DEFAULT NULL,
  `cummActivePwrDmdRate2` double DEFAULT NULL,
  `cummActivePwrDmdRate3` double DEFAULT NULL,
  `cummActivePwrDmdRate4` double DEFAULT NULL,
  `cummActivePwrDmdRateTot` double DEFAULT NULL,
  `cummReactivePwrDmdRate1` double DEFAULT NULL,
  `cummReactivePwrDmdRate2` double DEFAULT NULL,
  `cummReactivePwrDmdRate3` double DEFAULT NULL,
  `cummReactivePwrDmdRate4` double DEFAULT NULL,
  `cummReactivePwrDmdRateTot` double DEFAULT NULL,
  `discountedRates` double DEFAULT NULL,
  `enddevice_id` int(11) DEFAULT NULL,
  `importkWhPhaseA` double DEFAULT NULL,
  `importkWhPhaseB` double DEFAULT NULL,
  `importkWhPhaseC` double DEFAULT NULL,
  `kvah` double DEFAULT NULL,
  `location_id` int(11) DEFAULT NULL,
  `maxDmdkVah1Rate1` double DEFAULT NULL,
  `maxDmdkVah1Rate2` double DEFAULT NULL,
  `maxDmdkVah1Rate3` double DEFAULT NULL,
  `maxDmdkVah1Rate4` double DEFAULT NULL,
  `maxDmdkVah1RateTotal` double DEFAULT NULL,
  `maxDmdkVah1TimeRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `maxDmdkVah1TimeRateTotal` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meter_id` int(11) DEFAULT NULL,
  `modem_id` int(11) DEFAULT NULL,
  `newMiles` double DEFAULT NULL,
  `pf` double DEFAULT NULL,
  `reactiveEnergyLagExportRate1` double DEFAULT NULL,
  `reactiveEnergyLagExportRate2` double DEFAULT NULL,
  `reactiveEnergyLagExportRate3` double DEFAULT NULL,
  `reactiveEnergyLagExportRate4` double DEFAULT NULL,
  `rtvEnergyLagExpRateTot` double DEFAULT NULL,
  `reactiveEnergyLagImportRate1` double DEFAULT NULL,
  `reactiveEnergyLagImportRate2` double DEFAULT NULL,
  `reactiveEnergyLagImportRate3` double DEFAULT NULL,
  `reactiveEnergyLagImportRate4` double DEFAULT NULL,
  `rtvEnergyLagImpRateTot` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate1` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate2` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate3` double DEFAULT NULL,
  `reactiveEnergyLeadExportRate4` double DEFAULT NULL,
  `rtvEnergyLeadExpRateTot` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate1` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate2` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate3` double DEFAULT NULL,
  `reactiveEnergyLeadImportRate4` double DEFAULT NULL,
  `rtvEnergyLeadImpRateTot` double DEFAULT NULL,
  `reactiveEnergyRate1` double DEFAULT NULL,
  `reactiveEnergyRate2` double DEFAULT NULL,
  `reactiveEnergyRate3` double DEFAULT NULL,
  `reactiveEnergyRate4` double DEFAULT NULL,
  `reactiveEnergyRateTot` double DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate1` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate2` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate3` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRate4` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrDmdMaxTimeRateTot` varchar(12) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `reactivePwrMaxDmdRate1` double DEFAULT NULL,
  `reactivePwrMaxDmdRate2` double DEFAULT NULL,
  `reactivePwrMaxDmdRate3` double DEFAULT NULL,
  `reactivePwrMaxDmdRate4` double DEFAULT NULL,
  `reactivePwrMaxDmdRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLagExpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLagImpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadExpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate1` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate2` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate3` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRate4` double DEFAULT NULL,
  `rtvPwrDmdMaxLeadImpRateTot` double DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLagImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadExpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate1` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate2` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate3` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRate4` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `rtvPwrDmdMaxTimeLeadImpRateTot` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `remainingmiles` double DEFAULT NULL,
  `SEND_RESULT` bit(1) DEFAULT NULL,
  `supplier_id` int(11) DEFAULT NULL,
  `USAGE_READ_FROM_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `USAGE_READ_TO_DATE` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `usingMiles` double DEFAULT NULL,
  `writeDate` varchar(14) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`hhmmss`,`mdev_id`,`mdev_type`,`yyyymmdd`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;





