CREATE OR REPLACE TRIGGER AIMIR.TRI_DAY_EM
AFTER INSERT OR UPDATE ON AIMIR.LP_EM  
FOR EACH ROW  
  
BEGIN   
  
MERGE INTO AIMIR.LPEM_TO_DAYEM USING DUAL   
  ON (MDEV_ID = :NEW.MDEV_ID AND YYYYMMDDHHMISS = :NEW.YYYYMMDDHHMISS AND CHANNEL = :NEW.CHANNEL AND MDEV_TYPE = :NEW.MDEV_TYPE AND DST = :NEW.DST)  
WHEN MATCHED THEN UPDATE SET WRITEDATE = :NEW.WRITEDATE
WHEN NOT MATCHED THEN INSERT SELECT (:NEW.MDEV_ID, :NEW.YYYYMMDDHHMISS, :NEW.CHANNEL, :NEW.MDEV_TYPE, :NEW.DST, :NEW.WRITEDATE);  
                                
END;
