DROP TABLE AIMIR.MONTH_EM;
CREATE TABLE AIMIR.MONTH_EM
(
MDEV_ID VARCHAR(20) NOT NULL,
YYYYMM VARCHAR(6) NOT NULL,
CHANNEL VARCHAR(3) NOT NULL,
MDEV_TYPE VARCHAR(20) NOT NULL,
DST DECIMAL(38) NOT NULL,
DD VARCHAR(2) NOT NULL,
METER_ID BIGINT,
METERINGTYPE TINYINT,
MDEV_ID_LAST TINYINT,
MODEM_ID BIGINT,
DEVICE_ID VARCHAR(20),
DEVICE_TYPE VARCHAR(15),
C_VALUE BIGINT,
BASEVALUE DECIMAL(19, 4),
VALUE DECIMAL(19, 4),
WRITEDATE VARCHAR(14),
SUPPLIER_ID BIGINT,
CH_METHOD VARCHAR(255),
CONTRACT_ID BIGINT,
ENDDEVICE_ID BIGINT
);
CREATE INDEX AIMIR.PK_MONTH_EM ON AIMIR.MONTH_EM (MDEV_ID, YYYYMM, CHANNEL, MDEV_TYPE, DST, DD);
ALTER TABLE AIMIR.MONTH_EM ADD CONSTRAINT PK_MONTH_EM PRIMARY KEY (MDEV_ID, YYYYMM, CHANNEL, MDEV_TYPE, DST, DD);
