CREATE TABLE LPEM_TO_DAYEM
(
    MDEV_ID         VARCHAR(20) NOT NULL,
    YYYYMMDDHHMISS  VARCHAR(14) NOT NULL,
    CHANNEL         SMALLINT NOT NULL,
    MDEV_TYPE       VARCHAR(20) NOT NULL,
    DST             TINYINT DEFAULT 0 NOT NULL,
    WRITEDATE       VARCHAR(14)
);
CREATE INDEX IDX_LPEM_TO_DAYEM ON LPEM_TO_DAYEM(MDEV_ID, YYYYMMDDHHMISS, CHANNEL, MDEV_TYPE, DST);