CREATE TABLE AIMIR.LPEM_TO_DAYEM
(
    MDEV_ID         VARCHAR(20) NOT NULL,
    YYYYMMDDHHMISS  VARCHAR(14) NOT NULL,
    CHANNEL         SMALLINT NOT NULL,
    MDEV_TYPE       VARCHAR(20) NOT NULL,
    DST             DECIMAL(38) DEFAULT 0 NOT NULL,
    WRITEDATE       VARCHAR(14)
);
CREATE INDEX AIMIR.IDX_LPEM_TO_DAYEM ON AIMIR.LPEM_TO_DAYEM(MDEV_ID, YYYYMMDDHHMISS, CHANNEL, MDEV_TYPE, DST);