CREATE OR REPLACE VIEW AIMIR.DAY_EM_VIEW AS
SELECT MDEV_ID, YYYYMMDD, CHANNEL, MDEV_TYPE, DST, METER_ID, METERINGTYPE, MDEV_ID_LAST, MODEM_ID, DEVICE_ID, DEVICE_TYPE, WRITEDATE, SUPPLIER_ID, CONTRACT_ID, ENDDEVICE_ID, C_VALUE, 
BASEVALUE, TOTAL_VALUE, VALUE_00, VALUE_01, VALUE_02, VALUE_03, VALUE_04, VALUE_05, VALUE_06, VALUE_07, VALUE_08, VALUE_09, VALUE_10, VALUE_11, VALUE_12, VALUE_13,   
VALUE_14, VALUE_15, VALUE_16, VALUE_17, VALUE_18, VALUE_19, VALUE_20, VALUE_21, VALUE_22, VALUE_23 FROM  
(SELECT MDEV_ID, YYYYMMDD, CHANNEL, MDEV_TYPE, DST, METER_ID, METERINGTYPE, MDEV_ID_LAST, MODEM_ID, DEVICE_ID, DEVICE_TYPE, CH_METHOD, MIN(WRITEDATE) WRITEDATE, SUPPLIER_ID, CONTRACT_ID, ENDDEVICE_ID, SUM(C_VALUE) C_VALUE,  
BASEVALUE, CASE WHEN CH_METHOD = 'MAX' THEN MAX(TOTAL_VALUE) WHEN CH_METHOD = 'SUM' THEN SUM(TOTAL_VALUE) WHEN CH_METHOD = 'AVG' THEN AVG(TOTAL_VALUE) END TOTAL_VALUE,  
MAX(VALUE_00) VALUE_00, MAX(VALUE_01) VALUE_01, MAX(VALUE_02) VALUE_02, MAX(VALUE_03) VALUE_03, MAX(VALUE_04) VALUE_04, MAX(VALUE_05) VALUE_05, MAX(VALUE_06) VALUE_06, MAX(VALUE_07) VALUE_07,  
MAX(VALUE_08) VALUE_08, MAX(VALUE_09) VALUE_09, MAX(VALUE_10) VALUE_10, MAX(VALUE_11) VALUE_11, MAX(VALUE_12) VALUE_12, MAX(VALUE_13) VALUE_13, MAX(VALUE_14) VALUE_14, MAX(VALUE_15) VALUE_15,  
MAX(VALUE_16) VALUE_16, MAX(VALUE_17) VALUE_17, MAX(VALUE_18) VALUE_18, MAX(VALUE_19) VALUE_19, MAX(VALUE_20) VALUE_20, MAX(VALUE_21) VALUE_21, MAX(VALUE_22) VALUE_22, MAX(VALUE_23) VALUE_23  
FROM (SELECT MDEV_ID, YYYYMMDD, CHANNEL, MDEV_TYPE, DST, METER_ID, METERINGTYPE, MDEV_ID_LAST, MODEM_ID, DEVICE_ID, DEVICE_TYPE, CH_METHOD, WRITEDATE, SUPPLIER_ID, CONTRACT_ID, ENDDEVICE_ID, C_VALUE, 
BASEVALUE, VALUE TOTAL_VALUE,  
CASE WHEN HH = '00' THEN VALUE ELSE NULL END VALUE_00, CASE WHEN HH = '01' THEN VALUE ELSE NULL END VALUE_01, CASE WHEN HH = '02' THEN VALUE ELSE NULL END VALUE_02, CASE WHEN HH = '03' THEN VALUE ELSE NULL END VALUE_03,  
CASE WHEN HH = '04' THEN VALUE ELSE NULL END VALUE_04, CASE WHEN HH = '05' THEN VALUE ELSE NULL END VALUE_05, CASE WHEN HH = '06' THEN VALUE ELSE NULL END VALUE_06, CASE WHEN HH = '07' THEN VALUE ELSE NULL END VALUE_07,  
CASE WHEN HH = '08' THEN VALUE ELSE NULL END VALUE_08, CASE WHEN HH = '09' THEN VALUE ELSE NULL END VALUE_09, CASE WHEN HH = '10' THEN VALUE ELSE NULL END VALUE_10, CASE WHEN HH = '11' THEN VALUE ELSE NULL END VALUE_11,  
CASE WHEN HH = '12' THEN VALUE ELSE NULL END VALUE_12, CASE WHEN HH = '13' THEN VALUE ELSE NULL END VALUE_13, CASE WHEN HH = '14' THEN VALUE ELSE NULL END VALUE_14, CASE WHEN HH = '15' THEN VALUE ELSE NULL END VALUE_15,  
CASE WHEN HH = '16' THEN VALUE ELSE NULL END VALUE_16, CASE WHEN HH = '17' THEN VALUE ELSE NULL END VALUE_17, CASE WHEN HH = '18' THEN VALUE ELSE NULL END VALUE_18, CASE WHEN HH = '19' THEN VALUE ELSE NULL END VALUE_19,  
CASE WHEN HH = '20' THEN VALUE ELSE NULL END VALUE_20, CASE WHEN HH = '21' THEN VALUE ELSE NULL END VALUE_21, CASE WHEN HH = '22' THEN VALUE ELSE NULL END VALUE_22, CASE WHEN HH = '23' THEN VALUE ELSE NULL END VALUE_23  
FROM AIMIR.DAY_EM) GROUP BY MDEV_ID, YYYYMMDD, CHANNEL, MDEV_TYPE, DST, METER_ID, METERINGTYPE, MDEV_ID_LAST, MODEM_ID, DEVICE_ID, DEVICE_TYPE, CH_METHOD, SUPPLIER_ID, CONTRACT_ID, ENDDEVICE_ID, BASEVALUE);
