CREATE TABLE AIMIR.DAYEM_TO_MONTHEM
(
MDEV_ID VARCHAR(20) NOT NULL,
YYYYMMDD VARCHAR(8) NOT NULL,
CHANNEL VARCHAR(3) NOT NULL,
MDEV_TYPE VARCHAR(20) NOT NULL,
DST DECIMAL(38) NOT NULL,
HH VARCHAR(2) NOT NULL,
WRITEDATE VARCHAR(14)
);
CREATE INDEX AIMIR.IDX_DAYEM_TO_MONTHEM ON AIMIR.DAYEM_TO_MONTHEM(MDEV_ID, YYYYMMDD, CHANNEL, MDEV_TYPE, DST, HH);
