
package com.aimir.service.system.impl.demandResponseMgmt.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.aimir.service.system.impl.demandResponseMgmt.eventstate.EventStateConfirmation;
import com.aimir.service.system.impl.demandResponseMgmt.eventstate.ListOfEventStates;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DRASClientSOAP", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/")
@XmlSeeAlso({
	com.aimir.service.system.impl.demandResponseMgmt.eventstate.ObjectFactory.class,
	com.aimir.service.system.impl.demandResponseMgmt.soap.ObjectFactory.class
})
public interface DRASClientSOAP {


    /**
     * 
     * @param returnValue
     * @param empty
     * @param eventStates
     */
    @WebMethod(operationName = "GetEventStates", action = "http://www.openadr.org/DRAS/DRASClientSOAP/GetEventStates")
    @RequestWrapper(localName = "GetEventStates", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.GetEventStates")
    @ResponseWrapper(localName = "GetEventStatesResponse", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.GetEventStatesResponse")
    public void getEventStates(
        @WebParam(name = "empty", targetNamespace = "")
        Object empty,
        @WebParam(name = "returnValue", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> returnValue,
        @WebParam(name = "eventStates", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ListOfEventStates> eventStates);

    /**
     * 
     * @param eventStateConfirmation
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SetEventStateConfirmation", action = "http://www.openadr.org/DRAS/DRASClientSOAP/SetEventStateConfirmation")
    @WebResult(name = "returnValue", targetNamespace = "")
    @RequestWrapper(localName = "SetEventStateConfirmation", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.SetEventStateConfirmation")
    @ResponseWrapper(localName = "SetEventStateConfirmationResponse", targetNamespace = "http://www.openadr.org/DRAS/DRASClientSOAP/", className = "org.openadr.dras.drasclientsoap.SetEventStateConfirmationResponse")
    public String setEventStateConfirmation(
        @WebParam(name = "eventStateConfirmation", targetNamespace = "")
        EventStateConfirmation eventStateConfirmation);

}
