pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["2__gadget.htm","Gadget","Gadget Top Previous Next AIMIR v3.0 Manual Gadget based on a motive of iGoogle has formed of an inactive mode, abbreviated screen (Mini Gadget), t...",""],
["3__dashboard_and_gadget_manage.htm","Dashboard &#38; Gadget settings","Dashboard &#38; Gadget settings Top Previous Next AIMIR v3.0 Manual You can set The Dash Screen and Gadget by clicking Gadget Setting Button on the ab...",""],
["4__help.htm","4. Help","Help Top Previous Next AIMIR v3.0 Manual Help Screen provides description of AiMiR 3.0 and help information of each Gadget. You can see all help p...",""],
["chapter_2.htm","Introduction of AiMiR","Introduction of AiMiR Top Next AIMIR v3.0 Manual Copyrights and Trademarks AIMIR&#174; is a registered mark of NURI Telecom. Co., Ltd. User Notice The ...",""],
["dash_board.htm","Dashboard","Dashboard Top Previous Next AIMIR v3.0 Manual Dashboard is the user interface (UI) to manage a variety of information in one place. AiMiR 3.0 prov...",""],
["device_dashboard.htm","Device Management","Device Management Top Previous Next AIMIR v3.0 Manual Gadget description of Various Type such as equipment and career management are embodied in t...",""],
["gadget_device002.htm","Modem Management","Modem Management Top Previous Next AIMIR v3.0 Manual Providing not only the functions of Modem type, region, the communication state management bu...",""],
["gadget_device003.htm","Meter Management","Meter Management Top Previous Next AIMIR v3.0 Manual Providing Electricity, gas, water and heat meters, associated device information, metering da...",""],
["gadget_device004.htm","Equipment Register","Equipment Register Top Previous Next AIMIR v3.0 Manual The function of Individual and bulk registration for equipment. History management for a re...",""],
["gadget_device005.htm","Event and Alarm","Event and Alarm Top Previous Next AIMIR v3.0 Manual Providing view of whole events in real time, event query and view settings of the event. Mini ...",""],
["gadget_device006.htm","Communication History Management","Communication History Management Top Previous Next AIMIR v3.0 Manual Providing the information of Communications type as per equipment, communicat...",""],
["gadget_device007.htm","미터 시간관리","Meter Time Management Top Previous Next AIMIR v3.0 Manual Providing the error information between meter and the server time, the history of meter ...",""],
["gadget_device008.htm","장비 맵 관리","Equipment Map Management Top Previous Next AIMIR v3.0 Manual Providing a display function about the location with Google Map services by using add...",""],
["gadget_device009.htm","Power Management","Power Management Top Previous Next AIMIR v3.0 Manual Providing Histories of the power meter, duration, repair, long-term power outage, a brief pow...",""],
["gadget_device010.htm","Circuit Breaker Management","Circuit Breaker Management Top Previous Next AIMIR v3.0 Manual Mini Gadget Max Gadget ",""],
["gadget_device011.htm","Battery Management","Battery Management Top Previous AIMIR v3.0 Manual This gadget provides a search function to check missed data and state. Mini Gadget Max Gadget ",""],
["gadget_device013.htm","Meter Event Log","Meter Event Log Top Previous Next AIMIR v3.0 Manual Summarizing data information of warning, error and checking historical information of meter ev...",""],
["gadget_metering001.htm","Metering Data(Electricity)","Metering Data(Electricity) Top Previous Next AIMIR v3.0 Manual Mini Gadget The user can search and check the metering data by location. Max Gadget...",""],
["gadget_metering005.htm","Metering Fail(Electricity)","Metering Fail(Electricity) Top Previous Next AIMIR v3.0 Manual Mini Gadget Max Gadget Providing Excel output function Providing statistics and cau...",""],
["gadget_metering006.htm","Metering Fail(Heat)","Metering Fail(Heat) Top Previous Next AIMIR v3.0 Manual Mini Gadget Max Gadget Providing Excel output function Providing statistics and causes of ...",""],
["gadget_metering007.htm","Metering Fail(Gas)","Metering Fail(Gas) Top Previous Next AIMIR v3.0 Manual Mini Gadget Max Gadget Providing Excel output function Providing statistics and causes of f...",""],
["gadget_metering008.htm","Data Gaps(Electricity)","Data Gaps(Electricity) Top Previous Next AIMIR v3.0 Manual This gadget provides a search function to check missed data and state. Mini Gadget Max ...",""],
["gadget_metering008_water.htm","Metering Fail(Water)","Metering Fail(Water) Top Previous Next AIMIR v3.0 Manual Mini Gadget Max Gadget Providing Excel output function Providing statistics and causes of...",""],
["gadget_metering009.htm","Data Gaps(Gas)","Data Gaps(Gas) Top Previous Next AIMIR v3.0 Manual This gadget provides a search function to check missed data and state. Mini Gadget Max Gadget ",""],
["gadget_metering010.htm","Data Gaps(Water)","Data Gaps(Water) Top Previous Next AIMIR v3.0 Manual This gadget provides a search function to check missed data and state. Mini Gadget Max Gadget ",""],
["gadget_metering012.htm","Consumption Ranking(Electricity)","Consumption Ranking(Electricity) Top Previous Next AIMIR v3.0 Manual This gadget provides ranking of energy usage by separating energy type. You c...",""],
["gadget_metering016.htm","Billing Data (Electricity)","Billing Data (Electricity) Top Previous Next AIMIR v3.0 Manual Mini Gadget Max Gadget ",""],
["gadget_metering020.htm","Demand Management","Demand Management Top Previous Next AIMIR v3.0 Manual Demand Side Management is the various activities of electric power company to drive customer...",""],
["gadget_metering021.htm","PQ데이터관리","PQ Data Management Top Previous Next AIMIR v3.0 Manual Providing information of Electric Power Quality(Voltage, Current) , Voltage Level, Voltage ...",""],
["gadget_metering022.htm","Metering SLA","Metering SLA Top Previous Next AIMIR v3.0 Manual This gadget provides the rate of the success and analysis about metering data. Mini Gadget Max Ga...",""],
["gadget_metering023_electricity.htm","VEE(전기)","VEE (Electricity) Top Previous Next AIMIR v3.0 Manual This gadget provides a search function to do Validation Check, Editing, Estimation and check...",""],
["gadget_metering024.htm","Customer over capacity contract(Electricity)","Customer over capacity contract(Electricity) Top Previous Next AIMIR v3.0 Manual This gadget provides a customer list of abnormal usage and excess...",""],
["gadget_metering025.htm","Billing Reports(Electricity)","Billing Reports(Electricity) Top Previous Next AIMIR v3.0 Manual This Gadget can output the information of per TOU (Time Of Use)energy consumption...",""],
["gadget_system001.htm","Code Management","Code Management Top Previous Next AIMIR v3.0 Manual Providing the definition of the code and the code list, code functions of Add / Edit / Delete....",""],
["gadget_system002.htm","Manufacturer Model Management","Manufacturer Model Management Top Previous Next AIMIR v3.0 Manual Providing Equipment Manufacturer, Model Information and Inquiry of model informa...",""],
["gadget_system003.htm","Supplier Management","Supplier Management Top Previous Next AIMIR v3.0 Manual Providing the information of Local management, supplier, and supply services (electricity,...",""],
["gadget_system004.htm","User Management","User Management Top Previous Next AIMIR v3.0 Manual Providing User account management, rights management as per customer, user group management se...",""],
["gadget_system008.htm","Command History Management","Command History Management Top Previous Next AIMIR v3.0 Manual Providing not only operation charts for equipment including the number of attempts,...",""],
["gadget_system010.htm","Customer Contract Management","Customer Contract Management Top Previous Next AIMIR v3.0 Manual Providing the information of Customer, contract, management of a prepaid customer...",""],
["group_management.htm","Group Management","Group Management Top Previous Next AIMIR v3.0 Manual Mini Gadget Max Gadget ",""],
["metering_dashboard.htm","Metering Data Management","Metering Data Management Top Previous Next AIMIR v3.0 Manual This section contains explanation of the various type&#39;s gadgets for managing meter da...",""],
["overview.htm","Overview","Overview Top Previous Next AIMIR v3.0 Manual This article describes the new features of AIMIR 3.0 and explain each gadget including detailed expla...",""],
["system_dashboard.htm","System Management","System Management Top Previous Next AIMIR v3.0 Manual Customer information, supplier information, user information and information about various t...",""]];
