pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["2__gadget.htm","2. Gadget","2. Gadget Top Previous Next 가젯 가젯은 Google사의 iGoogle을 모티브로 하여 비활성모드, 축약화면 (Mini Gadget), 최대화면 (Max Gadget)의 형태를 지니며 각 가젯별로 가젯 비활성화, 활성화, 도움말, 새로 고침...",""],
["3__dashboard_and_gadget_manage.htm","3. Dashboard and Gadget Management","3. Dashboard and Gadget Management Top Previous Next 대시보드 및 가젯 관리 각 대시보드 별로 보고 싶은 가젯을 골라 볼 수 있게 가젯 설정 항목에서 대시보드 추가삭제 관리 및 가젯 추가 삭제 관리 등의 서비스를 제공합니...",""],
["4__help.htm","4. Help","4. Help Top Previous Next HELP 기능 전체 도움말 보기 기능, 각 가젯 별 도움말 보기 기능을 제공 상단의 HELP 링크를 클릭하면 전체 도움말 페이지를 볼 수 있으며 각 가젯 별로 가젯 우측 상단의 ‘?’ 를 클릭하면 가젯 별로 도움말을...",""],
["abnormal_contract_customers.htm","Abnormal Contract Customers(Electricity)","Abnormal Contract Customers(Electricity) Top Previous Next 전기 고객 중 비정상 사용 고객이나 계약용량 보다 실제 사용량이 더 큰 고객 목록을 조회하는 기능을 제공 Mini Gadget Max Gadget ",""],
["aimir_ami_system.htm","AiMiR AMI System","AiMiR AMI System Top Previous Next AiMiR Metering System은 원격에 있는 Meter로부터 주기적(Event-Driven, Asynchronous) 또는 On-demand (Polling, Synchronous) 방식으로...",""],
["alarmevent.htm","Alarm&#38;Event","Alarm&#38;Event Top Previous Next 단 말기와 계기 사이 Interface, 단말기 내부 및 Metering Data Transmission Path 상 비정상 상태 그리고 수신된 검침 데이터 오류로 인한 Alarm, Event 정보를 생성, ...",""],
["alarm_event.htm","Alarm, Event Gadget","Alarm, Event Gadget Top Previous Next ",""],
["analysis_of_metering_data.htm","Analysis of Metering Data","Analysis of Metering Data Top Previous Next Calendar (Monthly) Chart 특 정 고객에 대해 특정 월에 대한 일별 사용량 Graph를 Calendar 형식으로 보여줌. Weekday별, Weekend별 또는 특정...",""],
["batery_log.htm","Batery Log","Batery Log Top Previous Next 통신장비(모뎀)의 배터리 정보 및 배터리 정보 이력 등의 정보를 제공하여 대략적인 배터리 상태 및 수명을 알 수 있게 정보를 제공합니다 Mini Gadget 센서 타입이 ZEUPLS 이거나 리피터인 경우 검침 ...",""],
["chapter_2.htm","Introduction of AiMiR","Introduction of AiMiR Top Next 저작권 및 등록상표 AIMIR&#174; 는 누리텔레콤의 등록상표입니다. 사용자 공지 이 문서에 포함되어 있는 어떠한 정보도 기능 향상 등을 이유로 사전 통보 없이 변경 및 수정되어질 수 있으며, 누리텔레콤은 본 문...",""],
["circuit_breaker_management.htm","Load Management","Load Management Top Previous Next Enter topic text here. ",""],
["circuit_breaker_management2.htm","Circuit Breaker Management","Circuit Breaker Management Top Previous Next 공급 차단 재개 Mini Gadget Max Gadget 비상시 차단할 수 있게 해당 대상을 검색하여 바로 차단할 수 있게 합니다. 엑셀 출력 기능을 제공합니다. 선불 임계치 , 공...",""],
["co2_management.htm","5. CO2 Management","5. CO2 Management Top Previous Next 탄소 배출량 관리 전기, 가스, 수도 별 탄소 배출량 관리하며 전기, 가스, 수도 사용량을 탄소 배출량으로 환산하여 보여줍니다. 공사 관리 정보에서 각 에너지원 별 CO2발생량에 관한 정보 검침데이...",""],
["code_management.htm","Code Management","Code Management Top Previous Next 시스템에서 관리하는 코드 정의 및 코드 목록, 코드 정보 추가/수정 삭제 기능 Mini Gadget Max Gadget ",""],
["communication_log.htm","Communication Log","Communication Log Top Previous Next 통신 장비 별 통신 타입, 통신 시간, 통신 양 등에 대한 정보를 제공 Mini Gadget 기본적으로 일주일 치의 데이터를 보여줍니다. Max Gadget ",""],
["concentrator_mangement.htm","Concentrator Mangement","Concentrator Mangement Top Previous Next 공사에서 관리하는 집중기 목록 및 상세 정보, 집중기 별 검침스케줄 설정, 집중기 설치 위치 정보 , 집중기 설정 및 제어 등의 기능을 제공 Mini Gadget Max Gadget Bas...",""],
["configuration.htm","Configuration","Configuration Top Previous Next Metering Application 운용에 필요한 제반 설정 정보를 관리한다. 관리되는 정보는 다음과 같다. User Group 및 User Customer 정보 관리 Equipment Group 관리 ...",""],
["consumption_ranking.htm","Consumption Ranking(Electricity)","Consumption Ranking(Electricity) Top Previous Next 전기, 수도, 가스, 열량 고객을 대상으로 하여 소비 순위가 높은 고객 혹은 소비순위가 가장 낮은 고객 혹은 특정 기간 동안 사용량이 지속적으로 0인 고객에 대한 정보를 ...",""],
["customer_and_contract.htm","Customer and Contract","Customer and Contract Top Previous Next 공사별 고객 정보, 계약 정보, 선불 고객 관리, 계약 변경 내역, 월별 사용량 등의 정보를 제공 Mini Gadget 전체 고객 중 고객의 계약 상태에 따라 분류합니다. Normal : 정...",""],
["dash_board.htm","1. Dash Board","1. Dash Board Top Previous Next 대시보드 해당 시스템은 대시보드에 여러 개의 가젯을 올려놓아 한 대시보드 안에서 가젯의 위치를 이동 시킬 수 있습니다. 사용자가 필요한 가젯만 보고 싶으면 보지 않는 가젯은 비 활성 시킬 수 있습니다. 사...",""],
["data_gaps.htm","Data Gaps(Electricity)","검침데이터가 누락된 미터들에 대해 기간별로 누락 상태를 조회할 수 있는 기능을 제공 Mini Gadget Max Gadget 엑셀 출력 기능을 제공합니다. ",""],
["demand_management.htm","Demand Management","Demand Management Top Previous Next 수요관리의 궁극적 목적은 전력수요를 합리적으로 조절하여 부하율 향상을 통한 원가절감과 전력 수안정을 도모합니다. . 전기에서 수요관리(부하관리) Demand Side Management는 최소의 비...",""],
["device_dashboard.htm","Device","Device Top Previous Next Enter topic text here. ",""],
["device_registration.htm","Device Registration","Device Registration Top Previous Next 장비에 대한 개별, 일괄 등록 기능 등록 장비에 대한 이력 관리 (개별, 일괄, 연동, 자동 등 미터의 등록 타입 별로 관리 Mini Gadget Max Gadget ",""],
["device_vendor_model.htm","Device Vendor Model","Device Vendor Model Top Previous Next 시스템에서 사용하는 장비의 제조사, 모델 정보 및 특정 모델에 특화된 정보조회, 모델 사진 등의 서비스를 제공 Mini Gadget Max Gadget ",""],
["electricity_meter.htm","ZRU(ZigBee Meter Reading Unit for Electricity Meter)","ZRU(ZigBee Meter Reading Unit for Electricity Meter) Top Previous Next 전기 계량기와 기 정의된 Interface(RS-232)를 통해 통신 경로를 설정하고 상위 시스템인 집중기와는 ZigBee를 이용하여 ...",""],
["electricity_sales.htm","Electricity sales","Electricity sales Top Previous Next 공사가 관리하는 고객의 월별 사용량 및 사용금액 정보를 제공 Mini Gadget Max Gadget ",""],
["event_alarm_log.htm","Event Alarm Log","Event Alarm Log Top Previous Next 시스템 및 장비에서 발생한 모든 이벤트들에 대해 실시간 보기 및 이벤트 이력 조회, 이벤트 보기 설정 등에 대한 정보를 제공 ",""],
["gas_sales.htm","Gas sales","Gas sales Top Previous Next Enter topic text here. ",""],
["google_map_for_device.htm","Google Map For Device","Google Map For Device Top Previous Next Google Map 서비스와 연계 하여 주소 혹은 장비 아이디로 위치 찾기 제공 및 장비에 연관된 장비들 위치 표시등의 기능을 제공합니다 Mini Gadget Max Gadget ",""],
["group_management.htm","Group Management","Group Management Top Previous Next 그룹 추가/수정/삭제, 그룹멤버 관리 가젯 특정 그룹을 선택 후에 멤버 추가 버튼을 클릭하면 아래 멤버추가 탭이 활성화 됩니다. 그룹선택을 하지 않으면 그룹선택을 먼저 하라는 메시지를 뿌려야 합니다....",""],
["heat_sales.htm","Heat sales","Heat sales Top Previous Next Enter topic text here. ",""],
["main_features.htm","Main Features","Main Features Top Previous Next Enter topic text here. ",""],
["mcumaster_control_unit.htm","MCU(Master Control Unit)","MCU(Master Control Unit) Top Previous Next 상 위 시스템인 원격검침 서버(NACS)로부터의 명령을 단말기 또는 계기로 전송하거나 스스로 단말기 또는 계기와 통신하여 기 정의된 Task를 수행한다. 또한 여러 종류의 자체 스케줄에...",""],
["metering_dashboard.htm","Metering","Metering Top Previous Next Enter topic text here. ",""],
["metering_data.htm","Metering Data(Electricity)","Metering Data(Electricity) Top Previous Next Mini Gadget 전기, 가스, 수도, 열량 공타입 별 가젯으로 지역별 검침 률 현황과 각 미터의 검침데이터 수치를 검침기간별, 지역별, 고객별로 조회할 수 있는 기능을 제공합니...",""],
["metering_fail.htm","Metering Fail(Electricity)","Metering Fail(Electricity) Top Previous Next Mini Gadget Max Gadget 엑셀 출력 기능을 제공합니다. 검침 실패 고객들에 대한 통계 및 실패 원인, 재 검침 서비스 등의 정보를 제공 엑셀 출력 기능을 제공합니다. ",""],
["metering_management.htm","Metering Management","Metering Management Top Previous Next Data Collection &#38; Transmission 각 각의 단말기 (Terminal Unit)는 설정된 검침 스케줄에 따라 계량기로부터 조회 또는 Pulse Counting을 통해 검침 데...",""],
["metering_sla.htm","Metering SLA","Metering SLA Top Previous Next 검침에 대한 전반적인 성공률 지표 및 분석 가젯 Mini Gadget Max Gadget ",""],
["metering_statistics.htm","Metering Statistics","Metering Statistics Top Previous Next Metering Statistics 다양한 주기별 검침 성공 통계 정보를 조회하며 실패한 고객 목록을 조회할 수 있다. 또한 이러한 검침 통계를 계기별, 집중기별 및 사용자 정의 그룹별로 조회할...",""],
["meter_management.htm","Meter Management","Meter Management Top Previous Next 전기,가스, 수도, 열량 미터 등 공사가 공하는 에너지원 목록 및 상세 정보 연관된 장치 정보, 미터 별 검침데이터 ,위치 정보, 미터 설치 정보 사진 등을 제공 Mini Gadget 해당 검색 조건...",""],
["meter_time_management.htm","Meter Time Management","Meter Time Management Top Previous Next 미터와 서버시간과의 오차 정보, 미터 타임 설정 이력, 미터 타임 설정에 대한 임계치 설정 등의 서비스 제공 Mini Gadget Max Gadget 미터 시간차를 구간별로 그래프로 표시해줌...",""],
["modem_management.htm","Modem Management","Modem Management Top Previous Next 모뎀 종류별, 지역별, 통신 상태 별 모뎀 목록 관리 및 장비 추가, 삭제 기능 제공 특정 모뎀에 대한 LP log, Event Log, Unit Scanning, Monitoring 기능 제공 Mi...",""],
["nacsnuri_aimir_center_system.htm","NACS(Nuri AiMiR Center System)","NACS(Nuri AiMiR Center System) Top Previous Next WEB User Interface를 통해 수행되는 사용자 명령을 수신하여 특정 장치(집중기, 단말기 또는 계기)로 전송하고 해당 결과를 다시 사용자에게 전달한다. 또한 주기적...",""],
["operation_management.htm","Operation Management","Operation Management Top Previous 장비에 내린 명령(Operation)들의 목록과 각각의 시도 횟수, 성공률 등을 차트로 제공 장비 별로 시스템에서 제어할 수 있는 명령들에 대한 설정 및 시스템에서 지시한 명령 수행 이력들에 대한 정보...",""],
["overview.htm","Overview","Overview Top Previous Next 이 문서는 AIMIR 3.0 버전의 신규 기능 및 각 가젯 들에 대해 기술하며 각 세부기능에 대한 설명, 화면 구성에 대한 내용을 설명하고 있습니다. AIMIR 3.0 로그인 화면 해당 시스템의 화면은 1280*1...",""],
["power_alarm_log.htm","PowerAlarmLog","PowerAlarmLog Top Previous Next 미터의 정전 내역, 기간, 및 복구 내역, 장기간 정전, 짧은 정전 이력, 결상 발생 복구 내역 등의 정보를 제공 Mini Gadget 기본적으로 일주일 치의 데이터를 보여줍니다. Max Gadget ",""],
["power_quality.htm","Power Quality","Power Quality Top Previous Next 전기의 전력 품질(Voltage, Current) , Voltage Level, Voltage Imbalance 정보를 제공 전기 미터의 경우 검침 주기 별 전력 품질데이터를 의미합니다. 전기 미터의 경우...",""],
["report.htm","Report","Report Top Previous Next 사용자 요구 사항에 맞게 Form을 설계, 보고서를 생성할 수 있는 Engine을 내장하고 있으며, PDF, Excel Export 기능을 제공한다. 보고서는 각 화면상에 나타나는 \"Print\" 버튼 클릭 시 생성된다. ",""],
["supplier_management.htm","Supplier Management","Supplier Management Top Previous Next 공급사에서 관리하는 지역관리, 공급사 정보, 공급사가 제공하는 공급 서비스(전기, 가스, 수도 등)에 대한 정보, 과금 정보 관리 등의 서비스를 제공. Mini Gadget 로그인한 사용자의 공...",""],
["system_dashboard.htm","System Gadget","System Gadget Top Previous Next Enter topic text here. ",""],
["system_management.htm","System Management","System Management Top Previous Next Local Unit(Meter unit), Terminal Unit, Communication unit에 대한 구성 정보를 관리한다. Metering Application에 관련된 모든 Unit에 ...",""],
["user_management.htm","User Management","User Management Top Previous Next 사용자 계정관리, 사용자 별 권한 관리, 사용자 그룹관리 서비스 제공 Mini Gadget 미니 가젯 에서 그룹별 사용자 목록을 보여줍니다. 사용자 아이디 및 기본 정보 등을 보여줍니다. Max Gad...",""],
["vee.htm","VEE Management","VEE Management Top Previous Next VEE (Metering Data Validation, Estimation, Editing) 검침데이터에 대한 Validation Check, Editing, Estimation을 할 수 있는 기능을 제...",""],
["water_sales.htm","Water sales","Water sales Top Previous Next Enter topic text here. ",""],
["zeu_plszigbee_expansion_unit_p.htm","ZEU-PLS(ZigBee Expansion Unit-Pulse)","ZEU-PLS(ZigBee Expansion Unit-Pulse) Top Previous Next 수도 계량기 같은 펄스형 계기와 기 정의된 Interface(Pulse Cable)를 통해 통신 경로를 설정하고 상위 시스템인 집중기와는 ZigBee를 이용하여 통...",""]];
