//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:41:41 PM KST 
//


package _1_release.cpsm_v4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BreakerConfiguration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BreakerConfiguration">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="singleBreaker"/>
 *     &lt;enumeration value="breakerAndAHalf"/>
 *     &lt;enumeration value="doubleBreaker"/>
 *     &lt;enumeration value="noBreaker"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BreakerConfiguration")
@XmlEnum
public enum BreakerConfiguration {

    @XmlEnumValue("singleBreaker")
    SINGLE_BREAKER("singleBreaker"),
    @XmlEnumValue("breakerAndAHalf")
    BREAKER_AND_A_HALF("breakerAndAHalf"),
    @XmlEnumValue("doubleBreaker")
    DOUBLE_BREAKER("doubleBreaker"),
    @XmlEnumValue("noBreaker")
    NO_BREAKER("noBreaker");
    private final String value;

    BreakerConfiguration(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BreakerConfiguration fromValue(String v) {
        for (BreakerConfiguration c: BreakerConfiguration.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
