//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:41:41 PM KST 
//


package _1_release.cpsm_v4;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransformerControlMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TransformerControlMode">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="off"/>
 *     &lt;enumeration value="local"/>
 *     &lt;enumeration value="volt"/>
 *     &lt;enumeration value="active"/>
 *     &lt;enumeration value="reactive"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TransformerControlMode")
@XmlEnum
public enum TransformerControlMode {

    @XmlEnumValue("off")
    OFF("off"),
    @XmlEnumValue("local")
    LOCAL("local"),
    @XmlEnumValue("volt")
    VOLT("volt"),
    @XmlEnumValue("active")
    ACTIVE("active"),
    @XmlEnumValue("reactive")
    REACTIVE("reactive");
    private final String value;

    TransformerControlMode(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TransformerControlMode fromValue(String v) {
        for (TransformerControlMode c: TransformerControlMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
