package com.aimir.fep.protocol.fmp.frame.service.entry;

import javax.xml.bind.annotation.XmlTransient;

import com.aimir.fep.protocol.fmp.datatype.*;
import com.aimir.fep.protocol.fmp.frame.service.Entry;

/**
 * ethEntry
 * generated by MIB Tool, Do not modify
 *
 * @author Y.S Kim (sorimo@nuritelecom.com)
 * @version $Rev: 1 $, $Date: 2005-11-21 15:59:15 +0900 $,
 */
public class ethEntry extends Entry {

	public OCTET ethName = 
			new OCTET(16);

	public OCTET ethPhyAddr = 
			new OCTET(6);

	public IPADDR ethIpAddr = 
			new IPADDR();

	public IPADDR ethSubnetMask = 
			new IPADDR();

	public IPADDR ethGateway = 
			new IPADDR();

	@XmlTransient
	public OCTET getEthName()
	{
		 return this.ethName;
	}

	public void setEthName(OCTET ethName)
	{
		 this.ethName=ethName;
	}

	@XmlTransient
	public OCTET getEthPhyAddr()
	{
		 return this.ethPhyAddr;
	}

	public void setEthPhyAddr(OCTET ethPhyAddr)
	{
		 this.ethPhyAddr=ethPhyAddr;
	}

	@XmlTransient
	public IPADDR getEthIpAddr()
	{
		 return this.ethIpAddr;
	}

	public void setEthIpAddr(IPADDR ethIpAddr)
	{
		 this.ethIpAddr=ethIpAddr;
	}

	@XmlTransient
	public IPADDR getEthSubnetMask()
	{
		 return this.ethSubnetMask;
	}

	public void setEthSubnetMask(IPADDR ethSubnetMask)
	{
		 this.ethSubnetMask=ethSubnetMask;
	}

	@XmlTransient
	public IPADDR getEthGateway()
	{
		 return this.ethGateway;
	}

	public void setEthGateway(IPADDR ethGateway)
	{
		 this.ethGateway=ethGateway;
	}


    public String toString()
    {
        StringBuffer sb = new StringBuffer();

		sb.append("CLASS["+this.getClass().getName()+"]\n");
		sb.append("ethName: " + ethName + "\n");
		sb.append("ethPhyAddr: " + ethPhyAddr + "\n");
		sb.append("ethIpAddr: " + ethIpAddr + "\n");
		sb.append("ethSubnetMask: " + ethSubnetMask + "\n");
		sb.append("ethGateway: " + ethGateway + "\n");


        return sb.toString();
    }
}
