//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:41:41 PM KST 
//


package org.multispeak.version_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for assessmentLocation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="assessmentLocation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_4.1_Release}mspPointObject">
 *       &lt;sequence>
 *         &lt;element name="address" type="{http://www.multispeak.org/Version_4.1_Release}address" minOccurs="0"/>
 *         &lt;element name="locationOffset" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assessmentList" type="{http://www.multispeak.org/Version_4.1_Release}ArrayOfAssessment" minOccurs="0"/>
 *         &lt;element name="attachments" type="{http://www.multispeak.org/Version_4.1_Release}ArrayOfAttachment" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "assessmentLocation", propOrder = {
    "address",
    "locationOffset",
    "assessmentList",
    "attachments"
})
public class AssessmentLocation
    extends MspPointObject
{

	@XmlElement(name="address")
    protected Address address;
	@XmlElement(name="locationOffset")
    protected String locationOffset;
	@XmlElement(name="assessmentList")
    protected ArrayOfAssessment assessmentList;
	@XmlElement(name="attachments")
    protected ArrayOfAttachment attachments;

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setAddress(Address value) {
        this.address = value;
    }

    /**
     * Gets the value of the locationOffset property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationOffset() {
        return locationOffset;
    }

    /**
     * Sets the value of the locationOffset property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationOffset(String value) {
        this.locationOffset = value;
    }

    /**
     * Gets the value of the assessmentList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAssessment }
     *     
     */
    public ArrayOfAssessment getAssessmentList() {
        return assessmentList;
    }

    /**
     * Sets the value of the assessmentList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAssessment }
     *     
     */
    public void setAssessmentList(ArrayOfAssessment value) {
        this.assessmentList = value;
    }

    /**
     * Gets the value of the attachments property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfAttachment }
     *     
     */
    public ArrayOfAttachment getAttachments() {
        return attachments;
    }

    /**
     * Sets the value of the attachments property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfAttachment }
     *     
     */
    public void setAttachments(ArrayOfAttachment value) {
        this.attachments = value;
    }

}
