//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:40:55 PM KST 
//


package org.multispeak.version_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bufferedObjectCollection complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="bufferedObjectCollection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bufferedPoint" type="{http://www.multispeak.org/Version_4.1_Release}bufferedPoint" minOccurs="0"/>
 *         &lt;element name="physicalObjectList" type="{http://www.multispeak.org/Version_4.1_Release}physicalObjectList" minOccurs="0"/>
 *         &lt;element name="bufferedReferenceList" type="{http://www.multispeak.org/Version_4.1_Release}ArrayOfBufferedObjectRef" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "bufferedObjectCollection", propOrder = {
    "bufferedPoint",
    "physicalObjectList",
    "bufferedReferenceList"
})
public class BufferedObjectCollection {

    protected BufferedPoint bufferedPoint;
    protected PhysicalObjectList physicalObjectList;
    protected ArrayOfBufferedObjectRef bufferedReferenceList;

    /**
     * Gets the value of the bufferedPoint property.
     * 
     * @return
     *     possible object is
     *     {@link BufferedPoint }
     *     
     */
    public BufferedPoint getBufferedPoint() {
        return bufferedPoint;
    }

    /**
     * Sets the value of the bufferedPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link BufferedPoint }
     *     
     */
    public void setBufferedPoint(BufferedPoint value) {
        this.bufferedPoint = value;
    }

    /**
     * Gets the value of the physicalObjectList property.
     * 
     * @return
     *     possible object is
     *     {@link PhysicalObjectList }
     *     
     */
    public PhysicalObjectList getPhysicalObjectList() {
        return physicalObjectList;
    }

    /**
     * Sets the value of the physicalObjectList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhysicalObjectList }
     *     
     */
    public void setPhysicalObjectList(PhysicalObjectList value) {
        this.physicalObjectList = value;
    }

    /**
     * Gets the value of the bufferedReferenceList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBufferedObjectRef }
     *     
     */
    public ArrayOfBufferedObjectRef getBufferedReferenceList() {
        return bufferedReferenceList;
    }

    /**
     * Sets the value of the bufferedReferenceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBufferedObjectRef }
     *     
     */
    public void setBufferedReferenceList(ArrayOfBufferedObjectRef value) {
        this.bufferedReferenceList = value;
    }

}
