//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:41:41 PM KST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.multispeak.org/Version_4.1_Release", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.multispeak.version_4;
