//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:41:41 PM KST 
//


package org.multispeak.version_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for readingSchedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="readingSchedule">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.multispeak.org/Version_4.1_Release}schedule">
 *       &lt;sequence>
 *         &lt;element name="meterList" type="{http://www.multispeak.org/Version_4.1_Release}ArrayOfMeterID" minOccurs="0"/>
 *         &lt;element name="meterGroupList" type="{http://www.multispeak.org/Version_4.1_Release}ArrayOfMeterGroupIDs" minOccurs="0"/>
 *         &lt;element name="configurationGroupList" type="{http://www.multispeak.org/Version_4.1_Release}ArrayOfConfigurationGroupIDs" minOccurs="0"/>
 *         &lt;element name="readingTypeList" type="{http://www.multispeak.org/Version_4.1_Release}ArrayOfReadingType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "readingSchedule", propOrder = {
    "meterList",
    "meterGroupList",
    "configurationGroupList",
    "readingTypeList"
})
public class ReadingSchedule
    extends Schedule
{

    protected ArrayOfMeterID meterList;
    protected ArrayOfMeterGroupIDs meterGroupList;
    protected ArrayOfConfigurationGroupIDs configurationGroupList;
    protected ArrayOfReadingType readingTypeList;

    /**
     * Gets the value of the meterList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMeterID }
     *     
     */
    public ArrayOfMeterID getMeterList() {
        return meterList;
    }

    /**
     * Sets the value of the meterList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMeterID }
     *     
     */
    public void setMeterList(ArrayOfMeterID value) {
        this.meterList = value;
    }

    /**
     * Gets the value of the meterGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfMeterGroupIDs }
     *     
     */
    public ArrayOfMeterGroupIDs getMeterGroupList() {
        return meterGroupList;
    }

    /**
     * Sets the value of the meterGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfMeterGroupIDs }
     *     
     */
    public void setMeterGroupList(ArrayOfMeterGroupIDs value) {
        this.meterGroupList = value;
    }

    /**
     * Gets the value of the configurationGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfConfigurationGroupIDs }
     *     
     */
    public ArrayOfConfigurationGroupIDs getConfigurationGroupList() {
        return configurationGroupList;
    }

    /**
     * Sets the value of the configurationGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfConfigurationGroupIDs }
     *     
     */
    public void setConfigurationGroupList(ArrayOfConfigurationGroupIDs value) {
        this.configurationGroupList = value;
    }

    /**
     * Gets the value of the readingTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfReadingType }
     *     
     */
    public ArrayOfReadingType getReadingTypeList() {
        return readingTypeList;
    }

    /**
     * Sets the value of the readingTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfReadingType }
     *     
     */
    public void setReadingTypeList(ArrayOfReadingType value) {
        this.readingTypeList = value;
    }

}
