//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:40:55 PM KST 
//


package org.multispeak.version_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="outageEventID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="eventTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="callBackCustomersThatCalled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="outageCause" type="{http://www.multispeak.org/Version_4.1_Release}outageReasonContainer" minOccurs="0"/>
 *         &lt;element name="dispatcherResponsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outageEventID",
    "eventTime",
    "callBackCustomersThatCalled",
    "outageCause",
    "dispatcherResponsible"
})
@XmlRootElement(name = "RestoreOutage")
public class RestoreOutage {

    protected String outageEventID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventTime;
    protected boolean callBackCustomersThatCalled;
    protected OutageReasonContainer outageCause;
    protected String dispatcherResponsible;

    /**
     * Gets the value of the outageEventID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutageEventID() {
        return outageEventID;
    }

    /**
     * Sets the value of the outageEventID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutageEventID(String value) {
        this.outageEventID = value;
    }

    /**
     * Gets the value of the eventTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTime() {
        return eventTime;
    }

    /**
     * Sets the value of the eventTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTime(XMLGregorianCalendar value) {
        this.eventTime = value;
    }

    /**
     * Gets the value of the callBackCustomersThatCalled property.
     * 
     */
    public boolean isCallBackCustomersThatCalled() {
        return callBackCustomersThatCalled;
    }

    /**
     * Sets the value of the callBackCustomersThatCalled property.
     * 
     */
    public void setCallBackCustomersThatCalled(boolean value) {
        this.callBackCustomersThatCalled = value;
    }

    /**
     * Gets the value of the outageCause property.
     * 
     * @return
     *     possible object is
     *     {@link OutageReasonContainer }
     *     
     */
    public OutageReasonContainer getOutageCause() {
        return outageCause;
    }

    /**
     * Sets the value of the outageCause property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutageReasonContainer }
     *     
     */
    public void setOutageCause(OutageReasonContainer value) {
        this.outageCause = value;
    }

    /**
     * Gets the value of the dispatcherResponsible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatcherResponsible() {
        return dispatcherResponsible;
    }

    /**
     * Sets the value of the dispatcherResponsible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatcherResponsible(String value) {
        this.dispatcherResponsible = value;
    }

}
