//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.22 at 06:40:55 PM KST 
//


package org.multispeak.version_4;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="troubledElement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="statusPhaseA" type="{http://www.multispeak.org/Version_4.1_Release}outageElementStatus"/>
 *         &lt;element name="statusPhaseB" type="{http://www.multispeak.org/Version_4.1_Release}outageElementStatus"/>
 *         &lt;element name="statusPhaseC" type="{http://www.multispeak.org/Version_4.1_Release}outageElementStatus"/>
 *         &lt;element name="eventTime" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="dispatcherResponsible" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "troubledElement",
    "statusPhaseA",
    "statusPhaseB",
    "statusPhaseC",
    "eventTime",
    "dispatcherResponsible"
})
@XmlRootElement(name = "SetOutageElementStatus")
public class SetOutageElementStatus {

    protected String troubledElement;
    @XmlElement(required = true)
    protected OutageElementStatus statusPhaseA;
    @XmlElement(required = true)
    protected OutageElementStatus statusPhaseB;
    @XmlElement(required = true)
    protected OutageElementStatus statusPhaseC;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eventTime;
    protected String dispatcherResponsible;

    /**
     * Gets the value of the troubledElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTroubledElement() {
        return troubledElement;
    }

    /**
     * Sets the value of the troubledElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTroubledElement(String value) {
        this.troubledElement = value;
    }

    /**
     * Gets the value of the statusPhaseA property.
     * 
     * @return
     *     possible object is
     *     {@link OutageElementStatus }
     *     
     */
    public OutageElementStatus getStatusPhaseA() {
        return statusPhaseA;
    }

    /**
     * Sets the value of the statusPhaseA property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutageElementStatus }
     *     
     */
    public void setStatusPhaseA(OutageElementStatus value) {
        this.statusPhaseA = value;
    }

    /**
     * Gets the value of the statusPhaseB property.
     * 
     * @return
     *     possible object is
     *     {@link OutageElementStatus }
     *     
     */
    public OutageElementStatus getStatusPhaseB() {
        return statusPhaseB;
    }

    /**
     * Sets the value of the statusPhaseB property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutageElementStatus }
     *     
     */
    public void setStatusPhaseB(OutageElementStatus value) {
        this.statusPhaseB = value;
    }

    /**
     * Gets the value of the statusPhaseC property.
     * 
     * @return
     *     possible object is
     *     {@link OutageElementStatus }
     *     
     */
    public OutageElementStatus getStatusPhaseC() {
        return statusPhaseC;
    }

    /**
     * Sets the value of the statusPhaseC property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutageElementStatus }
     *     
     */
    public void setStatusPhaseC(OutageElementStatus value) {
        this.statusPhaseC = value;
    }

    /**
     * Gets the value of the eventTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEventTime() {
        return eventTime;
    }

    /**
     * Sets the value of the eventTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEventTime(XMLGregorianCalendar value) {
        this.eventTime = value;
    }

    /**
     * Gets the value of the dispatcherResponsible property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatcherResponsible() {
        return dispatcherResponsible;
    }

    /**
     * Sets the value of the dispatcherResponsible property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatcherResponsible(String value) {
        this.dispatcherResponsible = value;
    }

}
