package com.aimir.mars.integration.multispeak.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import org.multispeak.version_4.ArrayOfCDState;
import org.multispeak.version_4.ArrayOfConnectDisconnectEvent;
import org.multispeak.version_4.ArrayOfErrorObject;
import org.multispeak.version_4.ExpirationTime;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-23T09:42:34.749+09:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://www.multispeak.org/Version_4.1_Release", name = "CD_ServerSoap")
@XmlSeeAlso({_1_release.cpsm_v4.ObjectFactory.class, _1_release.gml_v4.ObjectFactory.class, org.w3._1999.xlink.ObjectFactory.class})
public interface CDServerSoap {

    /**
     * CB
     *                                                                         initiates
     *                                                                         a
     *                                                                         connect
     *                                                                         or
     *                                                                         disconnect
     *                                                                         action
     *                                                                         by
     *                                                                         issuing
     *                                                                         one or
     *                                                                         more
     *                                                                         connectDisconnectEvent
     *                                                                         objects
     *                                                                         to the
     *                                                                         CD. CD
     *                                                                         returns
     *                                                                         information
     *                                                                         about
     *                                                                         failed
     *                                                                         transactions
     *                                                                         by
     *                                                                         returning
     *                                                                         an array
     *                                                                         of
     *                                                                         errorObjects.
     *                                                                         The
     *                                                                         connect/disconnect
     *                                                                         function
     *                                                                         returns
     *                                                                         infromation
     *                                                                         about
     *                                                                         this
     *                                                                         action
     *                                                                         using
     *                                                                         the
     *                                                                         CDStateChangedNotification
     *                                                                         to the
     *                                                                         URL
     *                                                                         specified
     *                                                                         in the
     *                                                                         responseURL
     *                                                                         calling
     *                                                                         parameter
     *                                                                         and
     *                                                                         references
     *                                                                         the
     *                                                                         transactionID
     *                                                                         specified
     *                                                                         to link
     *                                                                         the
     *                                                                         transaction
     *                                                                         to this
     *                                                                         Initiate
     *                                                                         request.The
     *                                                                         expiration
     *                                                                         time
     *                                                                         parameter
     *                                                                         indicates
     *                                                                         the
     *                                                                         amount
     *                                                                         of time
     *                                                                         for
     *                                                                         which
     *                                                                         the
     *                                                                         publisher
     *                                                                         should
     *                                                                         try to
     *                                                                         obtain
     *                                                                         and
     *                                                                         publish
     *                                                                         the
     *                                                                         data; if
     *                                                                         the
     *                                                                         publisher
     *                                                                         has been
     *                                                                         unsuccessful
     *                                                                         in
     *                                                                         publishing
     *                                                                         the data
     *                                                                         after
     *                                                                         the
     *                                                                         expiration
     *                                                                         time,
     *                                                                         then the
     *                                                                         publisher
     *                                                                         will
     *                                                                         discard
     *                                                                         the
     *                                                                         request
     *                                                                         and the
     *                                                                         requestor
     *                                                                         should
     *                                                                         not
     *                                                                         expect a
     *                                                                         response.
     */
    @WebResult(name = "InitiateConnectDisconnectResult", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
    @RequestWrapper(localName = "InitiateConnectDisconnect", targetNamespace = "http://www.multispeak.org/Version_4.1_Release", className = "org.multispeak.version_4.InitiateConnectDisconnect")
    @WebMethod(operationName = "InitiateConnectDisconnect", action = "http://www.multispeak.org/Version_4.1_Release/InitiateConnectDisconnect")
    @ResponseWrapper(localName = "InitiateConnectDisconnectResponse", targetNamespace = "http://www.multispeak.org/Version_4.1_Release", className = "org.multispeak.version_4.InitiateConnectDisconnectResponse")
    public ArrayOfErrorObject InitiateConnectDisconnect(
        @WebParam(name = "cdEvents", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        ArrayOfConnectDisconnectEvent cdEvents,
        @WebParam(name = "responseURL", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        java.lang.String responseURL,
        @WebParam(name = "transactionID", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        java.lang.String transactionID,
        @WebParam(name = "expTime", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        ExpirationTime expTime
    );

    /**
     * CB
     *                                                                         initiates
     *                                                                         a switch
     *                                                                         status
     *                                                                         check
     *                                                                         directly
     *                                                                         from one
     *                                                                         or more
     *                                                                         Connect/Disconnect
     *                                                                         devices.
     *                                                                         CD
     *                                                                         returns
     *                                                                         information
     *                                                                         about
     *                                                                         failed
     *                                                                         transactions
     *                                                                         by
     *                                                                         returning
     *                                                                         an array
     *                                                                         of
     *                                                                         errorObjects.
     *                                                                         The CD
     *                                                                         switch
     *                                                                         state
     *                                                                         check
     *                                                                         function
     *                                                                         returns
     *                                                                         information
     *                                                                         asynchronously
     *                                                                         about
     *                                                                         this
     *                                                                         switch
     *                                                                         state
     *                                                                         using
     *                                                                         either
     *                                                                         the
     *                                                                         CDStateNotification
     *                                                                         (for
     *                                                                         only one
     *                                                                         device)
     *                                                                         or the
     *                                                                         CDStatesNotification
     *                                                                         (for one
     *                                                                         or more
     *                                                                         devices)
     *                                                                         to the
     *                                                                         URL
     *                                                                         specified
     *                                                                         in the
     *                                                                         responseURL
     *                                                                         calling
     *                                                                         parameter
     *                                                                         and
     *                                                                         references
     *                                                                         the
     *                                                                         transactionID
     *                                                                         specified
     *                                                                         to link
     *                                                                         the
     *                                                                         transaction
     *                                                                         to this
     *                                                                         Initiate
     *                                                                         request.The
     *                                                                         expiration
     *                                                                         time
     *                                                                         parameter
     *                                                                         indicates
     *                                                                         the
     *                                                                         amount
     *                                                                         of time
     *                                                                         for
     *                                                                         which
     *                                                                         the
     *                                                                         publisher
     *                                                                         should
     *                                                                         try to
     *                                                                         obtain
     *                                                                         and
     *                                                                         publish
     *                                                                         the
     *                                                                         data; if
     *                                                                         the
     *                                                                         publisher
     *                                                                         has been
     *                                                                         unsuccessful
     *                                                                         in
     *                                                                         publishing
     *                                                                         the data
     *                                                                         after
     *                                                                         the
     *                                                                         expiration
     *                                                                         time,
     *                                                                         then the
     *                                                                         publisher
     *                                                                         will
     *                                                                         discard
     *                                                                         the
     *                                                                         request
     *                                                                         and the
     *                                                                         requestor
     *                                                                         should
     *                                                                         not
     *                                                                         expect a
     *                                                                         response.
     */
    @WebResult(name = "InitiateCDStateRequestResult", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
    @RequestWrapper(localName = "InitiateCDStateRequest", targetNamespace = "http://www.multispeak.org/Version_4.1_Release", className = "org.multispeak.version_4.InitiateCDStateRequest")
    @WebMethod(operationName = "InitiateCDStateRequest", action = "http://www.multispeak.org/Version_4.1_Release/InitiateCDStateRequest")
    @ResponseWrapper(localName = "InitiateCDStateRequestResponse", targetNamespace = "http://www.multispeak.org/Version_4.1_Release", className = "org.multispeak.version_4.InitiateCDStateRequestResponse")
    public ArrayOfErrorObject initiateCDStateRequest(
        @WebParam(name = "states", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        ArrayOfCDState states,
        @WebParam(name = "responseURL", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        java.lang.String responseURL,
        @WebParam(name = "transactionID", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        java.lang.String transactionID,
        @WebParam(name = "expTime", targetNamespace = "http://www.multispeak.org/Version_4.1_Release")
        ExpirationTime expTime
    );
}
