package com.aimir.mars.integration.multispeak.client;

import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-23T09:59:49.021+09:00
 * Generated source version: 2.7.16
 * 
 */
@WebService(targetNamespace = "http://www.multispeak.org/Version_4.1_Release", name = "OA_ServerSoap")
@XmlSeeAlso({_1_release.cpsm_v4.ObjectFactory.class, _1_release.gml_v4.ObjectFactory.class, org.w3._1999.xlink.ObjectFactory.class})
public interface OAServerSoap {

}
