package com.aimir.mars.integration.multispeak.client;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.7.16
 * 2015-07-22T20:55:13.612+09:00
 * Generated source version: 2.7.16
 * 
 */
@WebServiceClient(name = "OA_Server", 
                  wsdlLocation = "http://localhost:8089/services/OA_Server.wsdl",
                  targetNamespace = "http://www.multispeak.org/Version_4.1_Release") 
public class OAServer extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.multispeak.org/Version_4.1_Release", "OA_Server");
    public final static QName OAServerSoap = new QName("http://www.multispeak.org/Version_4.1_Release", "OA_ServerSoap");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8089/services/OA_Server.wsdl");            
            
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OAServer.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8089/services/OA_Server.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OAServer(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OAServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OAServer() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OAServer(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OAServer(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OAServer(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns OAServerSoap
     */
    @WebEndpoint(name = "OA_ServerSoap")
    public OAServerSoap getOAServerSoap() {
        return super.getPort(OAServerSoap, OAServerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OAServerSoap
     */
    @WebEndpoint(name = "OA_ServerSoap")
    public OAServerSoap getOAServerSoap(WebServiceFeature... features) {
        return super.getPort(OAServerSoap, OAServerSoap.class, features);
    }

}
