DROP TABLE ASYNC_COMMAND_LOG;

DECLARE
  STMT_DDL VARCHAR2(4000);
BEGIN
  STMT_DDL := 'CREATE TABLE ASYNC_COMMAND_LOG '||CHR(10)||
              '( '||CHR(10)||
              '  COMMAND     VARCHAR2(50), '||CHR(10)||
              '  CREATETIME  VARCHAR2(14), '||CHR(10)||
              '  CURNICE     NUMBER(2,0),  '||CHR(10)||
              '  CURTRY      NUMBER(2,0),  '||CHR(10)||
              '  DAY         NUMBER(2,0),  '||CHR(10)||
              '  DEVICEID    VARCHAR2(20), '||CHR(10)||
              '  DEVICETYPE  VARCHAR2(20), '||CHR(10)||
              '  ERRORCODE   NUMBER(2,0),  '||CHR(10)||
              '  EVENTTYPE   NUMBER(2,0),  '||CHR(10)||
              '  INITNICE    NUMBER(2,0),  '||CHR(10)||
              '  INITTRY     NUMBER(2,0),  '||CHR(10)||
              '  LASTTIME    VARCHAR2(14), '||CHR(10)||
              '  OPERATOR    VARCHAR2(20), '||CHR(10)||
              '  QUEUE       NUMBER(2,0),  '||CHR(10)||
              '  REQUESTTIME VARCHAR2(14), '||CHR(10)||
              '  RESULTCNT   NUMBER(2,0),  '||CHR(10)||
              '  STATE       NUMBER(2,0),  '||CHR(10)||
              '  TROPTION    NUMBER(2,0),  '||CHR(10)||
              '  MCUID       VARCHAR2(20) NOT NULL, '||CHR(10)||
              '  TRID        NUMBER(16,0) NOT NULL '||CHR(10)||
              ') '||CHR(10)||
              'PARTITION BY RANGE(REQUESTTIME) '||CHR(10)||
              '( '||CHR(10)||
              '  PARTITION PART'||TO_CHAR(CURRENT_DATE,'YYYYMMDD')||' VALUES LESS THAN ('''||TO_CHAR(CURRENT_DATE+1,'YYYYMMDD')||'0000'') '||CHR(10)||
              ') TABLESPACE AIMIRPART ';
  EXECUTE IMMEDIATE STMT_DDL;

  STMT_DDL := 'CREATE UNIQUE INDEX ASYNC_COMMAND_LOG_PK ON ASYNC_COMMAND_LOG (MCUID,TRID) LOCAL TABLESPACE AIMIRPART';
  EXECUTE IMMEDIATE STMT_DDL;
  STMT_DDL := 'CREATE INDEX ASYNC_COMMAND_LOG_IDX_01 ON ASYNC_COMMAND_LOG (DEVICEID,STATE) LOCAL TABLESPACE AIMIRPART';
  EXECUTE IMMEDIATE STMT_DDL;

END;
/

Insert into PARTITION_CONTROL (ID,PARTITIONINGINTERVAL,SQLCOMMAND,STARTDATETRUNCATE,ITERATIONS,STARTDATEOFFSET,ACTIVE) 
values ('ASYNC_COMMAND_LOG','DAILY','ALTER TABLE ASYNC_COMMAND_LOG ADD PARTITION PART{STARTDATE} VALUES LESS THAN(''{NEXTPERIODDATE}0000'') update indexes','dd',10,0,1);
Insert into PARTITION_CONTROL (ID,PARTITIONINGINTERVAL,SQLCOMMAND,STARTDATETRUNCATE,ITERATIONS,STARTDATEOFFSET,ACTIVE) 
values ('ASYNC_COMMAND_LOG DROP','DAILY','ALTER TABLE ASYNC_COMMAND_LOG DROP PARTITION PART{STARTDATE} update indexes','dd',15,-365,1);

commit work;
