DROP TABLE EVENTALERTLOG;

DECLARE
  STMT_DDL VARCHAR2(2000);
BEGIN
  STMT_DDL := 'CREATE TABLE EVENTALERTLOG '||CHR(10)||
              '( '||CHR(10)||
              '  ID             NUMBER(19) NOT NULL, '||CHR(10)||
              '  ACTIVATORID    VARCHAR2(100) NOT NULL, '||CHR(10)||
              '  ACTIVATORIP    VARCHAR2(100), '||CHR(10)||
              '  ACTIVATOR_TYPE VARCHAR2(255) NOT NULL, '||CHR(10)||
              '  CLOSETIME      VARCHAR2(14), '||CHR(10)||
              '  DURATION       VARCHAR2(255), '||CHR(10)||
              '  EVENTALERT_ID  NUMBER(10), '||CHR(10)||
              '  LOCATION_ID    NUMBER(10), '||CHR(10)||
              '  MESSAGE        VARCHAR2(255), '||CHR(10)||
              '  OCCURCNT       NUMBER(10), '||CHR(10)||
              '  OPENTIME       VARCHAR2(14), '||CHR(10)||
              '  SEVERITY_TYPE  VARCHAR2(255) NOT NULL, '||CHR(10)||
              '  STATUS         VARCHAR2(255) NOT NULL, '||CHR(10)||
              '  SUPPLIER_ID    NUMBER(10), '||CHR(10)||
              '  WRITETIME      VARCHAR2(14)  NOT NULL, '||CHR(10)||
              '  CONSTRAINT EVENTALERTLOG_PK PRIMARY KEY (ID), '||CHR(10)||
              '  CONSTRAINT EVENTALERTLOG_SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(ID), '||CHR(10)||
              '  CONSTRAINT EVENTALERTLOG_LOCATION_ID_FK FOREIGN KEY ("LOCATION_ID") REFERENCES LOCATION(ID), '||CHR(10)|| 
              '  CONSTRAINT EVENTALERTLOG_EVENTALERT_ID_FK FOREIGN KEY (EVENTALERT_ID) REFERENCES EVENTALERT(ID) '||CHR(10)||
              ') '||
              'PARTITION BY RANGE (OPENTIME) '||
              '( '||
              '  PARTITION PART'||TO_CHAR(CURRENT_DATE,'YYYYMMDD')||' VALUES LESS THAN ('''||TO_CHAR(CURRENT_DATE+1,'YYYYMMDD')||'000000'') '||CHR(10)||
              ') TABLESPACE AIMIRPART';

  EXECUTE IMMEDIATE STMT_DDL;

  STMT_DDL := 'CREATE INDEX EVENTALERTLOG_IDX_01 ON EVENTALERTLOG(OPENTIME,ACTIVATOR_TYPE, ACTIVATORID, EVENTALERT_ID) LOCAL TABLESPACE AIMIRPART';
  EXECUTE IMMEDIATE STMT_DDL;

END;
/

Insert into PARTITION_CONTROL (ID,PARTITIONINGINTERVAL,SQLCOMMAND,STARTDATETRUNCATE,ITERATIONS,STARTDATEOFFSET,ACTIVE) 
values ('EVENTALERTLOG','DAILY','ALTER TABLE EVENTALERTLOG ADD PARTITION PART{STARTDATE} VALUES LESS THAN(''{NEXTPERIODDATE}000000'') update indexes','dd',10,0,1);
Insert into PARTITION_CONTROL (ID,PARTITIONINGINTERVAL,SQLCOMMAND,STARTDATETRUNCATE,ITERATIONS,STARTDATEOFFSET,ACTIVE) 
values ('EVENTALERTLOG DROP','DAILY','ALTER TABLE EVENTALERTLOG DROP PARTITION PART{STARTDATE} update indexes','dd',15,-365,1);

commit work;

