CREATE TABLESPACE AIMIR
DATAFILE '/home/dbf/aimir.dbf' SIZE 2048M;
ALTER DATABASE DATAFILE '/home/dbf/aimir.dbf' AUTOEXTEND ON;

CREATE TABLESPACE AIMIRINT
DATAFILE '/home/dbf/aimirint.dbf' SIZE 2048M;
ALTER DATABASE DATAFILE '/home/dbf/aimirint.dbf' AUTOEXTEND ON;

CREATE TABLESPACE AIMIRPART
DATAFILE '/home/dbf/aimirpart.dbf' SIZE 8096M;
ALTER DATABASE DATAFILE '/home/dbf/aimirpart.dbf' AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE AIMIRTMP
TEMPFILE '/home/dbf/aimirtemp.dbf' SIZE 4096M;

CREATE USER aimir IDENTIFIED BY aimir
DEFAULT     TABLESPACE AIMIR
TEMPORARY   TABLESPACE AIMIRTMP;

ALTER USER aimir QUOTA UNLIMITED ON AIMIR;
ALTER USER aimir QUOTA UNLIMITED ON AIMIRINT;
ALTER USER aimir QUOTA UNLIMITED ON AIMIRPART;

GRANT RESOURCE,CREATE SESSION,CREATE JOB TO aimir;


-- ALTER DATABASE DATAFILE '/home/dbf/aimirpart.dbf' RESIZE 8096M;
-- ALTER DATABASE  TEMPFILE '/home/dbf/aimirtemp.dbf' RESIZE 4096M;
