
CREATE TABLE IP_DNSSYNC_LOG(
  LOGTYPE VARCHAR2(20) NOT NULL,
  DOMAINNAME VARCHAR2(50) NOT NULL,
  IPV4 VARCHAR2(15),
  IPV6 VARCHAR2(46),
  CREATEDTIME DATE DEFAULT CURRENT_DATE
) TABLESPACE AIMIRINT;

