DROP TABLE SNR_LOG;

DECLARE
  STMT_DDL VARCHAR2(4000);
BEGIN
  STMT_DDL := 'CREATE TABLE SNR_LOG '||CHR(10)||
              '( '||CHR(10)||
              '    DCU_ID VARCHAR2(255), '||CHR(10)||
              '    SNR NUMBER(19,4), '||CHR(10)||
              '    DEVICE_TYPE VARCHAR2(255) NOT NULL, '||CHR(10)||
              '    HHMMSS VARCHAR2(6) NOT NULL, '||CHR(10)||
              '    YYYYMMDD VARCHAR2(8) NOT NULL, '||CHR(10)||
              '    DEVICE_ID VARCHAR2(20) NOT NULL '||CHR(10)||
              ') '||CHR(10)||
              'PARTITION BY RANGE(YYYYMMDD) '||CHR(10)||
              '( '||CHR(10)||
              '  PARTITION PART'||TO_CHAR(CURRENT_DATE,'YYYYMMDD')||' VALUES LESS THAN ('''||TO_CHAR(CURRENT_DATE+1,'YYYYMMDD')||''') '||CHR(10)||
              ') TABLESPACE AIMIRPART ';
  EXECUTE IMMEDIATE STMT_DDL;

  STMT_DDL := 'CREATE UNIQUE INDEX SNR_LOG_PK ON SNR_LOG(DEVICE_TYPE, DEVICE_ID, YYYYMMDD, HHMMSS) LOCAL TABLESPACE AIMIRPART';
  EXECUTE IMMEDIATE STMT_DDL;

END;
/

Insert into PARTITION_CONTROL (ID,PARTITIONINGINTERVAL,SQLCOMMAND,STARTDATETRUNCATE,ITERATIONS,STARTDATEOFFSET,ACTIVE) 
values ('SNR_LOG','DAILY','ALTER TABLE SNR_LOG ADD PARTITION PART{STARTDATE} VALUES LESS THAN(''{NEXTPERIODDATE}'') update indexes','dd',10,0,1);
Insert into PARTITION_CONTROL (ID,PARTITIONINGINTERVAL,SQLCOMMAND,STARTDATETRUNCATE,ITERATIONS,STARTDATEOFFSET,ACTIVE) 
values ('SNR_LOG DROP','DAILY','ALTER TABLE SNR_LOG DROP PARTITION PART{STARTDATE} update indexes','dd',15,-365,1);

commit work;
