pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["2__gadget.htm","가젯","가젯 Top Previous Next 가젯은 Google사의 iGoogle을 모티브로 하여 비활성모드, 축약화면 (Mini Gadget), 최대화면 (Max Gadget)의 형태를 지니며 각 가젯별로 가젯 비활성화, 활성화, 도움말, 새로 고침, 최대화, 최소화...",""],
["3__dashboard_and_gadget_manage.htm","대시보드&#38;가젯 설정","대시보드&#38;가젯 설정 Top Previous Next 우측 상단의 가젯 설정(Gadget Setting) 버튼을 클릭하면 사용자 별 대시화면과 가젯을 설정할 수 있습니다. 대시보드 설정 대시보드 기본 정보 가젯 설정 각 대시보드 별로 보고 싶은 가젯을 골라 볼 수...",""],
["4__help.htm","4. Help","도움말 Top Previous Next 도움말 화면에서는 AiMiR 3.0 에 대한 설명 및 각 가젯 별 도움말 보기 기능을 제공합니다. 상단의 HELP 링크를 클릭하면 전체 도움말 페이지를 볼 수 있으며, 각 가젯 별로 가젯 우측 상단의 ‘?’ 를 클릭하면 가...",""],
["abnormal_contract_customers.htm","계약용량 이상 고객(전기)","계약용량 이상 고객(전기) Top 전기 사용 고객들중 사용량이 비정상이거나 계약용량보다 실제 사용량이 더 큰 고객 목록을 조회할 수 있는 가젯입니다. 계약시 정한 계약 용량과 실제 사용량을 비교하여 정상적인 사용량이 아닐 경우 이를 쉽게 확인 할 수 있습니다. ...",""],
["aimir_ami_system.htm","AiMiR AMI System","AiMiR AMI System Top Previous Next AiMiR Metering System은 원격에 있는 Meter로부터 주기적(Event-Driven, Asynchronous) 또는 On-demand (Polling, Synchronous) 방식으로...",""],
["alarmevent.htm","Alarm&#38;Event","Alarm&#38;Event Top Previous Next 단 말기와 계기 사이 Interface, 단말기 내부 및 Metering Data Transmission Path 상 비정상 상태 그리고 수신된 검침 데이터 오류로 인한 Alarm, Event 정보를 생성, ...",""],
["alarm_event.htm","Alarm, Event Gadget","Alarm, Event Gadget Top ",""],
["analysis_of_metering_data.htm","Analysis of Metering Data","Analysis of Metering Data Top Previous Next Calendar (Monthly) Chart 특 정 고객에 대해 특정 월에 대한 일별 사용량 Graph를 Calendar 형식으로 보여줌. Weekday별, Weekend별 또는 특정...",""],
["battery_log.htm","Battery Log","Battery Log Top 통신장비(모뎀)의 배터리 정보 및 배터리 정보 이력 등의 정보를 제공하여 대략적인 배터리 상태 및 수명을 알 수 있게 정보를 제공합니다 Mini Gadget 센서 타입이 ZEUPLS 이거나 리피터인 경우 검침 데이터에 포함되어 있는 ...",""],
["chapter_2.htm","Introduction of AiMiR","Introduction of AiMiR Top Next 저작권 및 등록상표 AIMIR&#174; 는 누리텔레콤의 등록상표입니다. 사용자 공지 이 문서에 포함되어 있는 어떠한 정보도 기능 향상 등을 이유로 사전 통보 없이 변경 및 수정되어질 수 있으며, 누리텔레콤은 본 문...",""],
["circuit_breaker_management.htm","Load Management","Load Management Top Enter topic text here. ",""],
["circuit_breaker_management2.htm","Circuit Breaker Management","Circuit Breaker Management Top 공급 차단 재개 Mini Gadget Max Gadget 비상시 차단할 수 있게 해당 대상을 검색하여 바로 차단할 수 있게 합니다. 엑셀 출력 기능을 제공합니다. 선불 임계치 , 공 전력 임계치, 비상 전력...",""],
["co2_management.htm","탄소배출량 관리","탄소배출량 관리 Top Previous Next 전기, 가스, 수도 별 탄소 배출량을 관리하며 에너지별 사용량을 탄소 배출량으로 환산하여 보여줍니다. 공급사 관리 정보에서 각 에너지원 별 CO2발생량에 관한 정보를 확인 할 수 있습니다. 검침데이터 화면에서 사용...",""],
["code_management.htm","코드 관리","코드 관리 Top 시스템에서 관리하는 코드의 정의 및 코드 목록, 코드 정보 추가/수정 삭제 기능을 제공합니다. 미니 가젯 시스템에 등록된 코드 정보를 간단히 검색 및 추가/삭제 하는 기능을 제공합니다. 검색 : 검색창에 검색하려는 코드명 또는 코드값을 입력 후...",""],
["communication_log.htm","Communication Log","Communication Log Top 통신 장비 별 통신 타입, 통신 시간, 통신 양 등에 대한 정보를 제공 Mini Gadget 기본적으로 일주일 치의 데이터를 보여줍니다. Max Gadget ",""],
["concentrator_mangement.htm","Concentrator Mangement","Concentrator Mangement Top 공사에서 관리하는 집중기 목록 및 상세 정보, 집중기 별 검침스케줄 설정, 집중기 설치 위치 정보 , 집중기 설정 및 제어 등의 기능을 제공 Mini Gadget Max Gadget Basic Information...",""],
["configuration.htm","Configuration","Configuration Top Previous Next Metering Application 운용에 필요한 제반 설정 정보를 관리합니다. 관리되는 정보는 다음과 같습니다. User Group 및 User Customer 정보 관리 Equipment Group ...",""],
["consumption_ranking.htm","소비 랭킹(전기)","소비 랭킹(전기) Top 전기, 수도, 가스, 열량 고객들을 에너지 소비량에 따라 분류하여 보여주는 가젯입니다. 이 가젯은 에너지 종류에 따라 각각 별도의 가젯으로 분리하여 제공되고 있습니다.(ex : 전기 소비 랭킹 가젯, 수도 소비 랭킹가젯, etc.) 사용...",""],
["customer_and_contract.htm","고객 및 계약 관리","고객 및 계약 관리 Top 공사별 고객 정보, 계약 정보, 선불 고객 관리, 계약 변경 내역, 월별 사용량 등의 정보를 제공합니다. 미니 가젯 고객의 계약 상태와 계약 종별 통계를 간단히 확인할 수 있습니다. 1. 계약 상태 전체 고객 중 고객의 계약 상태에 따...",""],
["dash_board.htm","대시보드","대시보드 Top Previous Next 대시보드는 다양한 정보를 한 곳에 모아 관리하고 사용할 수 있도록 하는 사용자 인터페이스(UI) 단위입니다. AiMiR 3.0은 하나의 특화된 기능을 하나의 가젯(Gadget)으로 제공하고 있습니다. 대시보드를 이용하면 ...",""],
["data_gaps.htm","주기별 데이터 누락 관리","원격 검침 시스템은 시스템 내부적, 외부적 요인에 의해 검침이 누락 되는 경우가 발생할 수 있습니다. 이 가젯은 검침데이터가 누락된 미터들에 대해 기간별로 누락 상태를 조회할 수 있는 기능을 제공하는 가젯입니다. 미니 가젯 Max Gadget 엑셀 출력 기능을 ...",""],
["data_gapselectricity.htm","Data Gaps(Electricity)","Data Gaps(Electricity) Top Previous Next 원격 검침 시스템은 시스템 내부적, 외부적 요인에 의해 검침이 누락 되는 경우가 발생할 수 있습니다. 이 가젯은 검침데이터가 누락된 미터들에 대해 기간별로 누락 상태를 조회할 수 있는 기능...",""],
["demand_management.htm","수요 관리","수요 관리 Top 수요관리(Demand Side Management)는 최소의 비용으로 소비자의 전기사용패턴을 합리적인 방향으로 유도하여 전기에너지 서비스 욕구를 충족시키기 위한 전력회사의 제반 활동입니다. 전력공설비 확충에 중점을 두어온 공급관리(Supply ...",""],
["device_dashboard.htm","장비관리 및 이력관리","장비관리 및 이력관리 Top Previous Next 이번 섹션에서는 장비 관리 및 이력 관리에 대한 다양한 형태의 가젯 설명이 담겨있습니다. 장비, 이벤트, 정전, 펌웨어, 집중기 등의 관리 기능을 제공하며, 명령이력, 미터시간, 통신이력 등 의 이력 관리 기...",""],
["device_registration.htm","Device Registration","Device Registration Top 장비에 대한 개별, 일괄 등록 기능 등록 장비에 대한 이력 관리 (개별, 일괄, 연동, 자동 등 미터의 등록 타입 별로 관리 Mini Gadget Max Gadget ",""],
["device_vendor_model.htm","제조사 모델 관리","제조사 모델 관리 Top 시스템에서 사용하는 장비의 제조사, 모델 정보 및 특정 모델에 특화된 정보조회, 모델 사진 등의 서비스를 제공 미니 가젯 현재 시스템에 등록되어 있는 장비 목록을 간단하게 확인 할 수 있습니다. 장비별, 제조사별로 정렬할 수 있습니다. ...",""],
["electricity_meter.htm","ZRU(ZigBee Meter Reading Unit for Electricity Meter)","ZRU(ZigBee Meter Reading Unit for Electricity Meter) Top Previous Next 전기 계량기와 기 정의된 Interface(RS-232)를 통해 통신 경로를 설정하고 상위 시스템인 집중기와는 ZigBee를 이용하여 ...",""],
["electricity_sales.htm","Electricity sales","Electricity sales Top 공사가 관리하는 고객의 월별 사용량 및 사용금액 정보를 제공 Mini Gadget Max Gadget ",""],
["event_alarm_log.htm","Event Alarm Log","Event Alarm Log Top 시스템 및 장비에서 발생한 모든 이벤트들에 대해 실시간 보기 및 이벤트 이력 조회, 이벤트 보기 설정 등에 대한 정보를 제공 ",""],
["gadget_descr_device010.htm","공급 차단 재개 관리","공급 차단 재개 관리 Top Previous Next 비상시 차단할 수 있게 해당 대상을 검색하여 바로 차단할 수 있게 합니다. 미니가젯 맥스가젯 엑셀 출력 기능을 제공합니다. 선불 임계치 , 공 전력 임계치, 비상 전력 차단 시 설정 값 등을 셋팅 합니다. 전...",""],
["gadget_descr_device011.htm","배터리 관리","배터리 관리 Top Previous Next 통신장비(모뎀)의 배터리 정보 및 배터리 정보 이력 등의 정보를 제공하여 대략적인 배터리 상태 및 수명을 알 수 있게 정보를 제공합니다. 미니 가젯 모뎀 타입(센서 타입)이 ZEUPLS 이거나 ZBRepeater(리피...",""],
["gadget_device001.htm","집중기 관리","집중기 관리 Top Previous Next 공사에서 관리하는 집중기 목록 및 상세 정보,집중기 별 검침스케줄 설정,집중기 설치 위치 정보,집중기 설정 및 제어 등의 기능을 제공 미니 가젯 집중기관리 미니 버전은 아래와 같이 2개의 패널로 구성되어 있습니다. 1...",""],
["gadget_device002.htm","모뎀관리","모뎀관리 Top Previous Next 모뎀 종류별, 지역별, 통신 상태 별 모뎀 목록 관리 및 장비 추가, 삭제 기능 제공합니다. 특정 모뎀에 대한 LP log, Event Log, Unit Scanning, Monitoring, Firmware Update...",""],
["gadget_device003.htm","미터관리","미터관리 Top Previous Next 전기,가스, 수도, 열량 미터 등 공사가 공하는 에너지원 목록 및 상세 정보 연관된 장치 정보, 미터 별 검침데이터 ,위치 정보, 미터 설치 정보 사진 등을 제공 미니가젯 미터관리 미니 버전은 아래와 같이 2개의 패널로 ...",""],
["gadget_device004.htm","장비등록","장비등록 Top Previous Next 장비에 대한 개별, 일괄 등록 기능, 등록 장비에 대한 이력 관리(개별, 일괄, 연동, 자동 등 미터의 등록 타입 별로 관리) 미니가젯 등록되어 있는 집중기, 모뎀, 미터, 고객, 계약의 개수를 Pie Chart와 Col...",""],
["gadget_device005.htm","이벤트 관리","이벤트 관리 Top Previous Next 시스템 및 장비에서 발생한 모든 이벤트들에 대해 실시간 보기 및 이벤트 이력 조회, 이벤트 보기 설정 등에 대한 정보를 제공합니다. 미니가젯 이벤트관리 미니 버전은 2개의 탭로 구성되어 있습니다. 장비 별 이벤트 타입...",""],
["gadget_device006.htm","통신이력관리","통신이력관리 Top Previous Next 통신 장비 별 통신 타입, 통신 시간, 통신 양 등에 대한 정보를 제공합니다. 미니가젯 기본 조회에서는 일주일치의 통신 로그를 송수신으로 구분하여 챠트로 표현합니다. 맥스가젯 통신이력관리 맥스 버전은 4개의필드로 구성...",""],
["gadget_device007.htm","미터 시간관리","미터 시간관리 Top Previous Next 미터와 서버시간과의 오차 정보, 미터 타임 설정 이력, 미터 타임 설정에 대한 임계치 설정 등의 서비스 제공합니다. 미니가젯 일반 조회에서는 미터와 서버시간과의 오차 정보, 미터 타임 설정 이력등의 서비스를 제공합니...",""],
["gadget_device008.htm","장비 맵 관리","장비 맵 관리 Top Previous Next Google Map 서비스와 연계 하여 주소 혹은 장비 아이디로 위치 찾기 제공 및 장비에 연관된 장비들 위치 표시등의 기능을 제공합니다. 미니가젯 맥스가젯 ",""],
["gadget_device009.htm","정전 관리","정전 관리 Top Previous Next 미터의 정전 내역, 기간, 및 복구 내역, 장기간 정전, 짧은 정전 이력, 결상 발생 복구 내역 등의 정보를 제공합니다. 미니가젯 정전관리 미니 버전은 아래와 같이 2개의 탭으로 구성되어 있습니다. 정전/복구 내역 결상...",""],
["gadget_device010.htm","Circuit Breaker Management","Circuit Breaker Management Top Previous Next 공급 차단 재개 Mini Gadget Max Gadget 비상시 차단할 수 있게 해당 대상을 검색하여 바로 차단할 수 있게 합니다. 엑셀 출력 기능을 제공합니다. 선불 임계치 , 공...",""],
["gadget_device011.htm","Battery Log","Battery Log Top Previous Next 통신장비(모뎀)의 배터리 정보 및 배터리 정보 이력 등의 정보를 제공하여 대략적인 배터리 상태 및 수명을 알 수 있게 정보를 제공합니다 Mini Gadget 센서 타입이 ZEUPLS 이거나 리피터인 경우 검침...",""],
["gadget_device013.htm","미터 이벤트 로그","미터 이벤트 로그 Top Previous Next 미터 이벤트 로그는 미터에서 발생하는 이벤트, Warning, Error 등의 정보를 차트 혹은 데이터로 요악하거나 발생 빈도별, 미터별, 기간별로 미터 이벤트 이력 정보를 조회하게 합니다. 해당 이벤트 로그에 ...",""],
["gadget_device014.htm","펌웨어관리","펌웨어관리 Top Previous Next 1. 사용자 설명서 A. 펌웨어 파일관리 1. 배포할 파일을 등록하거나 수정 할 수 있는 기능을 제공 합니다. a) 펌웨어 등록 할 펌웨어 버전 정보 및 상세정보를 입력 할 수 있습니다. b) 등록할 펌웨어 정보를 입력...",""],
["gadget_device016.htm","로그분석 관리","로그분석 관리 Top Previous 장비에서 내린 명령을 기준으로 검색 조건(분 단위)에 해당되는 명령 이력과, 통신 이력, 이벤트 이력 정보를 제공합니다. 미니 가젯 조회조건( 날짜, 검색 범위)에 따라 명령이 발생한 시점 이후부터 검색범위(분 단위) 이내에...",""],
["gadget_metering001.htm","검침차트","검침차트 Top Previous Next 전기, 가스, 수도, 열량 공타입 별 가젯으로 지역별 검침 률 현황과 각 미터의 검침데이터 수치를 검침기간별, 지역별, 고객별로 조회할 수 있는 기능을 제공합니다. 검침 상세에서 조회한 내용을 차트로 도표화하여 제공합니다...",""],
["gadget_metering00111111.htm","빌링데이터(전기)","빌링데이터(전기) Top Previous Next 공급사가 관리하는 고객의 월별 사용량 및 사용금액 정보를 제공 미니가젯 맥스가젯 ",""],
["gadget_metering00122222.htm","*빌링리포트(전기)","*빌링리포트(전기) Top Previous Next 전개 고객별 일별,월별 TOU사용량 조회 ",""],
["gadget_metering005.htm","검침실패(전기)","검침실패(전기) Top Previous Next 검침 실패 고객들에 대한 통계 및 실패 원인, 재 검침 서비스 등의 정보를 제공합니다. 미니가젯 검침실패 미니 버전은 2가지 패널로 구성됩니다. 1. 일별, 기간별, 주별, 월별 데이터 조회 2. 검침 실패율 표시...",""],
["gadget_metering008.htm","Data Gaps(Electricity)","원격 검침 시스템은 시스템 내부적, 외부적 요인에 의해 검침이 누락 되는 경우가 발생할 수 있습니다. 이 가젯은 검침데이터가 누락된 미터들에 대해 기간별로 누락 상태를 조회할 수 있는 기능을 제공하는 가젯입니다. 미니 가젯 맥스가젯 엑셀 출력 기능을 제공합니다. ",""],
["gadget_metering012.htm","소비 랭킹(전기)","소비 랭킹(전기) Top Previous Next 전기, 수도, 가스, 열량 고객들을 에너지 소비량에 따라 분류하여 보여주는 가젯입니다. 이 가젯은 에너지 종류에 따라 각각 별도의 가젯으로 분리하여 제공되고 있습니다. (ex : 전기 소비 랭킹 가젯, 수도 소비...",""],
["gadget_metering016.htm","빌링데이터(전기)","빌링데이터(전기) Top Previous Next 공급사가 관리하는 고객의 월별 사용량 및 사용금액 정보를 제공합니다. 미니가젯 빌링데이터(전기) 미니 버전은 아래와 같이 2개의 패널로 구성되어 있습니다. 1. 일별, 주별, 월별 및 지역 별 데이터 조회 2. ...",""],
["gadget_metering017.htm","Gas sales","Gas sales Top Previous Next Enter topic text here. ",""],
["gadget_metering018.htm","Water sales","Water sales Top Previous Next Enter topic text here. ",""],
["gadget_metering019.htm","Heat sales","Heat sales Top Previous Next Enter topic text here. ",""],
["gadget_metering020.htm","수요 관리","수요 관리 Top Previous Next 수요관리(Demand Side Management)는 최소의 비용으로 소비자의 전기사용패턴을 합리적인 방향으로 유도하여 전기에너지 서비스 욕구를 충족시키기 위한 전력회사의 제반 활동입니다. 전력공설비 확충에 중점을 두어...",""],
["gadget_metering021.htm","PQ데이터관리","PQ데이터관리 Top Previous Next 전기의 전력 품질(Voltage, Current) , Voltage Level, Voltage Imbalance 정보를 제공합니다. 미니가젯 전기 미터의 경우 검침 주기 별 전력 품질데이터를 의미합니다. 전기 미터의...",""],
["gadget_metering022.htm","SLA가젯","SLA가젯 Top Previous Next 검침에 대한 전반적인 성공률 지표 및 분석 가젯입니다. 미니가젯 조회한 기간에 대한 SLA 성공률을 차트로 나타냅니다. 맥스가젯 SLA 맥스 버전은 2개의 탭으로 구성되어 있습니다. SLA 전체 분석 탭 검침성공률 분석...",""],
["gadget_metering023.htm","VEE Management","VEE Management Top Previous Next VEE (Metering Data Validation, Estimation, Editing) 에너지 공급자 소비자는 실시간 데이터에 대한 정확성 있는 데이터를 제공받기를 원하고 있으며 이런 기능을 VEE...",""],
["gadget_metering023_electricity.htm","VEE(전기)","VEE(전기) Top Previous Next 검침데이터에 대한 Valication Check, Editing Estimation을 할 수 있는 기능을 제공하며 Editing Estimation을 했던 이력등을 조회할 수 있는 기능을 제공합니다. Mini Gad...",""],
["gadget_metering024.htm","계약용량 이상 고객(전기)","계약용량 이상 고객(전기) Top Previous Next 전기 사용 고객들중 사용량이 비정상이거나 계약용량보다 실제 사용량이 더 큰 고객 목록을 조회할 수 있는 가젯입니다. 계약시 정한 계약 용량과 실제 사용량을 비교하여 정상적인 사용량이 아닐 경우 이를 쉽게...",""],
["gadget_metering025.htm","빌링리포트(전기)","빌링리포트(전기) Top Previous Next 이 가젯은 미터에서 저장하는 TOU(Time Of Use)별 에너지 사용량 및 전체 에너지 사용량, 누적 에너지 사용정보를 엑셀로 출력할 수 있는 가젯입니다. 미니가젯 빌링리포트(전기) 미니 버전은 3가지 패널로...",""],
["gadget_metering026.htm","빌링데이터(전기)","빌링데이터(전기) Top Previous Next 공급사가 관리하는 고객의 월별 사용량 및 사용금액 정보를 제공 미니가젯 맥스가젯 ",""],
["gadget_system001.htm","코드관리","코드관리 Top Previous Next 시스템에서 관리하는 코드의 정의 및 코드 목록, 코드 정보 추가/수정 삭제 기능을 제공합니다. 미니 가젯 코드관리 미니 버전은 코드 내역을 볼 수 있고 코드에 대한 검색 기능을 제공합니다. 맥스 가젯 시스템에 등록된 코드...",""],
["gadget_system002.htm","제조사 모델 관리","제조사 모델 관리 Top Previous Next 시스템에서 사용하는 장비의 제조사, 모델 정보 및 특정 모델에 특화된 정보조회, 모델 사진 등의 서비스를 제공 합니다. 미니 가젯 현재 시스템에 등록되어 있는 장비 목록을 간단하게 확인 할 수 있습니다. 장비별,...",""],
["gadget_system003.htm","공급사 관리","공급사 관리 Top Previous Next 공급사에서 관리하는 지역관리, 공급사 정보, 공급사가 제공하는 공급 서비스(전기, 가스, 수도 등)에 대한 정보, 과금 정보 관리 등의 서비스를 제공합니다. 미니 가젯 로그인한 사용자의 공급사 정보를 보여줍니다. 로그...",""],
["gadget_system004.htm","사용자 관리","사용자 관리 Top Previous Next 사용자 계정관리, 사용자 별 권한 관리, 사용자 그룹관리 서비스 제공합니다. 미니 가젯 사용자 관리 미니 버전은 2개의 패널로 구성되어 있습니다. 1. 사용자 그룹 선택 2. 사용자 그룹에 따른 사용자 목록 1. 사용...",""],
["gadget_system008.htm","명령이력관리","명령이력관리 Top Previous Next 장비에 내린 명령(Operation)들의 목록과 각각의 시도 횟수, 성공률 등을 차트로 제공합니다. 장비 별로 시스템에서 제어할 수 있는 명령들에 대한 설정 및 시스템에서 지시한 명령 수행 이력들에 대한 정보를 제공합...",""],
["gadget_system009.htm","그룹관리","그룹관리 Top Previous Next 그룹 추가/수정/삭제, 그룹멤버 관리 가젯입니다. 미니가젯 그룹 관리 미니 버전은 2가지 패널로 구성됩니다. 1. 그룹 타입, 그룹 명 검색 2. 그룹 목록 1. 그룹 타입, 그룹 명 검색 그룹 타입과 그룹 명으로 등록되...",""],
["gadget_system010.htm","고객계약관리","고객계약관리 Top Previous Next 공사별 고객 정보, 계약 정보, 선불 고객 관리, 계약 변경 내역, 월별 사용량 등의 정보를 제공합니다. 미니 가젯 고객의 계약 상태와 계약 종별 통계를 간단히 확인할 수 있습니다. 고객 및 계약 관리 미니 버전은 아...",""],
["gadget_system011.htm","*스케줄 관리","*스케줄 관리 Top Previous Next Enter topic text here. ",""],
["gadget_system012.htm","홈 그룹 관리","홈 그룹 관리 Top Previous Next 홈 그룹 추가/수정/삭제, 그룹멤버 관리 가젯입니다. 미니가젯 홈 그룹 관리 미니 버전은 2가지 패널로 구성됩니다. 1. 그룹 타입, 그룹 명 검색 2. 그룹 목록 1. 그룹 타입, 그룹 명 검색 그룹 타입과 그룹 ...",""],
["gadget_system013.htm","스케줄 관리","스케줄 관리 Top Previous Next 스케줄을 관리 가젯입니다. 미니가젯 스케줄관리 미니 버전은 아래와 같이 2개의 패널로 구성되어 있습니다. 1. 모든 작업의 상태 및 개수 2. 해당하는 작업의 상태 표시 1. 모든 작업의 상태 및 개수 All, Blo...",""],
["gas_sales.htm","Gas sales","Gas sales Top Enter topic text here. ",""],
["google_map_for_device.htm","Google Map For Device","Google Map For Device Top Google Map 서비스와 연계 하여 주소 혹은 장비 아이디로 위치 찾기 제공 및 장비에 연관된 장비들 위치 표시등의 기능을 제공합니다 Mini Gadget Max Gadget ",""],
["group_management.htm","그룹 관리","그룹 관리 Top 사용자 그룹과는 별도로 AiMiR 에서는 검침 장비, 장소 등을 종류별로 그룹을 만들어 관리 할 수 있습니다. 그룹을 만들 수 있는 그룹타입은 Location, Operator, Contract, MCU, Modem, Meter, EndDevi...",""],
["heat_sales.htm","Heat sales","Heat sales Top Enter topic text here. ",""],
["main_features.htm","Main Features","Main Features Top Previous Next Enter topic text here. ",""],
["mcumaster_control_unit.htm","MCU(Master Control Unit)","MCU(Master Control Unit) Top Previous Next 상 위 시스템인 원격검침 서버(NACS)로부터의 명령을 단말기 또는 계기로 전송하거나 스스로 단말기 또는 계기와 통신하여 기 정의된 Task를 수행합니다. 또한 여러 종류의 자체 스케줄...",""],
["metering_dashboard.htm","검침데이터 관리","검침데이터 관리 Top Previous Next 이번 섹션에서는 검침데이터를 관리하는 다양한 형태의 가젯에 대한 설명이 담겨있습니다. 전기, 수도 혹은 가스 등의 계량기에 기록된 검침값을 원격으로 확인하고 이를 응용해 검침 상태, 사용량, 품질 등을 확인하고 관...",""],
["metering_data.htm","Metering Data(Electricity)","Metering Data(Electricity) Top Mini Gadget 전기, 가스, 수도, 열량 공타입 별 가젯으로 지역별 검침 률 현황과 각 미터의 검침데이터 수치를 검침기간별, 지역별, 고객별로 조회할 수 있는 기능을 제공합니다. 검침 상세에서 조회한...",""],
["metering_fail.htm","Metering Fail(Electricity)","Metering Fail(Electricity) Top Mini Gadget Max Gadget 엑셀 출력 기능을 제공합니다. 검침 실패 고객들에 대한 통계 및 실패 원인, 재 검침 서비스 등의 정보를 제공 엑셀 출력 기능을 제공합니다. ",""],
["metering_management.htm","Metering Management","Metering Management Top Previous Next Data Collection &#38; Transmission 각 각의 단말기 (Terminal Unit)는 설정된 검침 스케줄에 따라 계량기로부터 조회 또는 Pulse Counting을 통해 검침 데...",""],
["metering_sla.htm","검침 서비스 분석","검침 서비스 분석 Top 검침에 대한 전반적인 성공률 지표 및 분석 기능을 제공합니다. 기본적으로 총 설치된 미터 개수 대비 검침률 미니 가젯 기간별 검색 기능을 제공합니다. 맥스 가젯 ",""],
["metering_statistics.htm","Metering Statistics","Metering Statistics Top Previous Next Metering Statistics 다양한 주기별 검침 성공 통계 정보를 조회하며 실패한 고객 목록을 조회할 수 있다. 또한 이러한 검침 통계를 계기별, 집중기별 및 사용자 정의 그룹별로 조회할...",""],
["meter_management.htm","Meter Management","Meter Management Top 전기,가스, 수도, 열량 미터 등 공사가 공하는 에너지원 목록 및 상세 정보 연관된 장치 정보, 미터 별 검침데이터 ,위치 정보, 미터 설치 정보 사진 등을 제공 Mini Gadget 해당 검색 조건에 해당하는 미터 중 정상...",""],
["meter_time_management.htm","Meter Time Management","Meter Time Management Top 미터와 서버시간과의 오차 정보, 미터 타임 설정 이력, 미터 타임 설정에 대한 임계치 설정 등의 서비스 제공 Mini Gadget Max Gadget 미터 시간차를 구간별로 그래프로 표시해줌 일치, 1~12시간, 1...",""],
["modem_management.htm","Modem Management","Modem Management Top 모뎀 종류별, 지역별, 통신 상태 별 모뎀 목록 관리 및 장비 추가, 삭제 기능 제공 특정 모뎀에 대한 LP log, Event Log, Unit Scanning, Monitoring 기능 제공 Mini Gadget 연결되어...",""],
["nacsnuri_aimir_center_system.htm","NACS(Nuri AiMiR Center System)","NACS(Nuri AiMiR Center System) Top Previous Next WEB User Interface를 통해 수행되는 사용자 명령을 수신하여 특정 장치(집중기, 단말기 또는 계기)로 전송하고 해당 결과를 다시 사용자에게 전달합니다. 또한 주기...",""],
["operation_management.htm","Operation Management","Operation Management Top 장비에 내린 명령(Operation)들의 목록과 각각의 시도 횟수, 성공률 등을 차트로 제공 장비 별로 시스템에서 제어할 수 있는 명령들에 대한 설정 및 시스템에서 지시한 명령 수행 이력들에 대한 정보를 제공 Mini...",""],
["overview.htm","Overview","Overview Top Previous Next 이 문서는 AIMIR 3.0 버전의 신규 기능 및 각 가젯 들에 대해 기술하며 각 세부기능에 대한 설명, 화면 구성에 대한 내용을 설명하고 있습니다. AIMIR 3.0 로그인 화면 해당 시스템의 화면은 1280*1...",""],
["power_alarm_log.htm","PowerAlarmLog","PowerAlarmLog Top 미터의 정전 내역, 기간, 및 복구 내역, 장기간 정전, 짧은 정전 이력, 결상 발생 복구 내역 등의 정보를 제공 Mini Gadget 기본적으로 일주일 치의 데이터를 보여줍니다. Max Gadget ",""],
["power_quality.htm","전력 품질","전력 품질 Top 전기의 전력 품질(Voltage, Current) , Voltage Level, Voltage Imbalance 정보를 제공합니다 전기 미터의 경우에만 Power Quality데이터가 존재하게 되며 검침 주기 별 전력 품질데이터를 의미합니다. ...",""],
["report.htm","Report","Report Top Previous Next 사용자 요구 사항에 맞게 Form을 설계, 보고서를 생성할 수 있는 Engine을 내장하고 있으며, PDF, Excel Export 기능을 제공합니다. 보고서는 각 화면상에 나타나는 \"Print\" 버튼 클릭 시 생성됩...",""],
["supplier_management.htm","공급사 관리","공급사 관리 Top 공급사에서 관리하는 지역관리, 공급사 정보, 공급사가 제공하는 공급 서비스(전기, 가스, 수도 등)에 대한 정보, 과금 정보 관리 등의 서비스를 제공합니다. 미니 가젯 로그인한 사용자의 공급사 정보를 보여줍니다. 로그인한 사용자가 특정 공사에...",""],
["system_dashboard.htm","시스템 관리","시스템 관리 Top Previous Next AiMiR 3.0 을 운영하기 위해서는 고객정보, 공급사 정보, 사용자 정보 및 각종 장비들에 대한 정보가 필요합니다. 시스템 관리 섹션은 이러한 정보들을 관리하는 가젯들에 대해 소개하고 기능들에 대한 설명을 담고 있...",""],
["system_management.htm","System Management","System Management Top Previous Next Local Unit(Meter unit), Terminal Unit, Communication unit에 대한 구성 정보를 관리합니다. Metering Application에 관련된 모든 Unit에...",""],
["testpage(elec).htm","testpage(elec)","testpage(elec) Top Enter topic text here. ",""],
["testpage_elec.htm","testpage-elec","testpage-elec Top Enter topic text here. ",""],
["user_management.htm","사용자 관리","사용자 관리 Top 사용자 계정관리, 사용자 별 권한 관리, 사용자 그룹관리 서비스 제공 미니 가젯 사용자 그룹별로 사용자의 목록을 보여줍니다. 사용자의 아이디, 이름, 전화번호, 이메일등의 기본정보를 확인할 수 있습니다. 사용자그룹 리스트 박스를 클릭하면 다른...",""],
["vee.htm","VEE Management","VEE Management Top VEE (Metering Data Validation, Estimation, Editing) 에너지 공급자 소비자는 실시간 데이터에 대한 정확성 있는 데이터를 제공받기를 원하고 있으며 이런 기능을 VEE로 칭합니다.. 유틸리티 ...",""],
["water_sales.htm","Water sales","Water sales Top Enter topic text here. ",""],
["zeu_plszigbee_expansion_unit_p.htm","ZEU-PLS(ZigBee Expansion Unit-Pulse)","ZEU-PLS(ZigBee Expansion Unit-Pulse) Top Previous Next 수도 계량기 같은 펄스형 계기와 기 정의된 Interface(Pulse Cable)를 통해 통신 경로를 설정하고 상위 시스템인 집중기와는 ZigBee를 이용하여 통...",""]];
