pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["aimir.htm","AiMiR","AiMiR Top Next 저작권 및 등록상표 AIMIR&#174; 는 누리텔레콤의 등록상표입니다. 사용자 공지 이 문서에 포함되어 있는 어떠한 정보도 기능 향상 등을 이유로 사전 통보 없이 변경 및 수정되어질 수 있으며, 누리텔레콤은 본 문서의 내용에 대하여 허락없이 ...",""],
["aimirmeteringsystem.htm","AiMiR 검침 시스템","AiMiR 검침 시스템 Top Previous Next 개요 - 전기 계기용 단말기 - 펄스 계기용 단말기 - 집중기 - 원격 검침 서버 주요 기능 - 시스템 관리 - 검침 관리 - 검침 데이터 분석 - 장애 현황 - 통계 관리 - 보고 - 설정 ",""],
["alarm_event.htm","장애 현황","장애 현황 Top Previous Next 단말기와 계기 사이 Interface, 단말기 내부 및 Metering Data Transmission Path 상 비정상 상태 그리고 수신된 검침 데이터 오류로 인한 Alarm, Event 정보를 생성, 실시간 표시 ...",""],
["configuration_mgmt.htm","시스템 관리","시스템 관리 Top Previous Next Local Unit(Meter unit), Terminal Unit, Communication unit에 대한 구성 정보를 관리한다. Metering Application에 관련된 모든 Unit에 대한 구성 정보를 효...",""],
["login.htm","Login","Login Top Previous Next 아래 그림처럼 WEB Browser의 주소 입력창에 WEB URL(예. https://187.1.10.200:8085/aimir-web/)을 입력하면 위와 같이 Login 화면이 생성된다. Login ID 및 Passw...",""],
["main_functions.htm","주요기능","주요기능 Top Previous Next 주요 기능 - 시스템 관리 - 검침 관리 - 검침 데이터 분석 - 장애 현황 - 통계 관리 - 보고 - 설정 ",""],
["main_menu.htm","메인화면 및 메뉴","메인화면 및 메뉴 Top Previous Next [Figure 3] 메인 화면 Main window는 다음과 같은 요소로 구성된다. Top menu() : Top menu 탭을 클릭시 해당 화면으로 이동하며 각 화면에는 설정된 미니 가젯들이 나타난다. Tool...",""],
["mcu.htm","집중기","집중기(MCU, Master Control Unit) Top Previous Next 상위 시스템인 원격검침 서버(NACS)로부터의 명령을 단말기 또는 계기로 전송하거나 스스로 단말기 또는 계기와 통신하여 기 정의된 Task를 수행한다. 또한 여러 종류의 자체 ...",""],
["metering_data_analysis.htm","검침 데이터 분석","검침 데이터 분석 Top Previous Next Calendar (Monthly) Chart 특정 고객에 대해 특정 월에 대한 일별 사용량 Graph를 Calendar 형식으로 보여줌. Weekday별, Weekend별 또는 특정 요일별 사용량 패턴에 대한 규...",""],
["metering_data_mgmt.htm","검침 관리","검침 관리 Top Previous Next Data Collection &#38; Transmission 각각의 단말기 (Terminal Unit)는 설정된 검침 스케줄에 따라 계량기로부터 조회 또는 Pulse Counting을 통해 검침 데이터를 수집하며 전송 스케줄...",""],
["nacs.htm","원격 검침 서버","원격 검침 서버(NACS-Nuri AiMiR Center System) Top Previous Next WEB User Interface를 통해 수행되는 사용자 명령을 수신하여 특정 장치(집중기, 단말기 또는 계기)로 전송하고 해당 결과를 다시 사용자에게 전달한...",""],
["overview.htm","개요","개요 Top Previous Next AiMiR Metering System은 원격에 있는 Meter로부터 주기적(Event-Driven, Asynchronous) 또는 On-demand (Polling, Synchronous) 방식으로 사용량 정보(Usage)...",""],
["report.htm","보고","보고 Top Previous Next 사용자 요구 사항에 맞게 Form을 설계, 보고서를 생성할 수 있는 Engine을 내장하고 있으며, PDF, Excel Export 기능을 제공한다. 보고서는 각 화면상에 나타나는 \"Print\" 버튼 클릭 시 생성된다. ",""],
["settings.htm","설정","설정 Top Previous Next Metering Application 운용에 필요한 제반 설정 정보를 관리한다. 관리되는 정보는 다음과 같다. User Group 및 User Customer 정보 관리 Equipment Group 관리 Code 정보 관리 ",""],
["statistic_log.htm","통계 관리","통계 관리 Top Previous Next Metering Statistics 다양한 주기별 검침 성공 통계 정보를 조회하며 실패한 고객 목록을 조회할 수 있다. 또한 이러한 검침 통계를 계기별, 집중기별 및 사용자 정의 그룹별로 조회할 수도 있다. Log 다음...",""],
["systemmanagement.htm","시스템 관리","시스템 관리 Top Previous Next 개요 - 사용자 관리 ",""],
["usermgmt.htm","사용자 관리","사용자 관리 Top Previous Next - 사용자 관리 미니 가젯 - 사용자 관리 맥스 가젯 ",""],
["usermgmt_max.htm","사용자 관리 맥스 가젯","사용자 관리 맥스 가젯 Top Previous Next 사용자 관리 맥스 가젯은 &#39;그룹정보&#39;와 &#39;그룹사용자목록&#39;의 두 개의 탭으로 나누어져 있다. 화면상단의 콤보박스에서 그룹을 선택할 수 있으며 선택한 그룹에 따라 각각에 해당하는 정보들이 출력되게 된다. 이 콤...",""],
["usermgmt_max_groupinfo.htm","그룹정보","그룹정보 Top Previous Next 그룹 정보을 통해서 시스템에 등록된 모든 사용자 그룹 정보를 조회할 수 있다. &#39;그룹정보&#39; 탭에서는 다음과 같은 기능을 갖는다. 1) 새 그룹 등록 2) 그룹별 기본 정보 조회 및 수정 3) 그룹별 허용 가젯 설정 및 변...",""],
["usermgmt_max_userlist.htm","그룹사용자목록","그룹사용자목록 Top Previous Next 그룹별로 등록된 사용자와 사용자 상세 정보를 조회할 수 있다. &#39;그룹사용자목록&#39;에서는 다음과 같은 기능을 갖는다. 1) 그룹별 사용자 리스트 조회 2) 새 사용자 추가 및 삭제 3) 각 사용자 기본 정보 &#38; 상세정보...",""],
["usermgmt_mini.htm","사용자 관리 미니 가젯","사용자 관리 미니 가젯 Top Previous &#39;사용자 관리 미니 가젯&#39;에는 각 사용자의 기본 정보를 확인할 수 있다. 이 때, 사용자 리스트는 사용자 그룹별로 나워져 있으며 수정은 불가능하다. 각 필드의 그리드 바를 클릭시 해당 필드에 대하여 정렬이 이루어 진...",""],
["zeu_pls.htm","펄스 계기용 단말기","펄스 계기용 단말기(ZEU-PLS, ZigBee Expansion Unit - Pulse) Top Previous Next 수도 계량기 같은 펄스형 계기와 기 정의된 Interface(Pulse Cable)를 통해 통신 경로를 설정하고 상위 시스템인 집중기와는 ...",""],
["zru.htm","전기 계기용 단말기","전기 계기용 단말기(ZRU, ZigBee Meter Reading Unit) Top Previous Next 전기 계량기와 기 정의된 Interface(RS-232)를 통해 통신 경로를 설정하고 상위 시스템인 집중기와는 ZigBee를 이용하여 통신한다. 즉 계량...",""]];
