drop table "AIMIR"."PREPAYMENTLOG"  CASCADE CONSTRAINTS;

CREATE TABLE "AIMIR"."PREPAYMENTLOG"
(
   ID decimal(19) PRIMARY KEY NOT NULL,
   ADDITIONALSUBSIDY float(126),
   ARREARS float(126),
   AUTH_CODE varchar2(255),
   BALANCE float(126),
   CANCEL_DATE varchar2(255),
   CHARGEDARREARS float(126),
   CHARGEDCREDIT float(126),
   CONTRACT_ID decimal(10),
   CUSTOMER_ID decimal(10),
   DAYS_FROM_CHARGE decimal(10),
   DESCR varchar2(255),
   EMERGENCYCREDITAVAILABLE decimal(10),
   GOVLEVY float(126),
   INIT_CREDIT float(126) DEFAULT 0,
   IS_CANCELED decimal(1),
   KEYNUM varchar2(255),
   KEYTYPE_ID decimal(10),
   LAST_LP_TIME varchar2(255),
   LASTTOKENDATE varchar2(14) NOT NULL,
   LASTTOKENID varchar2(255),
   LIFELINESUBSIDY float(126),
   MONTHLYPAIDAMOUNT float(126),
   MONTHLYSERVICECHARGE float(126),
   MONTHLYTOTALAMOUNT float(126),
   MUNICIPALITYCODE_ID decimal(10),
   OPERATOR_ID decimal(10),
   POWER_LIMIT float(126),
   PRE_ARREARS float(126),
   PRE_BALANCE float(126),
   PUBLICLEVY float(126),
   SUBSIDY float(126),
   USED_CONSUMPTION float(126),
   USED_COST float(126),
   VAT float(126),
   VATONSUBSIDY float(126),
   VENDORCASHER_ID decimal(10)
)
partition by HASH (CONTRACT_ID)
PARTITIONS 512
store in (AIMIRDATHASH0001, AIMIRDATHASH0002, AIMIRDATHASH0003, AIMIRDATHASH0004, AIMIRDATHASH0005,
AIMIRDATHASH0006, AIMIRDATHASH0007, AIMIRDATHASH0008, AIMIRDATHASH0009, AIMIRDATHASH0010)
;
ALTER TABLE "AIMIR"."PREPAYMENTLOG"
ADD CONSTRAINT FK9E8A0641E78D63C7
FOREIGN KEY (OPERATOR_ID)
REFERENCES "AIMIR"."OPERATOR"(ID)
;
ALTER TABLE "AIMIR"."PREPAYMENTLOG"
ADD CONSTRAINT FK9E8A06415CF66507
FOREIGN KEY (CONTRACT_ID)
REFERENCES "AIMIR"."CONTRACT"(ID)
;
ALTER TABLE "AIMIR"."PREPAYMENTLOG"
ADD CONSTRAINT FK9E8A0641D907B9AB
FOREIGN KEY (MUNICIPALITYCODE_ID)
REFERENCES "AIMIR"."CODE"(ID)
;
ALTER TABLE "AIMIR"."PREPAYMENTLOG"
ADD CONSTRAINT FK9E8A064198A289FB
FOREIGN KEY (KEYTYPE_ID)
REFERENCES "AIMIR"."CODE"(ID)
;
ALTER TABLE "AIMIR"."PREPAYMENTLOG"
ADD CONSTRAINT FK9E8A0641B7D46187
FOREIGN KEY (CUSTOMER_ID)
REFERENCES "AIMIR"."CUSTOMER"(ID)
;
ALTER TABLE "AIMIR"."PREPAYMENTLOG"
ADD CONSTRAINT FK9E8A0641C2343C93
FOREIGN KEY (VENDORCASHER_ID)
REFERENCES "AIMIR"."VENDOR_CASHER"(ID)
;
CREATE UNIQUE INDEX SYS_C004778 ON "AIMIR"."PREPAYMENTLOG"(ID)
;
