REM DEFAULT     TABLESPACE AIMIRDBDAT
REM TEMPORARY   TABLESPACE AIMIRDBTMP
REM INDEX       TABLESPACE AIMIRDBIDX
REM register user

REM comments QUOTA lines to create on ORACLE 10g
REM
CREATE USER aimir IDENTIFIED BY aimir
DEFAULT     TABLESPACE AIMIRDAT
TEMPORARY   TABLESPACE AIMIRTMP;

GRANT CONNECT,DBA TO aimir;
-- GRANT CONNECT,RESOURCE TO aimir
-- GRANT CREATE ANY JOB TO aimir;

REM 11g의 경우 계정 기간 제한이 있음.
SELECT * FROM DBA_PROFILES WHERE PROFILE='DEFAULT';
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;