DECLARE
  TYPE TABLE_NAME_ASIS_ROW IS RECORD(TABLE_NAME VARCHAR2(100));
  TABLE_NAME_ASIS TABLE_NAME_ASIS_ROW;
  TYPE INDEX_NAME_ASIS_ROW IS RECORD(INDEX_NAME VARCHAR2(100));
  INDEX_NAME_ASIS INDEX_NAME_ASIS_ROW;
  STMT VARCHAR2(250);
BEGIN
FOR TABLE_NAME_ASIS IN
(SELECT table_name FROM ALL_ALL_TABLES WHERE OWNER = 'AIMIR' AND TABLE_NAME LIKE '%#_EM' ESCAPE '#' UNION SELECT 'METERTIMESYNC_LOG' as table_name FROM DUAL)
LOOP 
  FOR INDEX_NAME_ASIS IN 
    (SELECT INDEX_NAME FROM USER_INDEXES WHERE TABLE_NAME = TABLE_NAME_ASIS.table_name AND UNIQUENESS = 'UNIQUE' AND INDEX_NAME LIKE 'SYS_%')
    LOOP
      STMT := 'ALTER INDEX '||INDEX_NAME_ASIS.INDEX_NAME||' RENAME TO '||TABLE_NAME_ASIS.table_name||'_PK';
      EXECUTE IMMEDIATE STMT;     
    END LOOP;
END LOOP;
END;